### ISSUE TITLE
iframe errors

### ISSUE THREAD

**Issue by glekner** [pmmmwh/react-refresh-webpack-plugin#105]
![image](https://user-images.githubusercontent.com/24938324/83424106-a31c0a80-a434-11ea-8f98-1977ac09e248.png)

These errors started after adding react-refresh and babel (typescript). any idea what causes this?

**Comment by pmmmwh** [comment]
This is due to SockJS, used in `webpack-dev-server`.

If you are not using WDS, you should probably configure the socket integration as stated in the README.

If you're using WDS, this issue is likely happening because a proper WebSocket implementation was not detected by SockJS in the browser, and thus it is falling back to using an `iframe`-based Cross Origin solution - which will get blocked by `X-Frame-Options: deny` obviously.

You can work-around this by using the native `ws` integration provided by WDS, but it still won't work in browsers without socket implementations.

**Comment by pmmmwh** [comment]
I'll be closing this because this is unrelated to the plugin.

**Comment by glekner** [comment]
hey @pmmmwh 
switching `transportMode` to `ws` indeed fixes the issue.
could this break something else in the code? the app seems to run fine, browser support is also pretty decent if i'm not wrong?

**Comment by pmmmwh** [comment]
> could this break something else in the code?

No. If it does please redirect your issue to the `webpack-dev-server` repo.

> browser support is also pretty decent if i'm not wrong?

As shown in [caniuse](https://caniuse.com/#feat=websockets), you're covered 97.57% of the time.

**Comment by glekner** [comment]
nice, I do get a warning of still using SockJS even though I cant find any reference to the pattern `sockjs || sock-js` in the code?

`WebSocket connection to 'ws://localhost:9000/sockjs-node' failed: Error during WebSocket handshake: Unexpected response code: 200`

**Comment by pmmmwh** [comment]
> nice, I do get a warning of still using SockJS even though I cant find any reference to the pattern `sockjs || sock-js` in the code?
> 
> `WebSocket connection to 'ws://localhost:9000/sockjs-node' failed: Error during WebSocket handshake: Unexpected response code: 200`

If you use a custom socket path for WDS -  you will have to tell the plugin. `sockjs-node` is the default fallback path hard-coded in WDS and in the plugin for the WDS integration.

**Comment by glekner** [comment]
Thanks, hijacking this issue for another question
Is it possible to not use:?

> Note 1: If you use webpack.config.ts, please also install type-fest as a peer dependency.

I'm not getting any type errors without it.

**Comment by pmmmwh** [comment]
> I'm not getting any type errors without it.

In theory, this shouldn't be the case - you can take a look at the files within `types` and clearly we have dependency on `type-fest` for error overlay options at least - maybe if you don't use these options `tsc` is smart enough to not warn ...

**Comment by glekner** [comment]
>If you use a custom socket path for WDS - you will have to tell the plugin. sockjs-node is the default fallback path hard-coded in WDS and in the plugin for the WDS integration.
@pmmmwh 
I'm using `ws` instead of the default `sock-js` as you advised.
Do you know what path/port do I need to change in the plugin options?

**Comment by pmmmwh** [comment]
> Do you know what path/port do I need to change in the plugin options?

Please post your dev server config here 😊

**Comment by glekner** [comment]
I fixed it :)
Because were running a bridge proxy just needed to add the webpack port to the plugin config.
It didn't work on 0.4.0.beta6 ! I still got the error for some reason.
I downgraded to 0.3.3

```
          new ReactRefreshWebpackPlugin({
            overlay: {
              sockPort: WDS_PORT,
            },
          }),
```

**Comment by pmmmwh** [comment]
> I fixed it :)
> Because were running a bridge proxy just needed to add the webpack port to the plugin config.
> It didn't work on 0.4.0.beta6 ! I still got the error for some reason.

I will ... Erm ... Have to take a look at it then I guess 😂

**Comment by pmmmwh** [comment]
Error addressed in #133.

**Comment by glekner** [comment]
@pmmmwh is there a way to disable the error overlay? without sacrificing the new `sockPort` I just added to the `overlay` object?

**Comment by pmmmwh** [comment]
> @pmmmwh is there a way to disable the error overlay? without sacrificing the new `sockPort` I just added to the `overlay` object?

`sockPort` only affects the overlay, so if you disable it you don't need to include the flag.
