### ISSUE TITLE
The plugin is unable to detect transformed code from react-refresh

### ISSUE THREAD

**Issue by nthypes** [pmmmwh/react-refresh-webpack-plugin#11]
The plugin supports TypeScript (_.tsx files_)?

I'm getting the following error:

`✖ ｢wdm｣: Error: The plugin is unable to detect transformed code from react-refresh. Did you forget to include "react-refresh/babel" in your list of Babel plugins? Note: you can disable this check by setting "disableRefreshCheck: true".`

My **babel.config.js**:

```
module.exports = api => {
  // This caches the Babel config
  api.cache.using(() => process.env.NODE_ENV);
  return {
    presets: [
      "@babel/preset-env",
      "@babel/preset-react",
      "@babel/preset-typescript"
    ],
    // Applies the react-refresh Babel plugin on non-production modes only
    ...(!api.env("production") && { plugins: ["react-refresh/babel"] })
  };
};
```

My **webpack.config.js**:

```
const webpack = require("webpack");
const path = require("path");
const HtmlWebpackPlugin = require("html-webpack-plugin");
const ReactRefreshWebpackPlugin = require("@pmmmwh/react-refresh-webpack-plugin");

module.exports = {
  entry: "./src/index.tsx",
  output: {
    path: path.join(__dirname, "/dist"),
    filename: "main.min.js"
  },
  devServer: {
    hot: true
  },
  resolve: {
    extensions: [".ts", ".tsx", ".js"]
  },
  module: {
    rules: [
      {
        test: /\.(ts|tsx)$/,
        exclude: /node_modules/,
        use: [
          {
            loader: "babel-loader"
          }
        ]
      }
    ]
  },

  plugins: [
    new ReactRefreshWebpackPlugin(),
    new HtmlWebpackPlugin({
      template: "./src/index.html"
    })
  ]
};

```

**Comment by pmmmwh** [comment]
> The plugin supports TypeScript (_.tsx files_)?
> 
> I'm getting the following error:
> 
> `✖ ｢wdm｣: Error: The plugin is unable to detect transformed code from react-refresh. Did you forget to include "react-refresh/babel" in your list of Babel plugins? Note: you can disable this check by setting "disableRefreshCheck: true".`
> 
> My **babel.config.js**:
> 
> ```
> module.exports = api => {
>   // This caches the Babel config
>   api.cache.using(() => process.env.NODE_ENV);
>   return {
>     presets: [
>       "@babel/preset-env",
>       "@babel/preset-react",
>       "@babel/preset-typescript"
>     ],
>     // Applies the react-refresh Babel plugin on non-production modes only
>     ...(!api.env("production") && { plugins: ["react-refresh/babel"] })
>   };
> };
> ```
> 
> My **webpack.config.js**:
> 
> ```
> const webpack = require("webpack");
> const path = require("path");
> const HtmlWebpackPlugin = require("html-webpack-plugin");
> const ReactRefreshWebpackPlugin = require("@pmmmwh/react-refresh-webpack-plugin");
> 
> module.exports = {
>   entry: "./src/index.tsx",
>   output: {
>     path: path.join(__dirname, "/dist"),
>     filename: "main.min.js"
>   },
>   devServer: {
>     hot: true
>   },
>   resolve: {
>     extensions: [".ts", ".tsx", ".js"]
>   },
>   module: {
>     rules: [
>       {
>         test: /\.(ts|tsx)$/,
>         exclude: /node_modules/,
>         use: [
>           {
>             loader: "babel-loader"
>           }
>         ]
>       }
>     ]
>   },
> 
>   plugins: [
>     new ReactRefreshWebpackPlugin(),
>     new HtmlWebpackPlugin({
>       template: "./src/index.html"
>     })
>   ]
> };
> ```

I'm actually on this right now. It is related to how Webpack handles errors and how the plugin sniffs babel transforms. For the time being, you should be able to get away with `disableRefreshCheck: true`

**Comment by nthypes** [comment]
Ok. I will disable. 

One more thing: We need to apply `module.hot.accept()` in the main **index.tsx** or this is injected somehow on babel?

**Comment by allocenx** [comment]
I'm facing the same issue aswell...and i thought i was doing something wrong.

**Comment by pmmmwh** [comment]
> I'm facing the same issue aswell...and i thought i was doing something wrong. Tho, i do not use typescript.

It would be great if you can share your setup a bit more so that I can understand what causes you issues.

**Comment by pmmmwh** [comment]
Closing this in favor of #15 , because it is more accurately describing the problem.
