### ISSUE TITLE
Issues with typescript and export default as

### ISSUE THREAD

**Issue by jwaldrip** [pmmmwh/react-refresh-webpack-plugin#111]
I am having issues with exports when the plugin is enabled. No issue when the plugin is disabled.

```
TypeError
Cannot read property 'default' of undefined
Call Stack
 Object.get [as InputSubtext]
  libraries/katana/input/styled-text-input/index.ts:1:403
 Object.get [as InputSubtext]
  libraries/katana/input/index.ts:1:3405
 Object.registerExportsForReactRefresh
  node_modules/@pmmmwh/react-refresh-webpack-plugin/src/runtime/refreshUtils.js:190:38
 Object.eval
  libraries/katana/input/index.ts:3:25
 eval
  libraries/katana/input/index.ts:6:30
 Object.../../../libraries/katana/input/index.ts
  bundle.js:2098:1
 __webpack_require__
  bundle.js:40:31
 Object.eval
  libraries/katana/input/predictive-input.tsx:1:2196
 eval
  libraries/katana/input/predictive-input.tsx:6:30
 Object.../../../libraries/katana/input/predictive-input.tsx
  bundle.js:2153:1
```

**Comment by pmmmwh** [comment]
Is it possible to provide a reproducible example?

**Comment by zxc0328** [comment]
I also encounter with this error and the reason is I named the default export as `module`, like:

```
import module from "./src/foo"
```

and module is a global variable when hot module reload is enabled. So the user-defined `module` variable conflict with the global one.  I'm not sure this behavior is expected or not.

**Comment by pmmmwh** [comment]
> I also encounter with this error and the reason is I named the default export as `module`, like:
> 
> ```
> import module from "./src/foo"
> ```
> 
> and module is a global variable when hot module reload is enabled. So the user-defined `module` variable conflict with the global one. I'm not sure this behavior is expected or not.

This is unrelated to this issue. What do you mean my naming an import `module`

Can you open a new issue and provide the steps to reproduce please?

**Comment by pmmmwh** [comment]
Closing this - unable to reproduce and inactive.

Feel free to re-open if there is more to share about this.
