### ISSUE TITLE
Could you rename main to canary or other alternatives?

### ISSUE THREAD

**Issue by ghost** [pmmmwh/react-refresh-webpack-plugin#115]
The word main has a toxic history in asian cultures (you should know it too). 
Please read the article here - https://www.nakasendoway.com/the-japanese-family-system/

Vercel (nextjs/now) use canary with their projects. I think that might be more appropriate change here.

Would you please consider the historical impact and change to canary?

**Comment by zisop16** [comment]
good meme nobody cares

**Comment by pmmmwh** [comment]
> The word main has a toxic history in asian cultures (you should know it too).
> Please read the article here - [nakasendoway.com/the-japanese-family-system](https://www.nakasendoway.com/the-japanese-family-system/)

I don't see any discussion about toxic history or the word `main` in the article.

I also don't know why you think I should have knowledge about that.

> Would you please consider the historical impact and change to canary?

Well, if you can properly justify the decision with sources, I might consider.

But yea, posting an issue then deleting the account (`@blacklivesmatterplease`) - I'm not sure if you care about this either.
