### ISSUE TITLE
On alternatives to 'master'

### ISSUE THREAD

**Issue by jbreckmckye** [pmmmwh/react-refresh-webpack-plugin#117]
**I am not interested in re-opening the question of whether the word 'master' is exclusionary / problematic**. But I do think it would be valuable to discuss exactly what synonym we'd like.

### I'm not sure about 'main'

Whilst there seems to be a burgeoning movement to use 'main', as a default across projects, I think this is mistaken:

1. In a lot of teams, the bulk of development is not actually done on the primary branch
2. 'Main' implies that work should not actually be done on branches; that branches are a 'special case' rather than the default
3. There may be better metaphors.

On point 3, if we're using the metaphor of (real world) trees, then the obvious word is not 'main' but 'trunk'. Trees have trunks and branches come off them - and this is a common naming system in a lot of SCM systems. Good metaphors make things easy to learn and technology less alien to newcomers.

### I think 'main' implies branches are exceptions, not the rule

Specifically, I think 'main' tells newcomers that one doesn't branch by default, and it'd be a shame if people lost out on branches / PRs because they assumed that they were 'supposed' to put things in 'main' unless they had a compelling reason not to.

### This project vs other projects

Of course, what _this_ project does and what others do may vary, but I think the earliest adopters of a new convention have a great opportunity to shape its design. And if we're going to break tools that assume things are called 'master' anyway, why not make the new convention the best it can be?

**Comment by InfinitySamurai** [comment]
How about 'Release'

**Comment by Kungergely** [comment]
> I completely understand that master have two meanings:
> 
>     A man who has people working for him, especially servants or slaves; and
>     An original recording, film, or document from which copies can be made.
> 
> As aforementioned, the usage of master as a branch most likely originated from the first meaning

That last sentence is a lie. Plain and simple as that.

**Comment by wuperguy** [comment]
How about keep it as "master"?
This is getting absolutely absurd and out of hand.. do we really need to rename every last thing because it quote on quote has reference to slavery? No.
Master does not have ANYTHING to do with slavery unless you're pathetic enough to complain and make it that way. Just leave it be, you're causing way more trouble than its worth.. people will find anything to complain about nowadays. I do not support this change whatsoever and I think its the silliest thing I have EVER seen. 
Whitelist and blacklist. We can't even reference colors now without them being tied to race? Ok. 
The media blew this situation way out of proportion and now everyone is being a puppeteer and following their nonsense drama. I'm so tired of it.

**Comment by MatStace** [comment]
> This comment is 100% getting removed, but thats fine with me. I just want you to know that I am 100% against this, and I am entitled to this decision just like those who think this stupid idea should be implemented.

You're also 100% entitled to not use any repo which makes default branch naming decisions that you disagree with, but this isn't an airport, you don't need to announce your departure

**Comment by jbreckmckye** [comment]
Given that no-one actually wants to discuss potential branch names (apart from @InfinitySamurai) I'm just going to close this

**Comment by pmmmwh** [comment]
@jbreckmckye

While you've closed the issue I think I owe you a proper reply, so here we go.

> 1. In a lot of teams, the bulk of development is not actually done on the primary branch

This depends on how you see it - most commits will be merged to the primary branch (especially when squashing), so in some sense we can say the primary branch is the "main" place where stuff happens. (I also occasionally push to master 😅)

> 2. 'Main' implies that work should not actually be done on branches; that branches are a 'special case' rather than the default

I don't think I completely agree. "Main" means "most important" - and I think it indicates that everything should be based off it. For me, it doesn't sound like branches are discouraged (however, for OSS libraries like this one, forks are much more common). (Also, branches can be considered as a special case given the expectation is everything will land in the default branch)

> 3. There may be better metaphors.

I don't disagree - I know other SCM systems uses "default" and "trunk".

However, I think "trunk" is too good of a metaphor to me that it sounds obscure, which for me personally, makes my thoughts deviate from thinking it's a "default"/"primary" copy of the source code.

I think using "master" have a few advantages:
- Shorter, and maintains muscle memory for typing "m"
- Direct synonym to "'master' copy", "primary", "'principle' copy" and "head"
- Well ... [Suggested by Petr Baudis](https://twitter.com/xpasky/status/1271477451756056577) (LOL?)

All in all, thanks for bringing this up - but for my personal preference, what others are adopting and also to prevent another incident of people complaining about a breaking change when we change the branch name again, I think I'll keep this for now.

If the industry somehow proves me wrong and another term is adopted widely I'll revisit the decision and hopefully not irritate too many people in the process of that.
