### ISSUE TITLE
integration with webpack-devserver

### ISSUE THREAD

**Issue by dagda1** [pmmmwh/react-refresh-webpack-plugin#128]
I can't find anywhere in the docs that states what `webpack-devserver` config might interfere with this plugin.

Would it be possible to find out if these values conflict?

```javascript
{
    disableHostCheck: true,
    clientLogLevel: 'none',
    contentBase: paths.appPublic,
    compress: true,
    liveReload: false,
    headers: {
      'Access-Control-Allow-Origin': '*',
    },
    hot: true,
    transportMode: 'ws',
    injectClient: false,
    sockHost,
    sockPath,
    sockPort,
    quiet: true,
    host,
    https: protocol === 'https',
    watchContentBase: true,
    noInfo: true,
    overlay: false,
    historyApiFallback: {
      disableDotRule: true,
    },
};

```

**Comment by pmmmwh** [comment]
Nothing will conflict with this plugin.

However, if you're using `sockHost`, `sockPath` and `sockPort`, you should also set the respective options for the plugin. This is currently a WDS-only quirk because we don't have a good way to detect these values (CLI/Config/Inline).

**Comment by dagda1** [comment]
@pmmmwh thank you for the answer and the plugin!

Do you mean set the `sockPath`, `sockHost` and `sockPort` on the overlay:

```javascript
        new ReactRefreshWebpackPlugin({
          overlay: {
            sockPort: Number(sockPort),
            sockPath,
            sockHost,
            sockIntegration: 'wds',
          },
        }),
```
I seem to get a better experience with this in `webpack-devserver`

```javscript
    hot: false,
    hotOnly: true,
```

**Comment by pmmmwh** [comment]
> Do you mean set the `sockPath`, `sockHost` and `sockPort` on the overlay:

Yes.

> I seem to get a better experience with this in `webpack-devserver`
> 
> ```
>     hot: false,
>     hotOnly: true,
> ```

It depends on the structure of your project. `hotOnly` only make any bailouts to not immediately trigger a full refresh.

If you're having issues, or are experiencing a lot of full refreshes, I'll need more context about your project before I can give out any specific suggestions.

**Comment by dagda1** [comment]
Hi,

THere do seem to be a hell of a lot of updates coming from the css, my css config is below.

Could you give it a quick glance and see if anything obvious stands out?  I have a function to create this and I did not realise how big it was until I outputted it to the console

```javascript
 {
     test: /\.css$/,
     use: [
       '/Users/developer15/projects/scot.disclosure.pvg-online/node_modules/css-hot-loader/index.js',
       {
         loader: '/Users/developer15/projects/scot.disclosure.pvg-online/node_modules/mini-css-extract-plugin/dist/loader.js',
         options: { hmr: true }
       },
       {
         loader: 'css-loader',
         options: { importLoaders: 2, sourceMap: true, modules: undefined }
       },
       {
         loader: 'postcss-loader',
         options: { ident: 'postcss', plugins: [Function: plugins] }
       }
     ]
   },
   {
     test: /\.(scss|sass)$/,
     exclude: /\.module\.(scss|sass)$/,
     use: [
       '/Users/developer15/projects/scot.disclosure.pvg-online/node_modules/css-hot-loader/index.js',
       {
         loader: '/Users/developer15/projects/scot.disclosure.pvg-online/node_modules/mini-css-extract-plugin/dist/loader.js',
         options: { hmr: true }
       },
       {
         loader: 'css-loader',
         options: { importLoaders: 2, sourceMap: true, modules: undefined }
       },
       {
         loader: 'postcss-loader',
         options: { ident: 'postcss', plugins: [Function: plugins] }
       },
       { loader: 'sass-loader' }
     ]
   },
   {
     test: /\.module\.(scss|sass)$/,
     use: [
       '/Users/developer15/projects/scot.disclosure.pvg-online/node_modules/css-hot-loader/index.js',
       {
         loader: '/Users/developer15/projects/scot.disclosure.pvg-online/node_modules/mini-css-extract-plugin/dist/loader.js',
         options: { hmr: true }
       },
       {
         loader: 'css-loader',
         options: {
           importLoaders: 2,
           sourceMap: true,
           modules: { getLocalIdent: [Function] }
         }
       },
       {
         loader: 'postcss-loader',
         options: { ident: 'postcss', plugins: [Function: plugins] }
       },
       { loader: 'sass-loader' }
     ]
   }
 ]
```

**Comment by pmmmwh** [comment]
> There do seem to be a hell of a lot of updates coming from the css, my css config is below.

This plugin does not deal with CSS - it is other plugins/loaders responsibility to ensure they hot update properly.

However, I would suggest removing `css-hot-loader` and use the built-in HMR functionality from `mini-css-extract-plugin` (since 0.6.0) instead, because it is much better maintained.

**Comment by dagda1** [comment]
thank you for taking the time to answer this
