### ISSUE TITLE
Failed to work when react is external and loaded via standalone script

### ISSUE THREAD

**Issue by otakustay** [pmmmwh/react-refresh-webpack-plugin#13]
With HTML template like:

```html
<script src="https://cdn.jsdelivr.net/npm/react@16.12.0/umd/react.production.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/react-dom@16.12.0/umd/react-dom.production.min.js"></script>
```

And a webpack config including:

```js
{
    externals: {
        react: 'React',
        'react-dom': 'ReactDOM',
    }
}
```

This plugin fails to work.

I'd like to dive into it a little, but with little knowledge about webpack I'm not sure I can find any valuable ideas.

**Comment by otakustay** [comment]
After looking into both this plugin and `react-refresh/runtime`, it comes the essential part of this issue is that `react-refresh/runtime`'s setup should be run before `react-dom` is initialized.

I tried to extract `react-refresh/runtime` and `ReactRefreshEntry.js` into separated `.js` files and load them from `<script>` element **BEFORE** `react-dom`, hot reload works as expected.

In this case, problem becomes a little complex, we should first make `react-refresh/runtime` loadable from CDN, and then the refresh entry loadable from CDN.

**Comment by pmmmwh** [comment]
> After looking into both this plugin and `react-refresh/runtime`, it comes the essential part of this issue is that `react-refresh/runtime`'s setup should be run before `react-dom` is initialized.
> 
> I tried to extract `react-refresh/runtime` and `ReactRefreshEntry.js` into separated `.js` files and load them from `<script>` element **BEFORE** `react-dom`, hot reload works as expected.
> 
> In this case, problem becomes a little complex, we should first make `react-refresh/runtime` loadable from CDN, and then the refresh entry loadable from CDN.

Yes, the runtime setup have to be done before React's first run. This is unfortunately a limitation from the runtime. I will subscribe to facebook/react#17552, but before that is resolved not a lot could be done here.

**Comment by gaearon** [comment]
Can you check if https://github.com/facebook/react/pull/17633 fixes this?

**Comment by gaearon** [comment]
I verified that https://github.com/facebook/react/pull/17633 fixes it, although it will only work with *development* versions of React. Your snippet uses production versions so you'll need to somehow handle that.

**Comment by gaearon** [comment]
Fixed in `react-refresh@0.7.1`.

**Comment by pmmmwh** [comment]
@otakustay can you check to see if the plugin works now with `react-refresh@0.7.1`?

**Comment by gaearon** [comment]
FWIW I've verified this with the plugin.

**Comment by pmmmwh** [comment]
> FWIW I've verified this with the plugin.

OK - closing this for now.

**Comment by otakustay** [comment]
@gaearon I can confirm `react-refresh@0.7.1` works, but along with this plugin's `0.1.2` version part of my app fails to render, some network requests triggered inside `useEffect` are not executed.

**Comment by pmmmwh** [comment]
> @gaearon I can confirm `react-refresh@0.7.1` works, but along with this plugin's `0.1.2` version part of my app fails to render, some network requests triggered inside `useEffect` are not executed.

Is it possible to provide a Repo/CodeSandbox or something that can reproduce your issue?

**Comment by otakustay** [comment]
@pmmmwh I'v checked this is caused by another modification of my build tools, this plugin did everything well

**Comment by pmmmwh** [comment]
> @pmmmwh I'v checked this is caused by another modification of my build tools, this plugin did everything well

Good to hear that!

**Comment by qiaoqiaowang** [comment]
> > FWIW I've verified this with the plugin.
> 
> OK - closing this for now.

react-refresh 0.9.0
react 16.9.0
react-dom 16.9.0
externals still not work. I checked this in example/webpack-dev-server,  add
<script type="text/javascript" src="//unpkg.com/react@16.9.0/umd/react.production.min.js"></script>
    <script type="text/javascript" src="//unpkg.com/react-dom@16.9.0/umd/react-dom.production.min.js"></script>
    in index.html <head>, and add externals in webpack.config.js.

**Comment by pmmmwh** [comment]
> > > FWIW I've verified this with the plugin.
> > 
> > 
> > OK - closing this for now.
> 
> react-refresh 0.9.0
> react 16.9.0
> react-dom 16.9.0
> @pmmmwh
> externals still not work. I checked this in example/webpack-dev-server, add
> 
> ```
> <script type="text/javascript" src="//unpkg.com/react@16.9.0/umd/react.production.min.js"></script>
> <script type="text/javascript" src="//unpkg.com/react-dom@16.9.0/umd/react-dom.production.min.js"></script>
> in index.html <head>, and add externals in webpack.config.js.
> ```

The **PRODUCTION** build will not work.
