### ISSUE TITLE
Configuration issue with react-refresh/babel "ReferenceError: $RefreshReg$ is not defined"

### ISSUE THREAD

**Issue by Romcol** [pmmmwh/react-refresh-webpack-plugin#131]
Hi,

The plugin works perfectly fine when I use `webpack-dev-server`, thank you for that ! But when I compile my react program not using the dev server, `webpack --mode development --config webpack.config.js` I get an error.

I've perused some related issues but none seem to match what I'm looking after.

When I include `ReactRefreshPlugin` only with hot mode, such as here :
```
const devMode = argv.mode !== 'production';
...
plugins: [
devMode && argv.hot && new ReactRefreshPlugin(),
```

I get this error in the browser :
```
ReferenceError: $RefreshReg$ is not defined
    at eval (createFormattedComponent.js:101)
```

When I include `ReactRefreshPlugin` without checking for the hot argument (as suggested in the doc) :

```
const devMode = argv.mode !== 'production';
...
plugins: [
devMode && new ReactRefreshPlugin(),
```

I get this :

`Error: Hot Module Replacement (HMR) is not enabled! React-refresh requires HMR to function properly.`

For it to work, I have to remove `react-refresh/babel` from `babel.config.js` file manually while excluding `ReactRefreshPlugin`.

Also, there is not way I can check for the "hot mode" in `babel.config.js` so as to remove the plugin.

It would be convenient not to have such errors.

Anyways, thank you for the plugin :rocket:

**Comment by pmmmwh** [comment]
This is unfortunately a constraint to having the babel config outside of the webpack configuration.

> Also, there is not way I can check for the "hot mode" in babel.config.js so as to remove the plugin.

This could be worked around - if you already can check for hot mode.

You could set an environment variable within the webpack config and consume its value in the babel config.

`webpack.config.js`

```js
process.env.HOT = argv.hot;
```

`babel.config.js`

```js
module.exports = (api) => {
  // This caches the Babel config w.r.t. NODE_ENV and HOT
  api.cache.using(() => `${process.env.NODE_ENV}-${process.env.HOT}`);
  return {
    presets: ['@babel/preset-env', '@babel/preset-react'],
    // Applies the react-refresh Babel plugin on non-production modes only
    ...(!api.env('production') && process.env.HOT && { plugins: ['react-refresh/babel'] }),
  };
};
```
