### ISSUE TITLE
Two Reacts with fast refresh, one overlay won't dismiss

### ISSUE THREAD

**Issue by colinclerk** [pmmmwh/react-refresh-webpack-plugin#139]
I have two React's with fast refresh, one coming from webpack/react-refresh-webpack-plugin, and the other coming from next.js.  (I think that's purely an implementation detail, though, this bug looks like it would occur with two webpacks as well.)

When I create a runtime error in either project, both error overlays throw.

When I fix my error, the codebase with the error removes their respective overlay, but the other overlay remains.

I think I see what's going on.  Both are catching the runtime error with `window.addEventListener('error')`, but only try to remove their overlay when a reload comes from their codebase.

Is there any way to only catch errors associated with the webpack build?  One idea is to filter errors on the "filename" in the error event, and only throw the overlay if the error is coming from a file in the webpack output:
https://developer.mozilla.org/en-US/docs/Web/API/ErrorEvent

**Comment by pmmmwh** [comment]
I'm not sure how you're using two Reacts, while bundling them together? This plugin and Next.js is somewhat redundant (from Next.js 9.4+) because they rock their own fast refresh runtime.

Can you provide a reproducible example for me to properly understand the issue?

**Comment by colinclerk** [comment]
I'm not bundling them together - I have two Reacts coming from two different <script> tags on my page, and each fast refresh is binding to the global `window.addEventListener('error')` to catch runtime errors, so they're catching each others errors.

The "why" of this is - I'm building an embeddable widget.  One react is for the widget (webpack), and the other is for the application embedding it (Next.js).

---

For a simple reproduction, I think we can ignore that my setup has two reacts.  Instead, open your index.html that loads webpack's javascript output.  Somewhere on the page, add:

```
    <script type="text/javascript">
      // Use setTimeout to give react/webpack time to initialize
      setTimeout(function() {
        throw new Error("React refresh will catch this but maybe shouldn't.");
      }, 1000);
    </script>
```

Refresh will catch the throw, but I don't believe it should because the error is not part of the webpack bundle.  It is indeed a runtime error, but it doesn't have to do with the javascript files running through the plugin.

There's a little bit of a conceptual argument here - is it right to scope down the errors that the plugin catches, or should it catch all runtime errors?

**Comment by pmmmwh** [comment]
> Refresh will catch the throw, but I don't believe it should because the error is not part of the webpack bundle. It is indeed a runtime error, but it doesn't have to do with the javascript files running through the plugin.

I understand the argument and would agree that this is an issue. I think this would be a bigger issue with Webpack 5 and module federation - since it basically is your example amplified.

> There's a little bit of a conceptual argument here - is it right to scope down the errors that the plugin catches, or should it catch all runtime errors?

The issue is, we basically don't have much of an alternative solution here. Filtering for `filename` from error events is unreliable: For example, what if an error originate from `eval` or maybe the output filename is non-deterministic (we don't sniff output filenames and they can be composed of hashes/content hashes)? Maybe we can add functionality to attach event handlers scoped to a single root element, and users will have to provide a unique element selector string (which seems doable esp. when we're already rendering with ReactDOM) - this have to be entirely optional though, as for most React SPAs mounting to `window`/`document` is perfectly fine and arguably "correct".

For reference, other known React error overlays also exhibit this behaviour:

- [Next.js' new error overlay](https://github.com/vercel/next.js/blob/5460abf2d43888fa5444f57ae47ed172fe92c79c/packages/react-dev-overlay/src/client.ts#L53-L54)
- [CRA's react-error-overlay](https://github.com/facebook/create-react-app/blob/2da5517689b7510ff8d8b0148ce372782cb285d7/packages/react-error-overlay/src/listenToRuntimeErrors.js#L66-L67)

**Comment by colinclerk** [comment]
Are you thinking something like `document.getElementByID("#react-root").addEventListener("error")`?  My intuition is that adding a listener to the node wouldn't catch anything, since the script runs outside of the node, but I'm not 100% sure on that.

I jumped to filename because (I think) the top line of my error is always attributed to the script webpack produces.  I just tried with an `eval("throw new Error('test');");` and it seems to still get the right filename:

Example: Eval added with fast refresh (does the plugin generate the script tag for this hot-update.js file, or is it totally out of its vision?):

<img width="895" alt="Screen Shot 2020-07-12 at 11 57 01 PM" src="https://user-images.githubusercontent.com/51144033/87279219-ad9ddb00-c49b-11ea-92a6-be3088ccf8be.png">

Example: Eval after the hard refresh:
<img width="898" alt="Screen Shot 2020-07-12 at 11 56 22 PM" src="https://user-images.githubusercontent.com/51144033/87279248-c4dcc880-c49b-11ea-8845-01608b97068b.png">

Hmm yea, looking at my webpack file it seems the plugin doesn't have access to my output definition.  Maybe we can get creative with document.currentScript:
https://developer.mozilla.org/en-US/docs/Web/API/Document/currentScript

---

PS: **thank you** so much for this plugin.  HMR was a total nightmare for this project, I constantly had to hard refresh.  Now I only have to hard refresh when my code throws, maybe only 5% of what I used to.

**Comment by pmmmwh** [comment]
> (does the plugin generate the script tag for this hot-update.js file, or is it totally out of its vision?)

Webpack does that, we have no control or information about it.

What methods do you have in mind with `document.currentScript`? Filter errors' source with it?

**Comment by colinclerk** [comment]
Yea, I'm imagining the babel plugin can inject something that uses `document.currentScript` to build up a reliable list of which script tags are running babel-loader output, then errors can be filtered against that list of script tags.

**Comment by pmmmwh** [comment]
Maybe something along the lines of sniffing webpack's output stats - let me discuss with other "overlay" maintainers about this use case 😄
