### ISSUE TITLE
Issues with React DevTools

### ISSUE THREAD

**Issue by luisgrases** [pmmmwh/react-refresh-webpack-plugin#142]
It seems this plugin causes issues with Chrome React devtools. The inspect tool seems to not be working at all.
![image](https://user-images.githubusercontent.com/6208922/87259799-1fa9fc00-c46b-11ea-8346-66e1279b57f1.png)

I am using react: 16.13.1 and refresh-webpack-plugin: 0.3.3.

**Comment by pmmmwh** [comment]
I'm not seeing this issue. Can you try the latest beta (i.e. `0.4.0-beta.8`)?

If it still doesn't work for you, can you provide a reproducible example for me to investigate?

**Comment by luisgrases** [comment]
I am not being able to reproduce it on a small repo. Will keep trying. Another thing I have noticed is that react-dev-tools is giving me a: No element found with id {node_id} anytime I hover over a component using the inspector tool.

**Comment by pmmmwh** [comment]
> Removing the plugin fixes the issue.

Do you mean removing the Webpack plugin, the Babel plugin or both? Can you try including the Webpack plugin but removing the Babel plugin? This will break FR, but is a good indicator on which part of the integration is messed up (DevTools global hook or runtime from the plugin)

**Comment by pmmmwh** [comment]
> EDIT: It seems the devtools is not finding any childs of the `<Suspense>` component. Will continue digging

It seems that it was a bug in DevTools instead of the plugin (and it was fixed few days ago). Can you verify that stuff works for you now?

**Comment by pmmmwh** [comment]
Cannot be reproduced on latest builds as a fix had landed (on React's side).
