### ISSUE TITLE
should I be seeing the regular error overlay iframe when using react-refresh

### ISSUE THREAD

**Issue by dagda1** [pmmmwh/react-refresh-webpack-plugin#144]
Should I be seeing the regular react error iframe when using this plugin?

After I have configured the plugin, errors show the iframe and there is no refresh.

If you could please let me know if the iframe should be there as my first thing to cross off.

![aaaaa](https://user-images.githubusercontent.com/118328/87656632-a43d9880-c751-11ea-9fca-97b6f7c56466.png)

**Comment by pmmmwh** [comment]
I suppose you are using `create-react-app`? If yes - their support have landed but have not been released. You will have to reference our CRA example in configuring your app.

**Comment by dagda1** [comment]
im not using create-react-app.  it is custom webpack

**Comment by pmmmwh** [comment]
> im not using create-react-app. it is custom webpack

Then you probably are using a custom overlay. The iframe shown in the screenshot is not the default one bundled by the plugin.

**Comment by dagda1** [comment]
I was using `webpackHotDevClient` from react-dev-tools.  Removing this removes the overlay
