### ISSUE TITLE
Error on HMR reload

### ISSUE THREAD

**Issue by sarunast** [pmmmwh/react-refresh-webpack-plugin#177]
I am trying to use fast refresh with WPS. With some components it works fine however with others, I get this error. 

Plugin version `0.4.1`
WPS: `1.0.1`

```
main.js:558 Uncaught (in promise) Error: Aborted because ./src/client/views/home/HomeView.js is not accepted
Update propagation: ./src/client/views/home/HomeView.js -> ./src/client/views/routes.js -> ./src/client/app.js -> ./src/client/main.js -> 0
    at hotApplyInternal (main.js:558)
    at hotApply (main.js:412)
    at replace (hmr.js?797c:60)
hotApplyInternal @ main.js:558
hotApply @ main.js:412
replace @ hmr.js?797c:60
async function (async)
replace @ hmr.js?797c:47
eval @ client.js?a662:70
```
![image](https://user-images.githubusercontent.com/825836/89704773-3f8feb00-d957-11ea-9a6f-e39a666c904c.png)

Any pointers where could the issue lie?

**Comment by gaearon** [comment]
This would need a minimal reproducing example. Could be a webpack big.

**Comment by pmmmwh** [comment]
Other than a Webpack bug, this might be due to no available boundaries within the whole chain (i.e. no files in that chain contains only React components a-la `PascalCase`).

**Comment by sarunast** [comment]
> (i.e. no files in that chain contains only React components a-la `PascalCase`)

@pmmmwh do you know where could I read more about this issue to understand it better?

**Comment by pmmmwh** [comment]
> @pmmmwh do you know where could I read more about this issue to understand it better?

I don't have a definitive source for you, but React Refresh relies on exports' names to detect whether it is something we can accept (so does other dev tooling such as the hooks eslint plugin). So if a path of update propagation does not include anything we can accept, we unfortunately have to bail out.

> Also. Do you have any idea why it doesn't reload the whole page instead if it fails to update? Because after the before mentioned error the page stops reloading.

It seems like Webpack's hot reloading crashed. I can help take a look at the actual config if you can provide it (with versions of webpack and react/react-dom used).

**Comment by sarunast** [comment]
I will close this issue for now. If I will manage to recreate a public example of the issue I will reopen the issue. Thanks for the help.

**Comment by desmap** [comment]
fwiw, I had something similar with webpack `5.0.0-rc.0`; it worked without any errors with webpack `4.43`.

The browser's log with `5.0.0-rc.0`:

```
react_devtools_backend.js:2273 [HMR] Cannot apply update. Need to do a full reload!
overrideMethod @ react_devtools_backend.js:2273
module.exports @ log.js:26
eval @ dev-server.js:39
Promise.catch (async)
check @ dev-server.js:36
eval @ dev-server.js:55
emit @ events.js:153
reloadApp @ reloadApp.js:23
ok @ index.js:120
eval @ socket.js:48
sock.onmessage @ SockJSClient.js:67
EventTarget.dispatchEvent @ sockjs.js:170
eval @ sockjs.js:888
SockJS._transportMessage @ sockjs.js:886
EventEmitter.emit @ sockjs.js:86
WebSocketTransport.ws.onmessage @ sockjs.js:2962

react_devtools_backend.js:2273 [HMR] Error: Aborted because ./index.tsx is not accepted
Update propagation: ./index.tsx
```

**Comment by pmmmwh** [comment]
> fwiw, I had something similar with webpack `5.0.0-rc.0`; it worked without any errors with webpack `4.43`.

I think it is quite contextual? It says that `./index.tsx` is not accepted, but it is already at root so when we propagate it means a bail out (i.e. full refresh in browsers).

**Comment by desmap** [comment]
> contextual

You mean "meaningful"?

> It says that ./index.tsx is not accepted, but it is already at root so when we propagate it means a bail out (i.e. full refresh in browsers).

Would you mind to elaborate?

Why does the `tsx` file end up being in the browser at all? webpack-dev-server only accesses the dist folder with `.js` files. I'm a bit confused...

**Comment by pmmmwh** [comment]
(Sorry for missing this)

> You mean "meaningful" or "clear" (...what the problem is)?

Yes.

> Why does the tsx file end up being in the browser at all? webpack-dev-server should only access the dist folder with .js files. I'm a bit confused...

How `webpack-dev-server` and source error works is that they compile files on the fly and store them in memory - so `index.tsx` is not actually being served to the browser, it's just that the error originates from code within that file.

> So that means that at some point it's expected that your HMR bails out if no valid React component is found, right?! So everything is ok and this "error" you display is more kind of an information?!

Yes. Let's say your component tree is like this: `Component A -> index.ts (ReactDOM.render)`

If Component A is changed and we can update it, fine we won't propagate the update (only Component A updates). But if the update from Component A defies what we require for a safe update, we would have to go to its parent. However, it's parent is also unsafe to update in place - so eventually we bubbled to "root" which means to the actual entry point of the JS - so the only way we can guarantee consistency is to bail out (in browsers this equals a full refresh).

That is also not something we print - it is what `webpack-dev-server` prints when it hits a bail out case.

> - If I have an index.tsx which imports an App.tsx function compnent and renders it with ReactDOM => no refresh on change of App.tsx
> - If I have an index.tsx which includes the App function component inline => refresh but this error above
> - If I have index.tsx which has a bit of JSX like <div>...</div> and imports App.tsx and puts it between the divs like <div><App/ ></div> or right the the <App /> in ReactDOM.render(<App />, ... => all good on change of App.tsx but the error of above when changing index.tsx

Refering to the case I've described above - the best way to avoid unnecessary bail outs when you edit code paths that is very close to root (i.e. ReactDOM.render) is to not have any JSX at all in the file you do ReactDOM.render.

This is because we only construct boundaries with exports, and the file containing ReactDOM.render would most likely not have any exports, thus will never have a boundary.

**Comment by baylac** [comment]
in case you haven't tried, restarting the computer did it for me

**Comment by jorgutdev** [comment]
I was able to solve the issue wrapping the app into a component

> const container = document.getElementById('root')
const root = createRoot(container)
root.render(\<App />)

Then add the browser router 

> export const App = () => (
  <React.Suspense fallback="Loading...">
    \<AuthProvider>
      \<RouterProvider router={router} />
    \</AuthProvider>
  </React.Suspense>
)

**Comment by julpat** [comment]
In my case, it was caused by additional export next to component export:

```
// removing export solved the issue
export const SOME_CONST = 'Value';

export default function SomeComponent({}) { ... }
```

**Comment by alvaro-escalante** [comment]
@ju

> In my case, it was caused by additional export next to component export:
> 
> ```
> // removing export solved the issue
> export const SOME_CONST = 'Value';
> 
> export default function SomeComponent({}) { ... }
> ```

Thanks, I was going crazy with this and it was just that the moment there was a single export it worked!

**Comment by nyngwang** [comment]
@alvaro-escalante I, fortunately, succeeded on the first try since I didn't have any extra export. Now I'm curious why having more than one export will force it to full-reload.

**Comment by JeonChangMin15** [comment]
> @julpat
> 
> > In my case, it was caused by additional export next to component export:
> > ```
> > // removing export solved the issue
> > export const SOME_CONST = 'Value';
> > 
> > export default function SomeComponent({}) { ... }
> > ```
> 
> Thanks, I was going crazy with this and it was just that the moment there was a single export it worked!

You are my jesus. I love you

**Comment by JeonChangMin15** [comment]
> In my case, it was caused by additional export next to component export:
> 
> ```
> // removing export solved the issue
> export const SOME_CONST = 'Value';
> 
> export default function SomeComponent({}) { ... }
> ```

You are my jesus. I love you so much!

**Comment by symmetriq** [comment]
> In my case, it was caused by additional export next to component export:
> 
> ```
> // removing export solved the issue
> export const SOME_CONST = 'Value';
> 
> export default function SomeComponent({}) { ... }
> ```

Thank you! This fixed the issue for me. I moved the other export to a separate file.
