### ISSUE TITLE
Error: Cannot find module '@pmmmwh/react-refresh-webpack-plugin'

### ISSUE THREAD

**Issue by jsphkm** [pmmmwh/react-refresh-webpack-plugin#181]
After transition to `react-refresh-webpack-plugin` from `react-hot-loader`, Netlify is failing to build:

```
6:27:36 PM: ┌───────────────────────────────────┐
6:27:36 PM: │ 1. Build command from Netlify app │
6:27:36 PM: └───────────────────────────────────┘
6:27:36 PM: ​
6:27:36 PM: $ set NODE_ENV=production && webpack --mode production
6:27:37 PM: /opt/build/repo/node_modules/webpack-cli/bin/cli.js:93
6:27:37 PM: 				throw err;
6:27:37 PM: 				^
6:27:37 PM: Error: Cannot find module '@pmmmwh/react-refresh-webpack-plugin'
6:27:37 PM:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
6:27:37 PM:     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
6:27:37 PM:     at Module.require (internal/modules/cjs/loader.js:692:17)
6:27:37 PM:     at require (/opt/build/repo/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
6:27:37 PM:     at Object.<anonymous> (/opt/build/repo/webpack.config.js:7:35)
6:27:37 PM:     at Module._compile (/opt/build/repo/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
6:27:37 PM:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
6:27:37 PM:     at Module.load (internal/modules/cjs/loader.js:653:32)
6:27:37 PM:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
6:27:37 PM:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
6:27:37 PM:     at Module.require (internal/modules/cjs/loader.js:692:17)
6:27:37 PM:     at require (/opt/build/repo/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
6:27:37 PM:     at WEBPACK_OPTIONS (/opt/build/repo/node_modules/webpack-cli/bin/utils/convert-argv.js:114:13)
6:27:37 PM:     at requireConfig (/opt/build/repo/node_modules/webpack-cli/bin/utils/convert-argv.js:116:6)
6:27:37 PM:     at /opt/build/repo/node_modules/webpack-cli/bin/utils/convert-argv.js:123:17
6:27:37 PM:     at Array.forEach (<anonymous>)
6:27:37 PM:     at module.exports (/opt/build/repo/node_modules/webpack-cli/bin/utils/convert-argv.js:121:15)
6:27:37 PM:     at yargs.parse (/opt/build/repo/node_modules/webpack-cli/bin/cli.js:71:45)
6:27:37 PM:     at Object.parse (/opt/build/repo/node_modules/webpack-cli/node_modules/yargs/yargs.js:567:18)
6:27:37 PM:     at /opt/build/repo/node_modules/webpack-cli/bin/cli.js:49:8
6:27:37 PM:     at Object.<anonymous> (/opt/build/repo/node_modules/webpack-cli/bin/cli.js:366:3)
6:27:37 PM:     at Module._compile (internal/modules/cjs/loader.js:778:30)
6:27:37 PM:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
6:27:37 PM:     at Module.load (internal/modules/cjs/loader.js:653:32)
6:27:37 PM:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
6:27:37 PM:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
6:27:37 PM:     at Module.require (internal/modules/cjs/loader.js:692:17)
6:27:37 PM:     at require (internal/modules/cjs/helpers.js:25:18)
6:27:37 PM:     at Object.<anonymous> (/opt/build/repo/node_modules/webpack/bin/webpack.js:156:2)
6:27:37 PM:     at Module._compile (internal/modules/cjs/loader.js:778:30)
6:27:37 PM: ​
6:27:37 PM: ┌─────────────────────────────┐
6:27:37 PM: │   "build.command" failed    │
6:27:37 PM: └─────────────────────────────┘
etc...
```

Is this an issue with this plugin?

**Comment by pmmmwh** [comment]
This seems like during build this plugin is not installed?
Are you only installing `dependencies`, have this plugin in `devDependencies` or something along the lines of that?

**Comment by jsphkm** [comment]
It's set as a devDependency.  It building on Netlify straight from Github.

**Comment by jsphkm** [comment]
Actually, you brought up an interesting point, why is netlify trying to install this plugin during the build? that flew over my head.

With that said, I've added environment variables, NODE_ENV = production
And ran this in webpack:
```
const isDevelopment = process.env.NODE_ENV === 'development';
```

And followed the instructions, e.g.:
```
plugins: [
    ...
    isDevelopment && new ReactRefreshWebpackPlugin(),
  ].filter(Boolean),
```

**Comment by pmmmwh** [comment]
> Actually, you brought up an interesting point, why is netlify trying to install this plugin during the build? that flew over my head.
> 
> With that said, environment variables was added, NODE_ENV = production
> And set this in webpack:
> ```
> const isDevelopment = process.env.NODE_ENV === 'development';
> ```
> 
> And followed the instructions, e.g.:
> ```
> plugins: [
>     ...
>     isDevelopment && new ReactRefreshWebpackPlugin(),
>   ].filter(Boolean),
> ```

Well, you still have that global `require` statement, so at the point in time where the config is being executed everything in there literally have to be installed.

**Comment by jsphkm** [comment]
Gotcha, I was thinking that just now.  So I need to conditionally import or split webpack with webpack.prod.js & webpack.dev.js. Something like that right?

**Comment by pmmmwh** [comment]
> Gotcha, I was thinking that just now.  So I need to conditionally import or split webpack with webpack.prod.js & webpack.dev.js. Something like that right?

Short answer: no.

I think it really depends on the setup.

If you're building something with a server, sure. Go ahead and split your config files. But if you're building something client side rendered that will output to static assets (or something along the lines of that), you probably don't care - yes hand picking dependencies to be installed for CI builds will make them faster but then you need more tooling to keep the two files consistent (assuming that the difference between dev and prod is small). Conditional imports would work to solve one-off problems like this. 

I would figure out why dependencies are not installing properly before going full-blown multi-config.

**Comment by jsphkm** [comment]
It was just this one line so I decided to go with the conditional import
```
const ReactRefreshWebpackPlugin = isDevelopment ? require('@pmmmwh/react-refresh-webpack-plugin') : null;
```

And I needed to install `trim-loader` for `babel-loader` for some reason, and it looks like it's working.

This project is a bit simple so I can hold off from splitting config files.

Thanks! I appreciate the help.
