### ISSUE TITLE
First reload full refresh because of scss

### ISSUE THREAD

**Issue by jansedlon** [pmmmwh/react-refresh-webpack-plugin#182]
Hello, I've got small issue with reloading full page on first recompile. The warning message is
![image](https://user-images.githubusercontent.com/13948180/90103417-befc3080-dd42-11ea-98f1-0ad808c4a2e7.png)

I've tried to take a look at issue #82  however there's a problem with Javascript, not SCSS. Any idea what could cause it?

**Comment by pmmmwh** [comment]
I'm not sure about your setup, but are you using [style-loader](https://github.com/webpack-contrib/style-loader) or [mini-css-extract-plugin](https://github.com/webpack-contrib/mini-css-extract-plugin)?

I think the former should have HMR OOTB, and the latter you have to [enable the `hmr` flag](https://github.com/webpack-contrib/mini-css-extract-plugin/#hot-module-reloading-hmr).

**Comment by jansedlon** [comment]
Hah, that's it! Thank you very much :)

**Comment by tony-go** [comment]
Hey 👋  

Awesome plugin 👏 thanks for the job.

I felt in this trap, haha.

I could open a PR to add it to the README in the Usage section: https://github.com/pmmmwh/react-refresh-webpack-plugin#usage

WDYT?
