### ISSUE TITLE
Get this one some of the pages. Too cryptic error don't know where to dig

### ISSUE THREAD

**Issue by addamove** [pmmmwh/react-refresh-webpack-plugin#185]
![Screenshot_20200818_130624](https://user-images.githubusercontent.com/26085770/90500583-c57c1500-e153-11ea-9a35-a2640ed4affd.png)

**Comment by pmmmwh** [comment]
I think the error is quite obvious? `401 Unauthorized`.

As for the error overlay, a revamp is planned. I don't have time to work on it just yet, but for this scenario (i.e. non-error thrown with the `throw` statement and we do not know how to present it) we can just show something like `non-error thrown, please look at the console for more information`.

**Comment by addamove** [comment]
>  think the error is quite obvious? 401 Unauthorized.

Lol this was stupid, please forgive me.
I just looked at callstack, saw `node_modules/@pmmmwh/react-refresh-webpack-plugin/` and started to think that error somewhere in node_modules.
