### ISSUE TITLE
Recipe for "do not know how to hot reload themselves"

### ISSUE THREAD

**Issue by binarykitchen** [pmmmwh/react-refresh-webpack-plugin#187]
Thanks for your awesome work. Reduces lots of webpack boilerplate.

Just stuck with some React components it won't refresh. Seeing those warnings I cannot crack after lots of research:

```
Ignored an update to unaccepted module ... [very long path]
[HMR] The following modules couldn't be hot updated: (Full reload needed)
This is usually because the modules which have changed (and their parents) do not know how to hot reload themselves. See https://webpack.js.org/concepts/hot-module-replacement/ for more details.
```

Any clues?

**Comment by pmmmwh** [comment]
This would mean that we weren't able to find any places we can safely stop the HMR propagation.

Is there no file within that path that contains React components only, or are you not naming React components in `PascalCase`?

**Comment by binarykitchen** [comment]
> Is there no file within that path that contains React components only, 

There are files in that path which are NOT React

> or are you not naming React components in `PascalCase`?

React components are in Pascal case but the directories aren't. For example `./src/modules/apple/apple_sets/views/toolbar/Toolbar.es`

What do you think?

**Comment by binarykitchen** [comment]
I see. You explained this very well. Maybe want to add this on README.md?

Many thanks!

**Comment by pmmmwh** [comment]
> I see. You explained this very well. Maybe want to add this on README.md?
> 
> Many thanks!

#189 - if you have any comments please do tell me!

**Comment by sahilrajput03** [comment]
> > There are files in that path which are NOT React
> 
> If, for example, in that path no file only exports Fast Refresh compatible stuff (i.e. React components - `PascalCase`, for HOCs the internal wrappers also have to be in this format), then we would have to propagate the update upwards, and eventually reach the root.
> 
> It doesn't mean that the build wouldn't work, it just mean that we cannot safely refresh the actual call path and the app would likely be in an inconsistent state after HMR. This mechanism is in place because we cannot safely assume anything out of React is side-effect-less - which would require cleanup.
> 
> There's also an edge case with `export *` syntax, especially with TypeScript - this is more abundant when you mix type exports and normal exports together.
> 
> File/directory names does not matter.
> 
> Another thing I would take a look at is if you have multiple bundles on a single page, or if `react-refresh` and `react` are on different chunks.
> 
> If you really want me to further help diagnose, it would be better if you can provide some sort of a minimal reproducible example.

Can you explain what are  you reffering  by type export and normal export..?

**Comment by pmmmwh** [comment]
> Can you explain what are you reffering by type export and normal export..?

"Type"

```ts
export type Something = string;
export interface SomethingInterface {
  property: string;
}
```

"Normal"

```ts
export const Something = 'something';
```
