### ISSUE TITLE
Using a package installed from a local directory will lead to "Can't resolve 'react-refresh/runtime'" error

### ISSUE THREAD

**Issue by nopol10** [pmmmwh/react-refresh-webpack-plugin#188]
I have a main project that relies on a components package installed from another project. This is published to an npm repository but for developmental purposes, I sometimes install the package locally using the following in dependencies in package.json
```
"components-library": "file:../components-library",
```
When I attempt to start the dev server, I'll get the following error

> ERROR in ../components-library/dist/index.js
> Module not found: Error: Can't resolve 'react-refresh/runtime' in 'C:\components-library\dist'
> .
> .
> .
>  @ multi ./node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ReactRefreshEntry.js webpack-dev-server/client?http://localhost:8080/ ./node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ErrorOverlayEntry.js webpack/hot/dev-server ./src/index.tsx

The components library itself does not have react-refresh installed.
When the components-library is installed from the repository (`"components-library": "^1.4.1",`), the issue does not occur. Apart from installing react-refresh in the components-library, is there a way to prevent the error from occurring?

**Comment by pmmmwh** [comment]
You can use the `exclude` option to make sure it does not get processed.

Docs not ready yet but you can take a look [here](https://github.com/pmmmwh/react-refresh-webpack-plugin/blob/docs/rewrite/docs/API.md).

**Comment by nopol10** [comment]
Thanks, this works well!

My configuration for anyone who's interested:
```
new ReactRefreshWebpackPlugin({
    exclude: [
        path.resolve("../component-library"),
        /node_modules/,
    ],
})
```
