### ISSUE TITLE
Fast Refresh is lagging one "save" behind

### ISSUE THREAD

**Issue by ceisele-r** [pmmmwh/react-refresh-webpack-plugin#199]
Thanks for the plugin!

I installed the plugin as described in the readme and it's basically working to fast refresh the page.
But I am encountering an issue that causes the following weird behavior:
* I change some code and save it - Server side, webpack compiles until it says `i ｢wdm｣: Compiled successfully.`
* Client-side in the browser, I see that it got noticed of something happening:
![image](https://user-images.githubusercontent.com/54797986/92114738-a33ff380-edf1-11ea-8599-15f55e2de3b1.png)

But it does not seem to receive the completed compile.
* Now if I save another time, server side webpack compiles again and client-side, it receives the update:
![image](https://user-images.githubusercontent.com/54797986/92114863-d4b8bf00-edf1-11ea-9e8c-d3bbc99e57c0.png)
As you can see, before it did not reach the point "App is up to date"

This actually stays like this meaning the Browser gets updated with 1 save behind:
* In the code, I change a string from "Test" to "Test2"
* Save
* Browser still shows "Test" (even though, in the Browser console it updates and comes to the last line "App is up to date" now)
* Save again
* Browser shows "Test2"
* Change the string to "Test3"
* Save
* Browser still shows "Test2"
* Change the string to "Test4"
* Save
* Browser updates to "Test3"

Server-side, it says (for each save):
```
i ｢wdm｣: Compiling...
node_modules/webpack-log/src/loglevel/PrefixFactory.js:55
webpack building...
...
i ｢wdm｣: Compiled successfully.
```

As said above, after the first save, it says for each update in the Browser ""App is up to date". So it kind of seems to miss the first compile completion and therefore always lags one save behind.

Do you have any idea what could be causing this?

**Comment by pmmmwh** [comment]
Hi, can you describe more about your setup? `webpack-dev-server`/`webpack-hot-middleware`/`webpack-plugin-serve`? `react` and `webpack` versions? How is Webpack configured? How are components structured (HOC/Class/Hooks/exports rewiring/etc.)?

**Comment by ceisele-r** [comment]
Hi @pmmmwh ,

Of course, I hope the following information helps.

Server is a Hapi Server using `hapi-webpack-plugin-2`
```
const HapiWebpackPlugin = require("hapi-webpack-plugin-2").default;
const config = require("../webpack.config.js");
await server.register({
      plugin: HapiWebpackPlugin,
      options: {
        config: {
          compiler: webpack(config),
          assets: {
            noInfo: true,
            publicPath: "/" + config.output.publicPath
          },
          hot: {
          },
        },
      },
    });
```

webpack is `4.44.1`
react is `16.13.1`

Webpack is configured in development mode with the following entrypoints:
```
entry: {
    app: [
      "webpack-hot-middleware/client?path=http://localhost/app/__webpack_hmr",
      "./src/common/server.tsx"
    ],
    other: "./src/common/other.ts"
  },
```

`babel-loader` is used in webpack and configured as follows:
```
{
          loader: "babel-loader",
          options: {
            presets: [
              [
                "@babel/preset-env",
                {
                  "useBuiltIns": false,
                  "debug": false,
                  "targets": {
                    "esmodules": true,
                  }
                }
              ],
              [
                "@babel/preset-typescript"
              ],
              "@babel/preset-react"
            ],
            plugins: [
              "@babel/plugin-transform-modules-commonjs",
              "@babel/proposal-object-rest-spread",
              ["@babel/plugin-proposal-decorators", { "legacy": true }],
              ["@babel/proposal-class-properties", { "loose": true }],
              "lodash",
              require.resolve("react-refresh/babel"),
            ],
            cacheDirectory: "./.cache/babel-loader/es6"
          }
        }
```

Components are structured as classes (`class ComponentA extends React.Component<ILocalProps, ILocalState>`).

Let me know if you need more details.

**Comment by IronSean** [comment]
I'm having a variant of this issue, my updates never trigger reloads because my app always thinks it's up to date:

![image](https://user-images.githubusercontent.com/1960190/92506619-170c4280-f1dc-11ea-9b1f-0f7074ac6ab2.png)

webpack 4.44.1
react 16.3.1
react-refresh 0.8.3
@pmmmwh/react-refresh-webpack-plugin 0.4.2

My hot reload config merges into my normal webpack config like this:
```javascript
const webpack = require('webpack');
const Merge = require('webpack-merge');
const DevConfig = require('./webpack.dev.js');
const ReactRefreshWebpackPlugin = require('@pmmmwh/react-refresh-webpack-plugin');

const babelLoader = {
  loader: 'babel-loader?cacheDirectory',
  options: {
    presets: ['@babel/react', '@babel/typescript', ['@babel/env', { modules: 'auto' }]],
    plugins: [
      '@babel/plugin-proposal-class-properties',
      '@babel/plugin-proposal-optional-chaining',
      '@babel/plugin-proposal-nullish-coalescing-operator',
      'react-refresh/babel',
    ],
  },
};

module.exports = Merge.smart(DevConfig, {
  module: {
    rules: [
      {
        test: /\.(ts|tsx)$/,
        exclude: /node_modules/,
        use: [
          babelLoader,
          {
            loader: 'ts-loader',
            options: {
              transpileOnly: true,
              experimentalWatchApi: true,
            },
          },
        ],
      },

      {
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        use: [babelLoader],
      },
    ],
  },
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new ReactRefreshWebpackPlugin()],
});
```

And my devserver config is 
```javascript
 devServer: {
    headers: {
      'Access-Control-Allow-Origin': 'http://localhost:2354',
      'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, PATCH, OPTIONS',
      'Access-Control-Allow-Headers': 'X-Requested-With, content-type, Authorization',
    },
    // contentBase: './dist',
    writeToDisk: true,
    hot: true,
  },
```

**Comment by IronSean** [comment]
It does work using
react-refresh 0.7.2
react-refresh-webpack-plugin 0.1.3

and plugins:
```javascript
  plugins: [new ReactRefreshWebpackPlugin({ disableRefreshCheck: true })],
```

**Comment by pmmmwh** [comment]
@IronSean I think you're hitting a recursion issue with HMR. If you remove `webpack.HotModuleReplacementPlugin()` while keeping `hot: true` in `devServer` your setup should work.
You probably would want remove the typescript for babel since you're using `ts-loader` for transpilation. Probably you will only need `react-refresh/babel` for `ts` files ...

**Comment by pmmmwh** [comment]
@ceisele-r Hi, I'm sorry that I really cannot reproduce your case. I suspect that you do not have the development server configured properly - can you provide a full reproducible example?

**Comment by ceisele-r** [comment]
@pmmmwh Hi, unfortunately I don't think I can provide a full reproducible example as the project is rather big and I'm not sure if I can extract the essential parts of it. Is there anything I can do to further trace this down? I already checked the hmr messages ending up in browser and compared them to the log message from the server - the webpack hash indicates that it always sends built from 1 save behind to the browser. Maybe it's trying to send the HMR result before the server-side compile actually completes?

**Comment by pmmmwh** [comment]
> @pmmmwh Hi, unfortunately I don't think I can provide a full reproducible example as the project is rather big and I'm not sure if I can extract the essential parts of it. Is there anything I can do to further trace this down? 

Is it possible for you to provide the full webpack config and the full Hapi server config (excluding other parts like API if you run those together)? Maybe I'm just not being to reproduce because there are some information missing. I'll try to create a sandbox with that.

You can try making `webpack-dev-middleware` write to disk and see if the change is written after a recompile.

> Maybe it's trying to send the HMR result before the server-side compile actually completes?

I actually have no idea, never hit this before. Just for clarification are you doing SSR?

**Comment by ceisele-r** [comment]
@pmmmwh thanks. I tried setting `writeToDisk` and saw then that webpack logs `webpack built 9856dfc0ba05f5845246 in 2503ms` but on disk, only files with the "1 save before" hash have been saved. So even when writing to disk it seems to lag already one step behind.

I try to share the essential parts of the hapi server config with you (as the full config is rather long and can unfortunately not be shared):

```
let server: Hapi.Server;
const publicPath = path.join(__dirname, "../../public");

export async function startWebserver(): Promise<void> {
    try {
      await configureServer();
      await server.start();
    } catch (ex) {
      Log.log(LogLevel.INFO, "Server could not started.");
    }
  }
}


async function configureServer(): Promise<void> {
  let tls: https.RequestOptions | undefined = undefined;

  server = new Hapi.Server({
    tls,
    state: {
    },
    port: SConfig.serverPort,
    routes: {
      cors: {
        origin: ["*"]
      },
      files: {
        relativeTo: publicPath
      },
    },
    host: "0.0.0.0" // Listen to all IPs
  });

  await server.register({
    plugin: require("@hapi/inert")
  });

  // Auth config

  await server.register({
    plugin: Nes,
    options: {
      // Nes config
    }
  });

if (process.env.HOTRELOAD !== "no" && !isProduction) {
    const hotReload = await import("./webserver-hotreload");
    await hotReload.setup(server, publicPath);
  }
// ...
// Route-Configs
// ...
}


/// webserver-hotreload.ts
import Hapi from "@hapi/hapi";
import webpack from "webpack";
const HapiWebpackPlugin = require("hapi-webpack-plugin-2").default;
const config = require("../webpack.config");

export async function setup(server: Hapi.Server, publicPath: string): Promise<void> {
  try {
    await server.register({
      plugin: HapiWebpackPlugin,
      options: {
        config: {
          // Webpack options http://webpack.github.io
          compiler: webpack(config),
          assets: {
            // Webpack-dev-middleware options https://github.com/webpack/webpack-dev-middleware
            noInfo: true,
            publicPath: "/" + config.output.publicPath,
            writeToDisk: true,
          },
          hot: {
            // Webpack-hot-middleware options https://github.com/glenjamin/webpack-hot-middleware
          },
        },
      },
    });
  } catch (error) {
     // ... Logging
  }
}

/// webpack.config
const path = require("path");
const fs = require("fs");
const webpack = require("webpack");
const copyplugin = require("./copywebpackplugin");
const BundleAnalyzerPlugin = require("webpack-bundle-analyzer").BundleAnalyzerPlugin;
const MomentLocalesPlugin = require("moment-locales-webpack-plugin");
const splitChunks = require("./webpack_optimization_splitchunks");
const ReactRefreshWebpackPlugin = require('@pmmmwh/react-refresh-webpack-plugin');

module.exports = {
  cache: true,
  mode: "development",
  entry: {
    entryone: [
      "webpack-hot-middleware/client?path=http://localhost/__webpack_hmr",
      "./src/app/server.tsx"
    ],
    entrytwo: "./src/app/two.ts"
  },
  output: {
    filename: "[name].bundle.js",
    chunkFilename: "[name].bundle.js",
    path: path.resolve(__dirname, "../public/dist"),
    publicPath: "dist/"
  },
  watch: false,

  devtool: "source-map",

  resolve: {
    extensions: [".webpack.js", ".web.js", ".ts", ".tsx", ".js", ".json"]
  },

  optimization: {
    splitChunks,
  },

  module: {
    rules: [
      {
        test: /\.s[ac]ss$/i,
        use: [
          // Creates `style` nodes from JS strings
          "style-loader",
          // Translates CSS into CommonJS
          "css-loader",
          // Compiles Sass to CSS
          "sass-loader",
        ],
      },
      {
        test: /\.css$/,
        loaders: [
          "style-loader",
          "css-loader"
        ]
      },
      {
        test: function (modulePath) {
          return (modulePath.endsWith(".js") || modulePath.endsWith(".ts") || modulePath.endsWith(".tsx"));
        },
        include: [
          path.resolve(__dirname, "../src"),
        ],
        use: {
          loader: "babel-loader",
          options: {
            presets: [
              [
                "@babel/preset-env",
                {
                  // Do not include core-js as its loaded globally
                  "useBuiltIns": false,
                  "debug": false,
                  "targets": {
                    "esmodules": true,
                  }
                }
              ],
              [
                "@babel/preset-typescript"
              ],
              "@babel/preset-react"
            ],
            plugins: [
              "@babel/plugin-transform-modules-commonjs",
              "@babel/proposal-object-rest-spread",
              ["@babel/plugin-proposal-decorators", { "legacy": true }],
              ["@babel/proposal-class-properties", { "loose": true }],
              "lodash",
              require.resolve("react-refresh/babel"),
            ],
            cacheDirectory: "./.cache/babel-loader/es6"
          }
        }
      }
    ]
  },

  plugins: [
    copyplugin,
    new webpack.DllReferencePlugin({
      context: __dirname, // Path.join(__dirname, "src"),
      manifest: require("./../dist/vendor-manifest.json")
    }),
    new webpack.DllReferencePlugin({
      context: __dirname, // Path.join(__dirname, "src"),
      manifest: require("./../dist/lib-manifest.json")
    }),
    new webpack.DefinePlugin({
      "process.env": {
        "NODE_ENV": JSON.stringify("development"),
        "API_URL": JSON.stringify("http://localhost:8080")
      }
    }),
    // Creates HTML file to analyze bundle
    new BundleAnalyzerPlugin({
      analyzerMode: "static",
      reportFilename: "../../webpackreport/app_report.html",
      openAnalyzer: false,
      generateStatsFile: false
    }),
    // Strip all locales except en (default) and de
    new MomentLocalesPlugin({
      localesToKeep: ["de"]
    }),
    new webpack.HotModuleReplacementPlugin(), // Hot reload
    new ReactRefreshWebpackPlugin(),
  ],

  // When importing a module whose path matches one of the following, just
  // assume a corresponding global variable exists and use that instead.
  // This is important because it allows us to avoid bundling all of our
  // dependencies, which allows browsers to cache those libraries between builds.
  externals: {
    "react": "react",
    "react": "React",
    "react-dom": "ReactDOM",
    "$": "jQuery",
    "jquery": "jQuery",
    "jQuery": "jQuery"
  },
  node: {
    dns: "mock",
    net: "mock"
  },
};
```

I hope these parts help. Regarding your question, I am not doing SSR.

**Comment by yumindev** [comment]
OK, I have encountered the same issue. But I have more info on it.

I am using react-loadable. And I have issues with async components, yes, the same issue, at least one "save" behind. But If I use regular import, `import Acoompont from a-comp`,  not dynamic import, things will be fine.

So, I guess the problem relates to lazy loading or dynamic import

**Comment by pmmmwh** [comment]
Tested with the latest release and cannot reproduce anymore.

If the issue still persists, feel free to re-open or file a new issue with reproduction, thanks!
