### ISSUE TITLE
$RefreshReg$ appears in production bundle

### ISSUE THREAD

**Issue by kevinwilde** [pmmmwh/react-refresh-webpack-plugin#2]
Hey there! Super excited about the work happening here.

One thing I noticed is that if I clone this repo, and run `yarn build` in the example app, the bundled main.js contains references to $RefreshReg$. Opening the built app via dist/index.html crashes as a result.

If this is unhelpful because it's still so early in the development of this plugin, feel free to close this. I'm happy to try to help if possible, but I'm not very familiar with webpack plugins or babel plugins, and wouldn't want to slow you down 😅

**Comment by pmmmwh** [comment]
Hey @kevinwilde ! Sorry for my late reply. The reason the build breaks is that the `react-refresh/babel` plugin is applied unconditionally, which will apply transforms to the bundle. I will push a fix to the example app later today to fix that.

**Comment by pmmmwh** [comment]
Fixed b241366
