### ISSUE TITLE
Cannot find update. Need to do a full reload! 

### ISSUE THREAD

**Issue by demian85** [pmmmwh/react-refresh-webpack-plugin#200]
Hi guys, I've spent an hour trying to fix this issue with no luck.
I've never used hot loader before and saw that is is being deprecated so I wanted to start with fast refresh from scratch.
I'm getting the following errors in the console when editing a file:
![image](https://user-images.githubusercontent.com/470630/92116639-7a583800-edca-11ea-8dfb-1868ea140c25.png)

My question is: why the fuck is webpack-dev-server not finding the update and where should that be placed in the filesystem? What sorcery is needed to make the dev server understand how to find the update that was generated by server itself?

My stack is Babel + Typescript + React + Webpack (obviously)

webpack.config.js:
```js
require('dotenv/config')

const webpack = require('webpack')
const path = require('path')
const MiniCssExtractPlugin = require('mini-css-extract-plugin')
const ReactRefreshWebpackPlugin = require('@pmmmwh/react-refresh-webpack-plugin')

module.exports = (env = {}) => {
  const prodMode = env.production || process.env.NODE_ENV === 'production'

  const plugins = [
    new webpack.DefinePlugin({
      'process.env.API_BASE_URL': JSON.stringify(process.env.API_BASE_URL),
    }),
  ]

  if (prodMode) {
    plugins.push(
      new MiniCssExtractPlugin({
        filename: 'bundle.css',
      })
    )
  } else {
    plugins.push(new ReactRefreshWebpackPlugin())
  }

  return {
    mode: prodMode ? 'production' : 'development',
    devtool: prodMode ? 'source-map' : 'eval-source-map',
    entry: './src/index.tsx',
    output: {
      path: path.resolve(__dirname, 'public'),
      filename: 'bundle.js',
    },
    resolve: {
      extensions: ['.tsx', '.ts', '.js', '.jsx', '.json', '.css', '.less'],
      alias: {
        '@components': path.resolve(__dirname, 'src/components/'),
        '@lib': path.resolve(__dirname, 'src/lib/'),
      },
    },
    devServer: {
      contentBase: path.join(__dirname, 'public'),
      historyApiFallback: true,
      port: process.env.PORT || 8080,
      hot: true,
    },
    module: {
      rules: [
        { test: /\.(t|j)sx?$/, use: ['babel-loader'], exclude: /node_modules/ },
        {
          test: /\.((c|le)ss)$/i,
          use: [
            prodMode ? MiniCssExtractPlugin.loader : 'style-loader',
            'css-loader',
          ],
        },
      ],
    },
    plugins,
  }
}
```

babelrc.js:
```js
module.exports = {
  presets: [
    [
      '@babel/preset-env',
      {
        targets: {
          node: 'current',
        },
        useBuiltIns: 'usage',
        corejs: 3,
      },
    ],
    '@babel/preset-typescript',
    '@babel/preset-react',
  ],
  plugins: [
    '@babel/plugin-proposal-nullish-coalescing-operator',
    '@babel/plugin-proposal-optional-chaining',
    'react-refresh/babel',
  ],
}
```

I'd appreciate your help!

**Comment by pmmmwh** [comment]
Hi - I think you somehow got `webpack-dev-server` confused ... what are you using for routing?

Maybe you can try disabling `devserver.historyApiFallback`?

**Comment by demian85** [comment]
> Hi - I think you somehow got `webpack-dev-server` confused ... what are you using for routing?
> 
> Maybe you can try disabling `devServer.historyApiFallback`?
> 
> **Edit**:
> Oh actually - can you try changing your `output.path` to not be the same as `devServer.contentBase`?

If I disable historyApiFallback, after refreshing the page I will get 404 since all the routing is done client side. I don't see other way.
Why would I have different output and contentBase directories? shouldn't those be the same? the bundle should be public, and the server should serve.... from the public directory. Not sure how to change those paths :/

**Comment by demian85** [comment]
Just changed the output to /build and still the same issue. It is looking for json files in the same path the URL says.
So if my URL path is /users, the dev server is searching for the json update at /reviews/something.json.
How can I tell the dev server to go find the damn update in / instead?

**Comment by pmmmwh** [comment]
> Why would I have different output and contentBase directories? shouldn't those be the same? the bundle should be public, and the server should serve.... from the public directory.

This is not exactly what is happening. WDS serves compiled files from it's own in-memory file system, and if you use the same path for `output` (which is supposed where your built files will go) and `devServer.public` (which is supposed to be used to serve static files during development only), if you have a bundle that was built previously and you did not have any caching in place it _might_ mess up.

Also - did `output.publicPath` fixed your problem?

**Comment by pmmmwh** [comment]
Seems like this have been resolved so I'll be closing this. Feel free to re-open if you need more help!
