### ISSUE TITLE
Excluding errors from node_modules

### ISSUE THREAD

**Issue by jansedlon** [pmmmwh/react-refresh-webpack-plugin#202]
Hello! I would like to ask if there's any way to disable overlay for errors from third part libraries? For example firebase throws error if it's opened in multiple tabs because `enablePersistence: true` is not enabled. I can't change this because it's in a huge project. It's a bit annoying if the overlay is displayed on every refresh 😅

**Comment by pmmmwh** [comment]
Unfortunately, not currently. This is being worked on.
