### ISSUE TITLE
Using react-refresh-webpack-plugin in a web extension environment

### ISSUE THREAD

**Issue by OriginalEXE** [pmmmwh/react-refresh-webpack-plugin#207]
Hello, thank you for maintaining this awesome plugin.

I wanted to make use of it for my browser extension (specifically, in the popup), but it appears that the web sockets library that is being used refuses to work on the non-http(s) protocol. Here is the exact error I am getting:

```
Uncaught SyntaxError: The URL's scheme must be either 'http:' or 'https:'. 'chrome-extension:' is not allowed.
    at new SockJS (sockjs.js:683)
```

Here is the code that is throwing:
```
else if (parsedUrl.protocol !== 'http:' && parsedUrl.protocol !== 'https:') {
  throw new SyntaxError("The URL's scheme must be either 'http:' or 'https:'. '" + parsedUrl.protocol + "' is not allowed.");
}
```

Is there anything I can do on my side to work around this, or is just not supported yet and I should give up?

Any help would be appreciated.
Ante

**Comment by pmmmwh** [comment]
Hi, I would like to know more about your development setup - are you using `webpack-dev-server`?

I think if you set the `transportMode` to `ws` instead of the default `sockjs` it would use native `WebSockets` with looser restrictions.

**Comment by OriginalEXE** [comment]
Hi, thanks for helping out. I indeed use the standard webpack dev server. I'll try your suggestion, that sounds like it could work, thanks. Will report back.

**Comment by OriginalEXE** [comment]
Unfortunately, it does not look like ws helps. Also, it seems to me like this is not the fault of your plugin.

Here is the code from the dev server WebsocketClient.js file:

```
_this.client = new WebSocket(url.replace(/^http/, 'ws'));
```

Since the extensions don't have a http(s) protocol, the replacement never happens and so the url is not valid.

I guess I'll try raising an issue in the Webpack dev server repo instead.

Thanks again for taking a look.

**Comment by pmmmwh** [comment]
> Unfortunately, it does not look like ws helps. Also, it seems to me like this is not the fault of your plugin.
> 
> Here is the code from the dev server WebsocketClient.js file:
> 
> ```
> _this.client = new WebSocket(url.replace(/^http/, 'ws'));
> ```
> 
> Since the extensions don't have a http(s) protocol, the replacement never happens and so the url is not valid.
> 
> I guess I'll try raising an issue in the Webpack dev server repo instead.
> 
> Thanks again for taking a look.

Just some quick questions - does WebSockets work in extensions just like browsers? Is there a difference like `ws` vs `wss`? (We also have a bit of url interpolation logic here in the plugin so that would be useful info to us too)

**Comment by OriginalEXE** [comment]
To my knowledge there is no difference in how it works.

I am using the Webpack dev server together with the `react-hot-loader` and it works just fine, I just wanted the improved experience of the `react-refresh` :)

![image](https://user-images.githubusercontent.com/2056251/93982942-367da080-fd82-11ea-8d6a-e67101aee5fd.png)
