### ISSUE TITLE
Is webpack-hot-middleware/client entry point necessary?

### ISSUE THREAD

**Issue by dlong500** [pmmmwh/react-refresh-webpack-plugin#213]
I see in the example for webpack-hot-middleware that `webpack-hot-middleware/client` is listed in the entry array, but hot reloading seems to work for me without that entry point.  Is that something that is now being dynamically injected by the react-refresh plugin?

Just curious.  Things seem to work with or without that entry point, but I don't know if I'm missing an edge case scenario where it is necessary.  On the other side, I also don't want to duplicate the entry if it is already being dynamically injected.

**Comment by pmmmwh** [comment]
It is best if you add the entry point yourself - it ensures the injection order which is important for flows related to error reporting. We do lazily inject it if you're using `whm` and the injected client wasn't found, but that is just our best effort to recover.
