### ISSUE TITLE
Does not reload function body (Not React Component)

### ISSUE THREAD

**Issue by joacub** [pmmmwh/react-refresh-webpack-plugin#222]
Hi guys, the plugin is telling me it is reloading but nothing happens in some cases,

for example 

```js
doSomethingFunction.js
const doSomething = () => {
   console.log('If you change this text never change when reload and plugin apparently is reloading everything but not this');
};
export default doSomething;
```

```js
import doSomethingFunction from 'doSomethingFunction';

consta ReactComponent = () => {
   const something = doSomethingFunction();
   return <div>Here if you change something works</div>
};
```

**Comment by pmmmwh** [comment]
Hi - this example is exactly a side-effect in render.

Render should always be pure and does not fire any side-effects - because we can never reliably detect them.

If you move the call to `doSomething` in an `useEffect`, it will work flawlessly.
