### ISSUE TITLE
IE11 error - SCRIPT1003: Expected ':'

### ISSUE THREAD

**Issue by hinok** [pmmmwh/react-refresh-webpack-plugin#223]
### Pull request https://github.com/pmmmwh/react-refresh-webpack-plugin/pull/224

---

Hey,
I found a small issue on IE11.

```
SCRIPT1003: Expected ':'
```

which redirects to the code below

![Zrzut ekranu 2020-10-7 o 15 47 49](https://user-images.githubusercontent.com/1313605/95339685-9c0a7a80-08b4-11eb-9a17-0c7c5a8a9a2e.png)

This can be solved by:

1. Transpiling the code
2. Changing the code to use ES5

I decided that it's better to explain transpiling this code in [Troubleshooting](https://github.com/pmmmwh/react-refresh-webpack-plugin/blob/656b49fa802836c6a6f2dc0329447956d63f3a77/docs/TROUBLESHOOTING.md) which doesn't cover this case at the moment. I added PR that explain how this can be solved.

**More screenshots**

![Zrzut ekranu 2020-10-7 o 15 43 56](https://user-images.githubusercontent.com/1313605/95339851-cfe5a000-08b4-11eb-91b3-ee7d9f0356a5.png)

![Zrzut ekranu 2020-10-7 o 15 41 33](https://user-images.githubusercontent.com/1313605/95339873-d542ea80-08b4-11eb-96a5-07c17778ecd6.png)

**Comment by pmmmwh** [comment]
Hi - thanks for reporting the bug. This was not supposed to happen - we do promise IE11 compatibility OOTB so we probably should fix the source code instead of providing steps for transpiling.
