### ISSUE TITLE
Crash on HMR

### ISSUE THREAD

**Issue by fabiospampinato** [pmmmwh/react-refresh-webpack-plugin#227]
- **webpack**: v4.44.2
- **@pmmmwh/react-refresh-webpack-plugin**: v0.4.2
- **react-refresh**: v0.8.3

I've been using this plugin for a while and I had no problems with it initially, but since a few weeks for some reason whenever I edit _some_ files, and a HMR is triggered, my app crashes.

I don't know what's causing this, this is what I know so far:

- I use this plugin with its default options, and I haven't changed any options since I started using it.
- If I remove this plugin from my webpack configuration I see no crashes. 
- If I edit my components directly with this plugin active I don't see any problems either.
- If I edit _some_ other files, outside of my React root, I still see no problems.
- If I edit _some_ other files though the app crashes on me.
- My dependencies graph looks a bit like the graph below, there's a "root" file that has almost every other file containing the logic of the app in its dependency tree, and that same root file itself is also referenced by components and some of the other files too. What happens is that editing components doesn't cause a crash, I think because those components are not themselves dependencies of the root file, but editing files in its dependency tree eventually causes the error screenshotted below, and the app crashes.
- That error happens because some files are getting HMR'd, they import that root file but the default export of that root file now for some reason is `undefined`.
- I think I have some cycles in my dependencies graph, so like there are probably paths going from a file to the root and from the root to the file. Cycles that aren't really a problem otherwise because the default exports of those modules are only resolved later on when both modules have finished loading.
- That's all I know, I'm guessing perhaps cycles in my dependencies graph are causing some modules to be disposed of and then referenced again before being fully reloaded or something like that, but I haven't messed with my dependencies graph yet to really test this hypothesis.

![](https://www.planttext.com/api/plantuml/svg/SoWkIImgAStDuKh9J2zABCXGS5Uevb800f_yzCpaUBVCd5G5NJk5eFpy4Z07BETVaf5QX4CEpWD98Go1oAKc9fV4E-Vd5kJdfUQL5AFghbNWSaZDIm4w1W00)

![image](https://user-images.githubusercontent.com/1812093/96324950-49e7f880-101c-11eb-8f6d-16073592aeae.png)

Any ideas on what I should be doing to debug this further? And does this sound like something that potentially should be fixed at the plugin level? As I'm not experiencing any such problems with the plugin disabled I'm guessing this is something the plugin should address, probably.

Thanks!

**Comment by pmmmwh** [comment]
I think this has something to do with cyclic dependencies - the actual order of cyclic imports during HMR is not ensured to be stable because updates propagate from the location of the change (i.e. to be the same on every reload, and to be the same as the original first load).

**Comment by fabiospampinato** [comment]
Do you think it would be possible to address this at the plugin level somehow?

Like maybe the import order could be stored during the initial load and then during HMR the update path could be traversed in the same order?

**Comment by pmmmwh** [comment]
> Do you think it would be possible to address this at the plugin level somehow?
> 
> Like maybe the import order could be stored during the initial load and then during HMR the update path could be traversed in the same order?

Unfortunately, no. This has to be done inside the actual HMR runtime itself - that is, Webpack's HMR runtime - because we don't actually have info about the dependency tree.

See webpack/webpack#11016.

**Comment by fabiospampinato** [comment]
Alright, I'll close this then, thanks for the help 👍
