### ISSUE TITLE
Cannot read property 'signature' of undefined

### ISSUE THREAD

**Issue by kharenzze** [pmmmwh/react-refresh-webpack-plugin#229]
Hi! My app satisfies all of the requirements, but i'm getting this error: 

![image](https://user-images.githubusercontent.com/5865128/96500630-7899e500-124f-11eb-91d1-aac8406a4ace.png)

Any thoughts?

**Comment by pmmmwh** [comment]
Hi - just so I understand, how are you using the plugin and how are you building your app?

**Comment by kharenzze** [comment]
Hi! I was using CRA 3.4.4 + craco + [craco-fast-refresh](https://github.com/vimcaw/craco-fast-refresh). I posted the same [issue](https://github.com/vimcaw/craco-fast-refresh/issues/5) there before posting this one. 

They recently released CRA 4.0.0 and it comes along with fast-resfresh integrated. So, I upgraded react-scripts and it's working right now! So I guess I was missing some requirement/configuration related to webpack/babel which is managed under-the-hood by react-scripts.

I'm closing this issue. Thank you! Your webpack plugin is great :)

**Comment by Chandu** [comment]
@kharenzze We are experiencing the same issue and are using CRA 3.4.4 + craco + craco-fast-refresh
Nothing special in terms of how we are configuring the plugin just straight forward inclusion of the plugin in the craco.config.js.

What was the issue/root cause you have identified with your config?

**Comment by kharenzze** [comment]
I think the issue is related to the requirements
![image](https://user-images.githubusercontent.com/5865128/100217161-6e849980-2f13-11eb-88c9-9cc3327bfda1.png)
I think they're not satisfied by react scripts 3.4.4. I recommend you to upgrade to v4.0.1

**Comment by pmmmwh** [comment]
That seems like exactly the issue! If you can't use CRA v4 you can also just use resolutions to force `webpack` to be `4.43.0+`.

**Comment by Chandu** [comment]
@kharenzze @pmmmwh Thank you.

**Comment by justinbhopper** [comment]
Had this issue too.  Turned out I needed to add a devDependency to `react-reconciler`, where previously it was not needed.  I upgraded from react-scripts v3 to v4.0.3 when I encountered this issue, so they must have changed their peer dependencies.

**Comment by sophia-ma** [comment]
I have just upgraded to CRA4 and node14 and I am trying to set up an existing npm package for local development with `npm link` and I am getting the same issue. It was working with node10 and CRA2.

**Comment by pmmmwh** [comment]
@sophia-ma Maybe you can raise an issue in CRA's repo? What version of dependencies are you using?

**Comment by aelkoussy** [comment]
Hi, thanks for the great plugin @pmmmwh
 
I got the same issue and the solution was to just remove this line that was mentioned in the Readme:
              `plugins: [isDevelopment && require.resolve('react-refresh/babel')].filter(Boolean),`

only keeping the other line:
 ` plugins: [isDevelopment && new ReactRefreshWebpackPlugin()].filter(Boolean),`
was sufficient for it to work. :)
