### ISSUE TITLE
react-refresh 0.8.3 dependency warning

### ISSUE THREAD

**Issue by silkfire** [pmmmwh/react-refresh-webpack-plugin#231]
Since upgrading `react-refresh` to v0.9.0 I'm getting a warning saying I need v0.8.3 instead. Despite this, everything seems to be working as it should.

> @pmmmwh/react-refresh-webpack-plugin@0.4.2 requires a peer of react-refresh@^0.8.3 but none is installed. You must install peer dependencies yourself.

**Comment by pmmmwh** [comment]
I will relax the peer-dependencies range - thanks for reporting.
