### ISSUE TITLE
__webpack_require__ is not defined when evaluating ./node_modules/@pmmmwh/react-refresh-webpack-plugin/overlay/components/Spacer.js

### ISSUE THREAD

**Issue by tranvansang** [pmmmwh/react-refresh-webpack-plugin#232]
My app encountered the following error when I tried integrating `@pmmmwh/react-refresh-webpack-plugin`.

```
main.js:formatted:9401 Uncaught ReferenceError: __webpack_require__ is not defined
    at ./node_modules/@pmmmwh/react-refresh-webpack-plugin/overlay/components/Spacer.js (main.js:formatted:9401)
    at Object.options.factory (runtime.js:592)
    at __webpack_require__ (runtime.js:25)
    at fn (runtime.js:279)
    at ./node_modules/@pmmmwh/react-refresh-webpack-plugin/overlay/components/RuntimeErrorFooter.js (main.js:formatted:9125)
    at Object.options.factory (runtime.js:592)
    at __webpack_require__ (runtime.js:25)
    at fn (runtime.js:279)
    at ./node_modules/@pmmmwh/react-refresh-webpack-plugin/overlay/index.js (main.js:formatted:9527)
    at Object.options.factory (runtime.js:592)
```

I tried many times and also looked at the source code of `@pmmmwh/react-refresh-webpack-plugin` but there was no luck.

In babel.config.js I have already added `require.resolve('react-refresh/babel')` to the plugin list, and in the webpack config, I also added `new webpack.HotModuleReplacementPlugin()` and `new ReactRefreshPlugin({overlay: {sockIntegration: 'whm'}})`.

After debugging in the browser (with source map disabled) I arrived at these screenshots and found out that `__webpack_require__` is not defined when evaluating the internal module in `@pmmmwh/react-refresh-webpack-plugin` (module `Spacer.js`).

Is there any idea to help me continue the debug? Or am I missing any config?

Thank you very much in advance.

![image](https://user-images.githubusercontent.com/13043196/97088700-b2af2080-166d-11eb-90c9-3b3512c27b15.png)
![image](https://user-images.githubusercontent.com/13043196/97088736-ed18bd80-166d-11eb-9216-59b708906d69.png)
![image](https://user-images.githubusercontent.com/13043196/97088748-f73abc00-166d-11eb-9693-617740dcaf44.png)

**Comment by tranvansang** [comment]
![image](https://user-images.githubusercontent.com/13043196/97089144-d031b980-1670-11eb-9115-5c227f7dfc4f.png)


![image](https://user-images.githubusercontent.com/13043196/97089153-dfb10280-1670-11eb-96b1-26850dd2347c.png)


There were several modules registered successfully before `Spacer.js`. Actually, there were exactly two modules cannot be processed with `originalFactory.call`, the one is `Spacer.js` and the other is in the next screenshot.

![image](https://user-images.githubusercontent.com/13043196/97089182-20a91700-1671-11eb-96f6-56af22ab6003.png)

**Comment by tranvansang** [comment]
Look again at this screenshot, at line 590, __webpack_require__ is available (defined), but right after get into the `originalFactory.call`, it immediately becomes undefined.

![image](https://user-images.githubusercontent.com/13043196/97089311-d07e8480-1671-11eb-8a21-4fbd634b9768.png)

**Comment by tranvansang** [comment]
`@pmmmwh/react-refresh-webpack-plugin` manually replaces all `$RefreshReg$` to `__webpack_require__.$Refresh$.register`, which disables the runtime requirement calculation feature of webpack.

That is why `webpack` does not put `__webpack_require__` when initializing the `Spacer.js` module

**Comment by tranvansang** [comment]
PR made at https://github.com/pmmmwh/react-refresh-webpack-plugin/pull/233

**Comment by pmmmwh** [comment]
Hello - thank for the PR! Please let me understand the situation further - are you using Webpack 5?

**Comment by tranvansang** [comment]
@pmmmwh 

yes.  I am using webpack 5. The only installed version is 5.2.0

```
yarn why webpack
yarn why v1.22.4
[1/4] Why do we have the module "webpack"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "webpack@5.2.0"
info Has been hoisted to "webpack"
info This module exists because it's specified in "devDependencies".
info Disk size without dependencies: "5.75MB"
info Disk size with unique dependencies: "9.7MB"
info Disk size with transitive dependencies: "22.21MB"
info Number of shared dependencies: 51
Done in 1.08s.
```
