### ISSUE TITLE
Webpack 5 with browserslist config breaks react-refresh plugin

### ISSUE THREAD

**Issue by bentrynning** [pmmmwh/react-refresh-webpack-plugin#235]
***Versions***
"webpack": "5.1.3",
"webpack-cli": "4.1.0",
"webpack-dev-server": "3.11.0"
"@pmmmwh/react-refresh-webpack-plugin": "0.4.2"
"react-refresh": "0.9.0",

Since updateing to webpack 5 react-refresh plugin stops working. Looks like it has something to to with the target in webpack being set to `target: browserslist` when browserslist config is present in repository. [This is new in webpack 5](https://webpack.js.org/blog/2020-10-10-webpack-5-release/)

It can be reproduced by ether adding `.browserlistrc` or `browserslist to package.json` 

I could be that this is some issue with react-refresh, but ill try my luck here first :) 

Workaround is to explicit set `target: 'web'` when in development in webpack config. 
Test repo: https://github.com/bentrynning/react-refresh

**Comment by anajavi** [comment]
This seems to be related:
https://github.com/webpack/webpack-dev-server/issues/2758

**Comment by pmmmwh** [comment]
This is unfortunately a problem from upstream - no code in the plugin is specific for the web and would stay that way.

**Comment by pmmmwh** [comment]
This have been resolved in `webpack-dev-server@4.0.0-beta.0`
