### ISSUE TITLE
__react_refresh_error_overlay__

### ISSUE THREAD

**Issue by CaiqueR** [pmmmwh/react-refresh-webpack-plugin#237]
When I set in ```webpack.config.js``` that way:
```javascript
new ReactRefreshWebpackPlugin({
          overlay: {
            module: false,
            sockIntegration: 'whm',
          },
        })
```
I get this error
![image](https://user-images.githubusercontent.com/42003129/97462341-5bcf7280-191d-11eb-9eb5-f456dd325923.png)

I'm using webpack-hot-middleware and don't want overlay when there is an error on application.

There is one way to remove that:
![image](https://user-images.githubusercontent.com/42003129/97462818-e4e6a980-191d-11eb-847f-8f7af56ff8d2.png)

I don't want this iframe

**Comment by pmmmwh** [comment]
```js
new ReactRefreshWebpackPlugin({
  overlay: false,
})
```
