### ISSUE TITLE
Feature Request: add `--inline` like webpack-dev-server to support resource query sock port

### ISSUE THREAD

**Issue by tianjianchn** [pmmmwh/react-refresh-webpack-plugin#240]
webpack-dev-server use `--inline` mode by appending resourceQuery like `?http://localhost:3000` to the entry. 
see https://github.com/webpack/webpack-dev-server/blob/master/lib/utils/addEntries.js#L31-L37

In my cases, entry js file is not running from `<script>`, but with manual ajax downloading and eval-like. Then, `document.currentScript` will be null and react-refresh-webpack-plugin will use window.location as the socket destination.

Though I can manually change overlay.sockPort and other options. Just a thought for you.

**Comment by frehner** [comment]
I think this is related to #216

**Comment by pmmmwh** [comment]
> Though I can manually change overlay.sockPort and other options. 

That's intentional. There is no reliable way to automatically detect the source of the script when it called unless there's a `src` attribute on the tag, or it is running from `window.location`. We can never be certain that you're running on localhost, under a certain port.
