### ISSUE TITLE
Element animation does not rerun after fast refresh

### ISSUE THREAD

**Issue by lPaths** [pmmmwh/react-refresh-webpack-plugin#243]
Hi, I'm running into this issue when using react-spring with fast refresh feature on react-scripts v4.
Here's the react spring config
```js
const transitions = useTransition(history.location, ({ pathname }) => pathname, {
    from: { opacity: 0, transform: 'translate3d(40px, 0, 0)' },
    enter: { opacity: 1, transform: 'translate3d(0, 0, 0)' },
    leave: { opacity: 0, transform: 'translate3d(-40px, 0, 0)' },
  })
```
And here's the render

```js
<Suspense fallback={<></>}>
  {transitions.map(({ key, props }) => (
    <Switch key={key} location={history.location}>
      {routes.map(({ Component, ...rest }, index) => (
        <Route
          key={index}
          {...rest}
          render={(routeProps) => (
            <animated.div style={{ ...props, width: '100%' }}>
              <Component {...routeProps} />
            </animated.div>
          )}
        />
      ))}
    </Switch>
  ))}
</Suspense>
```

After fast refresh triggered, the element animation reset to `from` state and did not move to `enter` state. I don't know if this's `react-fast-refresh` or `react-spring` issue. Sorry if I've created issue in wrong repo. Thanks

**Comment by gaearon** [comment]
You'll need to file this in `react-spring`. Please provide them with this reference: https://reactnative.dev/docs/fast-refresh#fast-refresh-and-hooks. Feel free to cc me and I can respond to the questions on their repo.

**Comment by lPaths** [comment]
@gaearon Thanks for the fast reply, I'll create one later.
After searching around, I found a work around and I'll leave it here for someone who run into this like me, just add `// @refresh reset` to the component file you wish to remount every time a code change.
[ref](https://medium.com/javascript-in-plain-english/what-is-react-fast-refresh-f3d1e8401333)
