### ISSUE TITLE
ReactRefresh does not hot reload when webpack config has multiple entry 

### ISSUE THREAD

**Issue by vovakulikov** [pmmmwh/react-refresh-webpack-plugin#254]
In case when we have for instance entry like below

code example №1
 ```
entry: {
    vendor: ['react', 'react-dom'],
    app: path.resolve(__dirname, './src/index.tsx'),
  }
```

React refresh does full reload for the page. but if we change the entry above on this with one entry 

code example №2
`entry:  path.resolve(__dirname, './src/index.tsx')`

Everything works as we are expecting - we have a local hot update at changed component without a full page refresh

A simple example of this problem can see here [https://github.com/vovakulikov/sandbox]( https://github.com/vovakulikov/sandbox) - if add an entry to webpack.config.js like at code example №1 we will see a problem with a full refresh

**Comment by pmmmwh** [comment]
This should solve your problem :)

https://github.com/pmmmwh/react-refresh-webpack-plugin/blob/main/docs/TROUBLESHOOTING.md#component-not-updating-with-bundle-splitting-techniques
