### ISSUE TITLE
Electron forge + react-refresh/babel not working

### ISSUE THREAD

**Issue by ivancuric** [pmmmwh/react-refresh-webpack-plugin#263]
I'm using the recommended [typescript-without-babel config from the examples](https://github.com/pmmmwh/react-refresh-webpack-plugin/tree/main/examples/typescript-without-babel), modified to match the electron-forge [webpack+typescript template](https://github.com/electron-userland/electron-forge/tree/master/packages/template/typescript-webpack/tmpl):

```ts
  {
    test: /\.tsx?$/,
    exclude: /(node_modules|\.webpack)/,
    use: [
      isDevelopment && {
        loader: 'babel-loader',
        options: { plugins: ['react-refresh/babel'] },
      },
      {
        loader: 'ts-loader',
        options: { transpileOnly: true },
      },
    ].filter(Boolean),
  },
```

When I add the following:
```js
  isDevelopment && {
    loader: 'babel-loader',
    options: { plugins: ['react-refresh/babel'] },
  },
```

I get this error in Electron:
```
Unable to find Electron app at /Users/ivan/Dev/demo

Cannot find module '/Users/ivan/Dev/demo/.webpack/main'. Please verify that the package.json has a valid "main" entry
```

This is the webpack config structure I'm using:
https://gist.github.com/ivancuric/2b02360a2d6e0119b25238a0a991b8be

I'm not sure what this option even does since it seems to work even without it. Also, why it's called "typescript-without-babel", when it uses `react-refresh/babel`?

**Comment by pmmmwh** [comment]
Is it possible to create a full reproduction? Also this issue might be of interest #169?

This might be related:
https://github.com/electron-userland/electron-forge/issues/1113

> I'm not sure what this option even does since it seems to work even without it. Also, why it's called "typescript-without-babel", when it uses react-refresh/babel?

It basically demonstrates that we still need Babel for this particular purpose as there is no official support of transformers in TypeScript per se.

**Comment by ivancuric** [comment]
Could be, will get back to you with a repro. Thanks for finding that issue.

**Comment by heleg** [comment]
@ivancuric Do you have `babel-loader` installed?

**Comment by ivancuric** [comment]
Hey, found out what the issue was:
https://github.com/electron-userland/electron-forge/issues/1936

Seems that
