### ISSUE TITLE
Compatibility with webpack-dev-server@4

### ISSUE THREAD

**Issue by billyjanitsch** [pmmmwh/react-refresh-webpack-plugin#264]
Hi!

The first beta of `webpack-dev-server@4` was [recently released](https://github.com/webpack/webpack-dev-server/releases/tag/v4.0.0-beta.0). `@pmmmwh/react-refresh-webpack-plugin` (optionally) peer-depends on `webpack-dev-server@3`, so I wasn't expecting it to work right away, but I was curious to try. Currently, it seems that no errors are being reported and the dev server remains functional, but HMR / React Refresh don't seem to be working at all. Every component change, even in the simplest case, triggers a full page refresh.

**Comment by akphi** [comment]
@billyjanitsch please see this thread https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/126#issuecomment-736883538

It has to do with `webpack-dev-server` and we're currently waiting for https://github.com/webpack/webpack-dev-server/issues/2893

**Comment by frehner** [comment]
a note here: WDS dropped support for the `devServer.sock*` (host, port, etc.) fields in v4, but this plugin should already be able to handle that aspect of it. Hopefully 😃

**Comment by pmmmwh** [comment]
> a note here: WDS dropped support for the `devServer.sock*` (host, port, etc.) fields in v4, but this plugin should already be able to handle that aspect of it. Hopefully 😃

I think we don't support the `path` fallback from `sockPath` yet, but that is trivial to add.

**Comment by akphi** [comment]
@pmmmwh could we release this under `alpha` tag or so so we can try to setup projects with `wds@4` and `webpack@5`?

**Comment by pmmmwh** [comment]
It is now published under the `next` tag :)

I'm also hoping to finish all bug fixes and release `0.5.0` stable before new year's eve.
