### ISSUE TITLE
Clearing error boundaries on component refresh

### ISSUE THREAD

**Issue by arcanis** [pmmmwh/react-refresh-webpack-plugin#267]
Let's say I have the following code:

```ts
export class ErrorHandler extends React.Component<ErrorHandlerProps> {
  state: {
    error: Error | null,
  } = {
    error: null,
  };

  static getDerivedStateFromError(error: Error) {
    return {error};
  }

  render() {
    if (this.state.error === null) {
      return <>{this.props.children}</>;
    } else {
      return <PrettyError error={this.state.error}/>;
    }
  }
}
```

When an error triggers, all is fine, it gets catched by my error handler (I also use the trick described in https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/262#issuecomment-736011010, but that shouldn't have any effect). However, one problem arises: the `error` property from the component state isn't cleared when Refresh replaces a component, so there's never a chance to recover from the failing state.

Is there a public way to register to an event triggered when the plugin successfully replaces a component (*any* component is fine; it's just for a best-effort recovery after all)? Something like this:

```ts
componentDidMount() {
  globalThis.reactRefresh?.onRefresh(() => {
    this.setState({error: null});
  });
}
```

This way the caught error would be dropped, the code would retry, and hopefully succeed 🙂 Having this as a JS API like here would also be nice in that it would be opt-in, and would allow the developer to select which errors to reset.

**Comment by pmmmwh** [comment]
Maybe you can try the `/* @refresh reset */` directive within the file? This will force reset state on every refresh for that file only.

**Comment by arcanis** [comment]
That's perfect, thanks! I wasn't aware of this annotation 👍

**Comment by diegoriver** [comment]
> force reset state on every refresh for that file only.

How do you use it? Explain me please

**Comment by pmmmwh** [comment]
> How do you use it? Explain me please

Add this comment anywhere in your file:

```js
/* @refresh reset */
```
