### ISSUE TITLE
SockJS connection is duplicated with error overlay enabled

### ISSUE THREAD

**Issue by dmi-dmi-dmi** [pmmmwh/react-refresh-webpack-plugin#279]
I installed the plugin and Fast Refresh seems to work just fine.

However, I noticed that if I error overlay is enabled my browser:
* sends 2 consecutive HTTP GET requests to  `http://localhost/sockjs-node/info`
* opens 2 ws connections with  `ws://localhost/sockjs-node/id/randomId/websocket`

If I disable error overlay in plugin settings then duplication goes away.
I am curious if this is an intended behavior or not.

Versions: react@16.14.0, react-dom@16.14.0, react-refresh@0.9.0, webpack@4.44.2, webpack-dev-server@3.11.0

**Comment by pmmmwh** [comment]
This is intended and it is a limitation because the overlay reuses the socket connection of the integration, and in WDS's case we need to create a new socket client which means duplicated connection.
