### ISSUE TITLE
ErrorOverlayOptions require absolute paths

### ISSUE THREAD

**Issue by s-pic** [pmmmwh/react-refresh-webpack-plugin#280]
When specifying `ErrorOverlayOptions`, I would like to provide relative paths pointing to the node module, just like the docs state it for both options:
> Both ABSOLUTE and RELATIVE paths are acceptable, but it is recommended to use the FORMER.

Instantiating the plugin like so ..
```js
new ReactRefreshWebpackPlugin({
        overlay: {
            entry: '@pmmmwh/react-refresh-webpack-plugin/client/ErrorOverlayEntry',
            module: '@pmmmwh/react-refresh-webpack-plugin/overlay',
            sockIntegration: 'wds'
        },
    })
``` 
.. results in the following error

```
ValidationError: Invalid options object. React Refresh Plugin has been initialized using an options object that does not match the API schema.
   - options.overlay.module: The provided value "@pmmmwh/react-refresh-webpack-plugin/overlay" is not an absolute path!
```

The reason why I want to point to the module using a relative path is that I am snapshot-testing my webback config.
If the snapshots contain absolute paths, test results differ for different user file systems.

I wont be able to make a PR to fix this, but I could at least do a small one to update the README so that it is clear that only absolute paths are allowed.

**Comment by pmmmwh** [comment]
Actually this might be a bug in how we validate options (via Webpack's `schema-utils`), I'll have to take a look.
