### ISSUE TITLE
fast refresh doesn't work with browserlist if target is not specified in webpack config

### ISSUE THREAD

**Issue by FokinAleksandr** [pmmmwh/react-refresh-webpack-plugin#281]
I think that we should document in README.md that if we add .browserslist file then we have to specify target in webpack.
`target: process.env.NODE_ENV === "development" ? "web" : "browserslist".`
Otherwise fast refresh doesn't work

**Comment by pmmmwh** [comment]
This is a bug from upstream (i.e. webpack dev server), there's nothing we can do about it.

I'll add a note in the troubleshooting guide.
