### ISSUE TITLE
Plugin breaks on webpack 5 with multiple compilers

### ISSUE THREAD

**Issue by EvanPurkhiser** [pmmmwh/react-refresh-webpack-plugin#289]
The stacktrace is

```
$ /Users/evan/Coding/refresh-example/node_modules/.bin/webpack --config=webpack.config.js
internal/crypto/hash.js:82
    throw new ERR_INVALID_ARG_TYPE('data',
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Hash.update (internal/crypto/hash.js:82:11)
    at BulkUpdateDecorator.update (/Users/evan/Coding/refresh-example/node_modules/webpack/lib/util/createHash.js:49:14)
    at NormalModule.updateHash (/Users/evan/Coding/refresh-example/node_modules/webpack/lib/NormalModule.js:1062:8)
    at Compilation.createModuleHashes (/Users/evan/Coding/refresh-example/node_modules/webpack/lib/Compilation.js:2769:12)
    at /Users/evan/Coding/refresh-example/node_modules/webpack/lib/Compilation.js:2107:11
    at Hook.eval [as callAsync] (eval at create (/Users/evan/Coding/refresh-example/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/evan/Coding/refresh-example/node_modules/tapable/lib/Hook.js:18:14)
    at /Users/evan/Coding/refresh-example/node_modules/webpack/lib/Compilation.js:2067:36
    at Hook.eval [as callAsync] (eval at create (/Users/evan/Coding/refresh-example/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/evan/Coding/refresh-example/node_modules/tapable/lib/Hook.js:18:14) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

I've prepared a small reproduction repo here:

```
git clone git@gist.github.com:5510cedee2cfefac9bef8526a268da88.git react-refresh-webpack5-error
cd react-refresh-webpack5-error

# Webpack will build fine
yarn webpack --config webpack.config.no-refresh.js

# When using react-refresh plugin it fails
yarn webpack --config webpack.config.js
```

I'm obviously having this issue on a much larger repository, but this is a _very_ simple case, that afaict should work.

**Comment by EvanPurkhiser** [comment]
This appears to happen when `new webpack.HotModuleReplacementPlugin()` isn't included in the plugins.

I suspect that this raise is being caught somewhere in webpack:

https://github.com/pmmmwh/react-refresh-webpack-plugin/blob/b4b59dc182e47a075ea38f0fa3247ce64dc9fca4/lib/index.js#L276-L282

**Comment by EvanPurkhiser** [comment]
I fixed this by adding the `HotModuleReplacementPlugin` to both compiler configs.

I had actually originally removed them from _both_ of my compilers while switching to [`webpack-plugin-serve`](https://github.com/shellscape/webpack-plugin-serve), which _injects the `HotModuleReplacementPlugin` for you_. but you do _not_ declare the plugin in both compilers, since you would not want two servers running, so you must still include the _compiler that doesn't declare the server plugin_.

I'm going to leave this issue open though as it appears the helpful error message isn't bubbling it's way up.

**Comment by pmmmwh** [comment]
I guess there are two issues here, the first one being the error message not bubbling up correctly and the second being whether we should allow skipping the checks. For reference we already have the `forceEnable` flag, which maybe in this case should also kick into action to circumvent checks?

**Comment by elisherer** [comment]
Not completely related, but wanted to share that looking for that error and reaching that issue here, led me to understand I did not install `react-refresh`

**Comment by adidahiya** [comment]
I ran into this problem too. The README says:

> If you use webpack-dev-server or webpack-plugin-serve, you can set devServer.hot/devServer.hotOnly and hmr to true respectively, instead of adding the HMR plugin to your plugin list.

This appears not to be the case. I get the error posted by the OP here if I do _not_ include the HMR plugin in the plugin list.

**Comment by pmmmwh** [comment]
> This appears not to be the case. I get the error posted by the OP here if I do not include the HMR plugin in the plugin list.

What integration are you running?

I would assume you have the same issue as the OP - multiple compilers with only one server so we couldn't detect HMR in one of the compilers. We currently don't have a way for you to bypass that error but I'm thinking to add one in `0.5.0`.

**Comment by adidahiya** [comment]
@pmmmwh I am just using webpack-dev-server, here's my config. Removing this line caused the problem: https://github.com/palantir/blueprint/blob/9e305da9308b82b3a3c58234a9e9d313791d4d90/packages/webpack-build-scripts/webpack.config.base.js#L68

**Comment by sethomas** [comment]
I also got this error when using Cypress with `@cypress/webpack-preprocessor`, in the `webpackOptions` I was also including `@pmmmwh/react-refresh-webpack-plugin` on accident. Removing this from my cypress webpack config resolved the error.

**Comment by mrmos** [comment]
for me, this issue was resolved by switching from node v16 -> node v14

**Comment by arleyGuoLei** [comment]
this issue was resolved add plugin `new webpack.HotModuleReplacementPlugin()` to plugins.
