### ISSUE TITLE
How to close this error page

### ISSUE THREAD

**Issue by HEJIN2016** [pmmmwh/react-refresh-webpack-plugin#292]
![071820CF-9834-4347-8B8A-DC0DDC3DB7F1](https://user-images.githubusercontent.com/25821307/104396131-11a57700-5585-11eb-802e-25adde0e1119.png)
How to configure this page to not appear in case of error？

**Comment by pmmmwh** [comment]
Hi, you can disable the error overlay integration by setting `overlay: false`.
