### ISSUE TITLE
`const` injected in runtime code

### ISSUE THREAD

**Issue by Donov4n** [pmmmwh/react-refresh-webpack-plugin#297]
Thanks for this super cool project!

In [`RefreshModule.runtime.js`](https://github.com/pmmmwh/react-refresh-webpack-plugin/blob/main/loader/RefreshModule.runtime.js#L14), `const` are injected in runtime code and will not be transpiled (since it's a loader injected code).

This is critical in old browser that [do not support `const`](https://caniuse.com/const) in strict mode for example.  

Elsewhere in the codebase i've seen a [`supportsConst`](https://github.com/pmmmwh/react-refresh-webpack-plugin/blob/89ccca3a528a68f06f777daef09a28a5614e5525/lib/runtime/RefreshRuntimeModule.js#L21) method that seems to handle this specific case, maybe the code injected by `RefreshModule.runtime.js`should do the same.

**Comment by pmmmwh** [comment]
Hi, that is actually done deliberately on purpose. All modern browser since 2016 have working implementations of `const` and `let` (and also IE11 supports it). Are you facing specific issues where that would break your code?

**Comment by Donov4n** [comment]
We are trying to replace RHL with react-refresh but we need to support old browser (like Chrome 30-40 f.e) but these `const` are breaking our code with errors like "SyntaxError: Use of const in strict mode".

It seems sad to me to not support all the projects that need to take into account old browsers (not only IE) just because of these few line 😞  but if it's done deliberately, maybe this should be explicitly said in the README / FAQ (?).

**Comment by pmmmwh** [comment]
> We are trying to replace RHL with react-refresh but we need to support old browsers (like Chrome 30-40 f.e) but these `const` are breaking our code with errors like "SyntaxError: Use of const in strict mode".
> 
> 
> 
> It seems sad to me to not support all the projects that need to take into account old browsers (not only IE) just because of these few line 😞  but if it's done deliberately, maybe this should be explicitly said in the README / FAQ (?).

I understand the frustration - I'll look into it, in particular I don't think we rely on any scoping behaviours from `const` and `let`.

**Comment by TrySound** [comment]
Just wondering why do you support chrome 30-40? They did not get security updates for 5 or more years already.

**Comment by Donov4n** [comment]
> Just wondering why do you support chrome 30-40? They did not get security updates for 5 or more years already.
> Is it even possible to test them?

Thiz bug can be seen in all browsers versions that don’t support const / let in strict mode, not only Chrome 30-40.

For our case, we support Chrome since v30 because the platforms (old tv) where our project is run can’t update to newer version of chrome.

**Comment by pmmmwh** [comment]
To be honest, the pragmatist in me definitely does not want to support these browsers, but given React supports browsers down to IE9 I'm not sure about how compelling our argument on this case would be.

However, given that Webpack 5 now does have APIs to selectively target specific environments and we already lean on it with the crucial runtime init code, maybe it makes sense to actually use that more to ensure not only compat with older browsers but also pure ESM environments (#294).

It does make the template code more difficult to maintain and lint because now it is not really pure JavaScript.

**Comment by Donov4n** [comment]
Like said, it’s not only for Chrome 30-40, this bug is viewable on iOS 9, which imply supporting (or not) iPad 2, iPhone 4S ...
