### ISSUE TITLE
HMR succeeds, but React fails to actually update the component until a state change

### ISSUE THREAD

**Issue by frehner** [pmmmwh/react-refresh-webpack-plugin#299]
Here's a link to a repo for reproduction https://github.com/frehner/react-fast-refresh-externals/tree/systemjs-fast-refresh

Follow the instructions in the readme. Once you have the app running, make a change to `app2/other.js` (e.g. change `aaa` to `bbb`). Note that the browser console says that everything worked, but React itself apparently fails to rerender or something and the component isn't updated. You can, however, force an update to happen by clicking the button to update state, and _that_ will correctly apply the HMR-updated code.

Video (hopefully this works):

https://user-images.githubusercontent.com/3054066/105916706-9add9480-5fee-11eb-99cd-80ac0b7598e0.mov

In debugging, it appears to me that this plugin actually does everything that it should - it correctly recognizes an HMR update and does call [`Refresh.performReactRefresh();`](https://github.com/pmmmwh/react-refresh-webpack-plugin/blob/main/lib/runtime/RefreshUtils.js#L62) when it should. If that's correct, this could potentially be a bug in `react-refresh/runtime` itself and not this plugin. 

Notes: Using webpack 5, webpack-dev-server 4-beta, and react-refresh-webpack-plugin 0.5-beta

**Comment by frehner** [comment]
I think I have confirmed through debugging that this is actually a bug in react-refresh itself. I'll try to write something up and open an issue in the react repo for that

**Comment by frehner** [comment]
Actually, with more digging, it turns out that the problem is that there are more than one instance of `react-refresh` in a MFE setup. 

So we need to ensure that there's only one instance of it by sharing it in the import-map -- something that's a little difficult because `react-refresh` doesn't have a UMD build at the moment, but still something that can be worked around with a hack + JSPM CDN for now.

See this repo for an example:

https://github.com/frehner/react-fast-refresh-externals/tree/systemjs-fast-refresh-hack

closing as fixed. 🙂

**Comment by ryanrogalski** [comment]
I just ran into a similar issue after upgrading to webpack 5.19.0.

The error is occuring on this line:

```
self["webpackHotUpdatemyApp"] = function(chunkId, moreModules, runtime) {
/******/ 			for(var moduleId in moreModules) {
/******/ 				if(__webpack_require__.o(moreModules, moduleId)) {
/******/ 					currentUpdate[moduleId] = moreModules[moduleId]; <--- error on this line
/******/ 					if(currentUpdatedModulesList) currentUpdatedModulesList.push(moduleId);
/******/ 				}
/******/ 			}
```
<img width="1281" alt="Screen Shot 2021-02-01 at 12 48 08 PM" src="https://user-images.githubusercontent.com/1111881/106516362-c992b980-648b-11eb-9c22-6c10305b72a9.png">
<img width="709" alt="Screen Shot 2021-02-01 at 12 47 51 PM" src="https://user-images.githubusercontent.com/1111881/106516355-c8618c80-648b-11eb-833d-58e803e56ebc.png">
<img width="727" alt="Screen Shot 2021-02-01 at 12 48 01 PM" src="https://user-images.githubusercontent.com/1111881/106516360-c8fa2300-648b-11eb-8f37-84560e51ca5f.png">

**Comment by pmmmwh** [comment]
> I just ran into a similar issue after upgrading to webpack 5.19.0. Thought I'd post my results in case it helps.
> 
> The error is occurring on this line:
> 
> ```
> self["webpackHotUpdatemyApp"] = function(chunkId, moreModules, runtime) {
> /******/ 			for(var moduleId in moreModules) {
> /******/ 				if(__webpack_require__.o(moreModules, moduleId)) {
> /******/ 					currentUpdate[moduleId] = moreModules[moduleId]; <--- error on this line
> /******/ 					if(currentUpdatedModulesList) currentUpdatedModulesList.push(moduleId);
> /******/ 				}
> /******/ 			}
> ```
> 
> <img alt="Screen Shot 2021-02-01 at 12 47 51 PM" width="709" src="https://user-images.githubusercontent.com/1111881/106516355-c8618c80-648b-11eb-833d-58e803e56ebc.png">
> 
> <img alt="Screen Shot 2021-02-01 at 12 48 01 PM" width="727" src="https://user-images.githubusercontent.com/1111881/106516360-c8fa2300-648b-11eb-8f37-84560e51ca5f.png">
> 
> <img alt="Screen Shot 2021-02-01 at 12 48 08 PM" width="1281" src="https://user-images.githubusercontent.com/1111881/106516362-c992b980-648b-11eb-9c22-6c10305b72a9.png">

Your issue seems like HMR straight up did not work rather than this plugin not working?

**Comment by ryanrogalski** [comment]
@pmmmwh yea, ended up going back to webpack 4 for the time being
