### ISSUE TITLE
Fast refresh not accept any change in any place, require full page refresh.

### ISSUE THREAD

**Issue by Akiyamka** [pmmmwh/react-refresh-webpack-plugin#300]
I check every item in [docs](https://github.com/pmmmwh/react-refresh-webpack-plugin/blob/main/docs/TROUBLESHOOTING.md#edits-always-lead-to-full-reload)

* [x] Un-named/non-pascal-case-named components - not used
* [x] Chain of files leading to root with none containing React-related content only - not used
* [x] export * from 'namespace' - not used

What wrong with my code?
https://github.com/Akiyamka/fast-refresh-bug

**Comment by pmmmwh** [comment]
I don't see this plugin being used in the Webpack configuration? Am I missing something?

**Comment by Akiyamka** [comment]
@pmmmwh oh sorry, problem really was in it, I was sure that I added it!
Another check in "Edits always lead to full reload" - "you just forgot to add plugin" :rofl:
