### ISSUE TITLE
$RefreshReg$ is not defined

### ISSUE THREAD

**Issue by ariovistus** [pmmmwh/react-refresh-webpack-plugin#302]
Hello

I set up a project with react-refresh last week and I got it to work, but then a few days later it magically stopped working, and I have not been able to figure out what I changed (if anything). It errors out in the browser with `$RefreshReg$ is not defined`, and I am reasonably certain when it was working that that symbol was not in the build artifact, though I am a bit past trusting my sanity at this point.

Anyways, I reduced the project a bunch: https://github.com/ariovistus/test-react/, can anyone see what I might be doing wrong?

**Comment by pmmmwh** [comment]
Hi, have you manage to resolve the issue?

**Comment by ariovistus** [comment]
The issue resolved itself in my original project through no action of my own. I confirmed that `$RefreshReg$` is not in the build asset there. I still do not know how I got it into that state, but the above test project outputs `$RefreshReg$` on both a windows and a linux box of mine. It may still be valuable for you to investigate if it is a race condition or silent failure in the webpack transformations, but I am not qualified to say it is.

**Comment by g3tr1ght** [comment]
It happens when NODE_ENV is set to production, via .env file or something else sets it during the build.

**Comment by hnrchrdl** [comment]
I had the same issue after fiddling around with the plugin. Even after reverting all the changes, the error was still present. I was able to resolve it by clearing the babel cache.

**Comment by 4461563** [comment]
> I had the same issue after fiddling around with the plugin. Even after reverting all the changes, the error was still present. I was able to resolve it by clearing the babel cache.

Have you solved it? Can you describe it in detail

**Comment by 4461563** [comment]
Well, thank you. I've solved it. I've deleted the APK package generated before. It may really be a cache problem



---Original---
From: ***@***.***&gt;
Date: Fri, Jul 8, 2022 22:11 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [pmmmwh/react-refresh-webpack-plugin] $RefreshReg$ is not defined(#302)




 
Try removing node_modules folder first and re-installing dependencies.
 If that does not help, try to see if babel uses a folder for caching, and remove that as well.
