### ISSUE TITLE
How to work with webpack-hot-client ?

### ISSUE THREAD

**Issue by stkevintan** [pmmmwh/react-refresh-webpack-plugin#309]
Hi, guys, very appreciate for the great work!

but, I am using a standalone koa 2.x dev server with `koa-webpack`  which unfortunately choose `webpack-hot-client` instead of `webpack-hot-middleware` as the HMR implementation, but currently we don't have any references or docs about how to configure it with `webpack-hot-client`.
so is it possible ? or  is there any plan to work with it ?

Thanks

**Comment by pmmmwh** [comment]
Hi, sorry for the late reply. Currently, the error overlay integration will not work with `webpack-hot-client`, nor do I intend to work with it as it has not been updated since fall 2018.

The core of the plugin for React Refresh will still work though.

**Comment by stkevintan** [comment]
Hi, Yes, it's doesn't matter, since I don't need the error-overlay. thanks!
