### ISSUE TITLE
Incompatible with chrome 53

### ISSUE THREAD

**Issue by fwh1990** [pmmmwh/react-refresh-webpack-plugin#31]
```
Uncaught ReferenceError: getModuleExports is not defined          utils.js:169
```

```
Uncaught ReferenceError: handleCompileSuccess is not defined      ErrorOverlayEntry.js:67
```

Work fine at latest chrome version

**Comment by fwh1990** [comment]
I find out that errors will only show when `devtool` includes literal `eval`
* eval
* cheap-eval-source-map
* ...

**Comment by pmmmwh** [comment]
I wasn't able to get my hands on any versions of chrome older than 2018, and I cannot reproduce this issue in any versions that I've tried.

I'll close this for now - I suspect it have something to do with the use of `Object.freeze` in `module.exports` and source map parsing failing to handle the immutable object.
