### ISSUE TITLE
Is React DevTools mandatory ?

### ISSUE THREAD

**Issue by pgn-vole** [pmmmwh/react-refresh-webpack-plugin#315]
Hello, it seems that the plugin cannot work without the React DevTools extension.
I digged up into the code and it does seems very much related to this area:
https://github.com/facebook/react/blob/master/packages/react-refresh/src/ReactFreshRuntime.js#L436-L446

It seems like a fallback mechanism is written to handle the the case where React Devtool is not installed, however in my setup this fallback is not working.

Could you please clarify wether React Devtool extension is mandatory or wether, in my setup somehow the fallback mechanism doesnt work.

**Comment by pmmmwh** [comment]
No. The React DevTools extension AFAIK is not mandatory.

I can't provide more help without more information on your setup, but the fallback not working is most likely because React executed before the fallback is set up. (i.e. React Refresh needs to run before React/React-DOM).

**Comment by gaearon** [comment]
@pgn-vole Like the comment says, the problem is likely that you're importing `react-dom` earlier than `react-refresh` runtime is imported.

**Comment by pgn-vole** [comment]
Sorry for the late reply.
@gaearon you are right, the setup that we are using here is based on React/ReactDOM 16.14 UMD builds, therefore React and ReactDOM are loaded independently and BEFORE any applications bundles (containing the HMR + Fast Refresh code).

@pmmmwh you are mentioned un-released fixes - could you point to it? And even beter, is there an ETA for the release?

**Comment by pmmmwh** [comment]
The unreleased fixes are in the facebook/react repo - I don't think I would be able to provide an ETA unfortunately.

**Comment by pgn-vole** [comment]
@pmmmwh I just updated to `react-refresh@0.1.0` and `react-refresh-webpack-plugin@0.5.0-beta.3`, but it doesn't seem to have solve that issue. Is there a dependency on a React update too for the fix to work?

**Comment by pmmmwh** [comment]
You need to ensure on your side that `react-refresh/runtime` is loaded before any React code runs.
This can be done by also externalising `react-refresh` with a UMD build.
