### ISSUE TITLE
[BUG] breaks when a module exports a Proxy that can throw errors

### ISSUE THREAD

**Issue by MichaelBelousov** [pmmmwh/react-refresh-webpack-plugin#316]
It is possible for modules to export objects that can throw on property access, (e.g. proxies). This seems to cause runtime errors when the plugin is investigating exported objects for whether they are a component.

Here is an [example MVR](https://github.com/MichaelBelousov/bad-proxy-hot-reload-mvr).

And the resulting runtime error:

```js
Uncaught Error: cannot use object
    get http://localhost:3000/static/js/main.chunk.js:187
    isLikelyComponentType http://localhost:3000/static/js/vendors~main.chunk.js:31145
    registerExportsForReactRefresh http://localhost:3000/static/js/vendors~main.chunk.js:201
    js http://localhost:3000/static/js/main.chunk.js:267
    js http://localhost:3000/static/js/main.chunk.js:339
    __webpack_require__ http://localhost:3000/static/js/bundle.js:857
    fn http://localhost:3000/static/js/bundle.js:151
    js http://localhost:3000/static/js/main.chunk.js:450
    js http://localhost:3000/static/js/main.chunk.js:567
    __webpack_require__ http://localhost:3000/static/js/bundle.js:857
    fn http://localhost:3000/static/js/bundle.js:151
    1 http://localhost:3000/static/js/main.chunk.js:703
    __webpack_require__ http://localhost:3000/static/js/bundle.js:857
    checkDeferredModules http://localhost:3000/static/js/bundle.js:46
    webpackJsonpCallback http://localhost:3000/static/js/bundle.js:33
    <anonymous> http://localhost:3000/static/js/main.chunk.js:1
 ```

A solution would be to try/catch property access of exports under investigation. Or you could do some special checking for proxies (I don't recall if/how that's possible in JS). Or ignore it and force consumers to never export proxies that have a possible error condition on access. I know this cropped up on a codebase I've worked on which is where I found this.

I would be willing to contribute a PR but if someone can do it faster than me (might take me a couple of weeks) please do.

**Comment by pmmmwh** [comment]
I think this is fixed in `HEAD` in the React repo, but never released.

@gaearon is it possible to cut a `0.10.0` release for React Refresh?
