### ISSUE TITLE
refresh not working with react-refresh-typescript

### ISSUE THREAD

**Issue by boojum** [pmmmwh/react-refresh-webpack-plugin#317]
Minimal repo can be found [here](https://gitlab.com/b00jum/react-ts).

Making any change to the component results in `GET http://localhost:8080/_-ceb3f47-main-wps-hmr.js net::ERR_ABORTED 404 (Not Found)`.

To reproduce:
1. `git clone https://gitlab.com/b00jum/react-ts`
2. `cd react-ts`
3. `npm i -D --legacy-peer-deps`
4. `npm run dev`
5. Make a change to `src/app.tsx`. Refresh will kick-in but in your browser dev-tools console you will see: 
```GET http://localhost:8080/_-ceb3f47-main-wps-hmr.js net::ERR_ABORTED 404 (Not Found)```

If I'm not mistaken, the wps file should be called `main-ceb3f47-main-wps-hmr.js`, not `_-ceb3f47-main-wps-hmr.js`. I would appreciate help in debugging this issue.

**Comment by pmmmwh** [comment]
CC @Jack-Works

**Comment by Jack-Works** [comment]
Files should not start with undeeslash cause it is reserved in chrome extension. Maybe there's some configuration wrong. I'll check that later

**Comment by Jack-Works** [comment]
Oh wait this is a normal website right?... Sorry I just wake up yet

**Comment by Jack-Works** [comment]
So I'm confident this is not a bug in my transformers cause I don't handle any filename in it. I can try to help when I'm free

**Comment by Jack-Works** [comment]
I can't connect to HMR server. Is it not working with Windows?

> WebSocket connection to 'ws://[::]:8080/wps' failed: Error during WebSocket handshake: Unexpected response code: 404

**Comment by boojum** [comment]
@Jack-Works 
Sadly, I don't have a Windows machine to try it on.

**Comment by pmmmwh** [comment]
Let me try running it locally ...

**Comment by boojum** [comment]
Apologies for the silence, life got in the way. Either way, the issue is not with `react-refresh-webpack-plugin` nor `react-refresh-typescript` but with `webpack` or `html-webpack-plugin`. The whole setup works absolutely fine with `webpack 5.11` and `html-webpack-plugin 4.5`. The issue appears after updating to the latest versions of these two plugins, and affects ts and js.

I'll try to narrow it down a little more.

**Comment by pmmmwh** [comment]
Fix shipped upstream in `webpack-plugin-serve@1.4.0`.
