### ISSUE TITLE
[0.5.0-beta.1] __webpack_require__.$Refresh$.signature is not a function

### ISSUE THREAD

**Issue by hailwood** [pmmmwh/react-refresh-webpack-plugin#325]
**Version:** 
@pmmmwh/react-refresh-webpack-plugin:0.5.0-beta.1 
react-refresh:0.9.0
webpack: 5.21.2
react: 17.0.1

Issue does not occur with @pmmmwh/react-refresh-webpack-plugin:0.5.0-beta.0

**Issue:**
When using a render prop with a useEffect in the render prop `__webpack_require__.$Refresh$.signature is not a function` is thrown.

**Reproduction:**

```jsx
function FunctionRenderer({children}) {
  return children();
}

function TestComponent() {
  return (
    <FunctionRenderer>
      {() => {
        useEffect(() => {}, []);

        return <span>Hello</span>;
      }}
    </FunctionRenderer>
  );
}
```

**Other Info:**
If the render prop is declared externally, this issue does not occur

```jsx
const externalRenderProp = () => {
  useEffect(() => {}, []);

  return <span>Hello</span>;
};

function FunctionRenderer({children}) {
  return children();
}

function TestComponent() {
  return (
    <FunctionRenderer>
      {externalRenderProp}
    </FunctionRenderer>
  );
}
```

If the render prop does not contain a useEffect, this issue does not occur

```diff
function FunctionRenderer({children}) {
  return children();
}

function TestComponent() {
  return (
    <FunctionRenderer>
      {() => {
-        useEffect(() => {}, []);

        return <span>Hello</span>;
      }}
    </FunctionRenderer>
  );
}
```

If the useEffect is not in the render prop this issue does not occur

```diff
function FunctionRenderer({children}) {
  return children();
}

function TestComponent() {
+
+  useEffect(() => {}, []);
+
  return (
    <FunctionRenderer>
      {() => {
-        useEffect(() => {}, []);

        return <span>Hello</span>;
      }}
    </FunctionRenderer>
  );
}
```

**Comment by phaistonian** [comment]
Having the same issue, but with a different pattern:

```js
// this triggers the error
run({
  flag: true,
  onChange: async (something) => {
    await doThis();
  },
});

// this works
run({
  flag: true,
  async onChange(something) {
    await doThis();
  },
});
```

**Comment by gaearon** [comment]
Note you shouldn’t be putting effects (or any Hooks) into render props anyway.

**Comment by pmmmwh** [comment]
> Having the same issue, but with a different pattern

Can you provide a bit more onto how is `run` being used?

**Comment by phaistonian** [comment]
@pmmmwh Here's a part of [the code](https://gist.github.com/phaistonian/dfe2f4aa1f536aa868849a5cc7452f36#file-neabry-js-L23-L24).

This is not triggered inside a react component, btw*

* though `initNearbyPicker` eventually renders one.

**Comment by phaistonian** [comment]
@pmmmwh Thak you.  ETA for a release with this fix?

**Comment by pmmmwh** [comment]
`0.5.0-beta.4` have been released.
