### ISSUE TITLE
optimization.spliChunks broke fast refresh without any error

### ISSUE THREAD

**Issue by Akiyamka** [pmmmwh/react-refresh-webpack-plugin#329]
Please add it in troubleshooting: splitChunks must be disabled in development mode.
Flowing setting broke fast refresh hot reload:

```js
splitChunks: {
  cacheGroups: {
     vendor: {
       test: /[\\/]node_modules[\\/]/,
       minChunks: 1,
       name: "vendors",
       chunks: "all",
     },
  },
}
 ```
 full config
 https://gist.github.com/Akiyamka/95be5723e29b384c893598cecf3b823a

**Comment by pmmmwh** [comment]
Hi - did you manage to resolve it?
