### ISSUE TITLE
Does not properly trigger a full refresh upon refactoring a component used in the entry module

### ISSUE THREAD

**Issue by Zaid-Ajaj** [pmmmwh/react-refresh-webpack-plugin#330]
I have a weird issue with react-refresh when renaming components and fixing compile issues up to the entry module, react-refresh does not trigger a full refresh and the page is instead left with a  runtime error that isn't catched by the error boundary. I have to manually refresh the page to get it working

Here is a screen recording of the situation:

https://user-images.githubusercontent.com/13316248/111555505-d728a800-8788-11eb-80c4-55dfd2d88566.mp4

I've tested that the issue occurs both on latest v0.4.3 and in v0.5.1-beta

Here [https://github.com/Zaid-Ajaj/fast-refresh-bug-reproduction](https://github.com/Zaid-Ajaj/fast-refresh-bug-reproduction) you can find a repro of the bug. 

Using webpack 5 in there

**Comment by Zaid-Ajaj** [comment]
It is worth noting the problem does _not_ occur when the refactored component is in a module other than the entry module:

Here I have a structure where
 - Main.fs.js is the entry module
    - Component.js
      - App.fs.js

Changing App.fs.js and Component.js triggers a partial rerender and works as expected

![modules](https://user-images.githubusercontent.com/13316248/111560960-ed883100-8793-11eb-8b94-8115c982b9dc.png)

**Comment by Zaid-Ajaj** [comment]
Confirmed that the error does not occur in previous major webpack version
```
"webpack": "^4.44.2",
"webpack-cli": "^3.3.12",
```

**Comment by Zaid-Ajaj** [comment]
Hi, please let me know if you need me to provide more debug information about this issue. Maybe I missed something above.

**Comment by pmmmwh** [comment]
Sorry - I haven't had time to look at this, maybe this weekend.

**Comment by Zaid-Ajaj** [comment]
No worries or hurry at all, just let me know if you need anything on my end of things. Currently I reverted back to webpack 4 and friends which still works just fine

**Comment by xuya227939** [comment]
@pmmmwh Hi，I had similar problem，configure multiple entries, hot update failed，what is the current solution? I use `webpack：4.41.2`，`webpack-dev-server: 3.10.1`，`@pmmmwh/react-refresh-webpack-plugin：0.4.3`.

**Comment by pmmmwh** [comment]
> @pmmmwh Hi，I had similar problem，configure multiple entries, hot update failed，what is the current solution? I use `webpack：4.41.2`，`webpack-dev-server: 3.10.1`，`@pmmmwh/react-refresh-webpack-plugin：0.4.3`.

You need newer Webpack versions.
https://github.com/pmmmwh/react-refresh-webpack-plugin#prerequisites

**Comment by pmmmwh** [comment]
@Zaid-Ajaj I did some initial testing and it seems very weird because the newly consumed code doesn't seem to be re-executed. I'll dig deeper later this week and see if I can identify anything, could be a Webpack/WDS bug as well ...

**Comment by pmmmwh** [comment]
It has been a long time to debug this, but I believe with the latest versions of this plugin/react refresh/Webpack/WDS the reproduction works as expected.

https://github.com/pmmmwh/fast-refresh-bug-reproduction
