### ISSUE TITLE
Fast-Refresh not working due to React instance in window object

### ISSUE THREAD

**Issue by UltraTempest** [pmmmwh/react-refresh-webpack-plugin#335]
The react & react-dom instances for our web app are found in the window object under:
window.shared.react[16] & window.shared.reactDom[16] respectively.

We have configured this in our Webpack build using:
```
  externals: {
    react: 'root shared.react[16]',
    'react-dom': 'root shared.reactDom[16]',
  },
```

React-refresh does not hot reload in this case, if we remove the externals the hot reloading works.
Do you know if there is a way to enable hot-reloading/fast-refreshing when the react instance is in the window object?
Thanks

**Comment by pmmmwh** [comment]
Hi, in this case you should also externalise `react-refresh/runtime`. The runtime have to run before **ANY** React code.

**Comment by UltraTempest** [comment]
Hmmm so you mean adding the instance for react-refresh/runtime to the window object? Like the react instance above?

**Comment by pmmmwh** [comment]
Yes. The general suggestion when you externalize/chunk React you have to make sure `react-refresh/runtime` goes with it.

**Comment by pmmmwh** [comment]
This issue is basically a derived version of [this](https://github.com/pmmmwh/react-refresh-webpack-plugin/blob/main/docs/TROUBLESHOOTING.md#component-not-updating-with-bundle-splitting-techniques)
