### ISSUE TITLE
Official support for webpack 5

### ISSUE THREAD

**Issue by rocalvo-meli** [pmmmwh/react-refresh-webpack-plugin#336]
Hi!

Is there an estimated release date for the stable version 1.0.0 with webpack 5 support?

Thank yuo! 😄

**Comment by pmmmwh** [comment]
Support for Webpack 5 is already official since `0.4.x`.

As for an estimated date for a `1.x` release, I don't have a concrete date yet. However - the software in its current state is considered quite stable. It's just that the internals of this plugin are constantly improving.

**Comment by rocalvo-meli** [comment]
Thank you for yuor quick response ! :)
