### ISSUE TITLE
Update to react-refresh@0.10.0

### ISSUE THREAD

**Issue by gaearon** [pmmmwh/react-refresh-webpack-plugin#340]
That should fix https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/266.

**Comment by njleonzhang** [comment]
when will this fix be released?

**Comment by pmmmwh** [comment]
It's already in the latest 0.5.0 beta. If you want something stable, maybe in 1-2 weeks as I'm wrapping up final bug fixes and updates to support WDS v4.
