### ISSUE TITLE
lose react-refresh runtime

### ISSUE THREAD

**Issue by fatWill** [pmmmwh/react-refresh-webpack-plugin#341]
first change will get this:

![image](https://user-images.githubusercontent.com/20520334/113306751-fef63f00-9336-11eb-9fea-70b978415bed.png)

and i find my runtime chunk get this:

![image](https://user-images.githubusercontent.com/20520334/113307111-5f857c00-9337-11eb-9e0d-f3bf75da82e1.png)

![image](https://user-images.githubusercontent.com/20520334/113306975-37961880-9337-11eb-81d5-a5949a50528d.png)

before change:
![image](https://user-images.githubusercontent.com/20520334/113308554-dff8ac80-9338-11eb-9d27-f255af02137b.png)

![image](https://user-images.githubusercontent.com/20520334/113307213-7b891d80-9337-11eb-9134-87a6ac50aea3.png)

why lose the runtime module?

**Comment by fatWill** [comment]
env:
**webpack: 5.28.0**
**weback-dev-server: 4.0.0-beta.1**

this is my config:

![image](https://user-images.githubusercontent.com/20520334/113307506-c6a33080-9337-11eb-8521-e4c9755f0c61.png)

![image](https://user-images.githubusercontent.com/20520334/113307524-ce62d500-9337-11eb-9ac5-8d02e426eab9.png)

**Comment by pmmmwh** [comment]
Hi, can I have a bit more information about your Webpack configuration? Are you doing any chunking or externalizing? What version of React/React-Refresh/This Plugin are you on? Are you using strict ESM?

**Comment by fatWill** [comment]
yeah, i set the splitChunks

![image](https://user-images.githubusercontent.com/20520334/113312172-97db8900-933c-11eb-92ee-dc82b5254389.png)

**react and react-dom version: 16.13.1**

**Comment by fatWill** [comment]
no strict esm, otherwise the first build will fail

**Comment by pmmmwh** [comment]
You need to split the `react-refresh/runtime` alongside the react dependencies

**Comment by fatWill** [comment]
![image](https://user-images.githubusercontent.com/20520334/113372353-1404b980-939b-11eb-9f4c-205b2a9e41fa.png)

![image](https://user-images.githubusercontent.com/20520334/113372520-778ee700-939b-11eb-8092-16fb1f549fb5.png)


@pmmmwh also not work

**Comment by pmmmwh** [comment]
I don't understand, what is not working now? Any errors, warnings, whatever? The screenshot you've showed seems like the runtime is there?

Also - I would prefer going with the approach of having react, react-dom and react-refresh in the same chunk.

**Comment by fatWill** [comment]
After I updated the code, I lost react-refresh in webpack-runtime.

For the time being, I still don’t understand why

**Comment by pmmmwh** [comment]
Are you running multiple entry points? Can you try this?

```js
module.exports = {
  optimization: {
    runtimeChunk: 'single',
  },
};
```

**Comment by fatWill** [comment]
> Can you try this?

I tried, still the same error

Mainly, react-refresh will be lost in webpack-runtime after the update

**Comment by pmmmwh** [comment]
If you have time can you try testing the branch in #372?

```sh
yarn add https://github.com/pmmmwh/react-refresh-webpack-plugin.git#fix/runtime-requirements
```
