### ISSUE TITLE
npm ERR! Cannot destructure property 'name' of 'node' as it is null.

### ISSUE THREAD

**Issue by manu1222** [pmmmwh/react-refresh-webpack-plugin#345]
```
npm install -D @pmmmwh/react-refresh-webpack-plugin react-refresh
npm ERR! code ERESOLVE
npm ERR! Cannot destructure property 'name' of 'node' as it is null.
```

Webpack: 5.20.0
webpack-cli: 4.5.0
React: 17.0.2

**Comment by pmmmwh** [comment]
Hi, this is an issue of `npm` and not us. Please try upgrading to the latest version of `npm@7` or downgrade to `npm@6`.

You might also see peer dependency errors, which you can resolve by doing `npm install --legacy-peer-deps`.
