### ISSUE TITLE
Webpack 5: plugin don't work if no entry specified in webpack config

### ISSUE THREAD

**Issue by farwayer** [pmmmwh/react-refresh-webpack-plugin#346]
Reproduce demo for this and #347 
https://github.com/farwayer/rrwp-issues

**Comment by farwayer** [comment]
[Entry should be updated](https://github.com/pmmmwh/react-refresh-webpack-plugin/blob/652a31a15396398f01b765d51108d1b0b1504282/lib/index.js#L84) inside [`environment` hook](https://webpack.js.org/api/compiler-hooks/#environment) after all defaults were applied

**Comment by pmmmwh** [comment]
This is an artificial constraint for now. Updating the `entry` object anywhere later than the plugin `apply` phase is potentially too late as we need to ensure the changes propagate to any other code/plugins that observes the entry via hooks.

For Webpack 5 the way to go is #319 - but I currently do not value this as a high priority.

**Comment by tfoxy** [comment]
Hi @pmmmwh, would it be good to have the entry specified in the readme examples? With a comment explaining that entry is required for webpack 5.

I can do the PR if you want. We can then remove it when #319 is merged.

**Comment by pmmmwh** [comment]
Feel free to PR. You can either add it in README or TROUBLESHOOTING/
