### ISSUE TITLE
`connection.onClose` is not a function

### ISSUE THREAD

**Issue by garrettmaring** [pmmmwh/react-refresh-webpack-plugin#35]
In `createSocket`, I'm seeing a `connection.onClose` is not a function error. In the `SocketClient` conditional, it is not using __webpack_dev_server_client__. It is use SockJS.

**Comment by pmmmwh** [comment]
Mind adding a bit more context - Webpack version, SockJS version, WDS version, etc?

**Comment by blainekasten** [comment]
This was already fixed in `0.1.1` https://github.com/pmmmwh/react-refresh-webpack-plugin/pull/17

**Comment by pmmmwh** [comment]
> This was already fixed in `0.1.1` #17

Good catch! I will close this for now, if there is regression feel free to re-open this.
