### ISSUE TITLE
WebSocket is closed before the connection is established.

### ISSUE THREAD

**Issue by sringly** [pmmmwh/react-refresh-webpack-plugin#356]
I use domain to visit local web with whitle proxy;
but I get one error, like 'WebSocket is closed before the connection is established';

how do i modify?

**Comment by pmmmwh** [comment]
What webpack dev tooling are you using? Does the tooling's HMR work without this plugin?

**Comment by sringly** [comment]
using webpack-dev-server,  the tooling's HMR don't work without this plugin
