### ISSUE TITLE
get hot-update.js, but page don't render new content

### ISSUE THREAD

**Issue by sringly** [pmmmwh/react-refresh-webpack-plugin#359]
I save code modify, brower gets hot-update.js, but page don't render new content。  
what should i do?

**Comment by pmmmwh** [comment]
How does your config look like?

**Comment by chrise86** [comment]
@sringly did you get anywhere with this?

**Comment by pmmmwh** [comment]
This is likely due to React Refresh not running before **ANY** React code is ran, please check the Troubleshooting docs for more info, or look at this issue if you externalise React: https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/334

**Comment by pmmmwh** [comment]
Please checkout the troubleshooting guide and try the latest release, it fixed a lot of issues related to complex setups. If you still have issues, feel free to re-open this one or file a new issue with reproduction.
