### ISSUE TITLE
Using with esbuild-loader?

### ISSUE THREAD

**Issue by marioaks** [pmmmwh/react-refresh-webpack-plugin#366]
Hey there,

First of all, thanks for all the hard work on building this plugin. I've used it in lots of projects before and it's amazing!

I was wondering if there was a way to use this plugin with [esbuild-loader](https://github.com/privatenumber/esbuild-loader) instead of babel-loader or ts-loader. I want to use esbuild-loader with webpack for performance purposes. I just can't seem to figure out whether esbuild-loader has a getCustomTransformers equivalent that would work.

This might be too niche to ask on here, but I figured I'd ask in case anyone here knew. 

Thanks!

**Comment by ranisalt** [comment]
I'm using it, just add `new ReactRefreshWebpackPlugin()` to the plugins and set `hot: true` to the dev server

**Comment by pmmmwh** [comment]
With their implementation right now I do not believe it is possible - this requires usage of a "plugin" (i.e. a custom transformer) with ESBuild and to my understanding this is only available for the `build` API, not the `transform` API which is used in the loader.

**Comment by pmmmwh** [comment]
Closing this as it is a limitation upstream.
