### ISSUE TITLE
Uncaught ReferenceError: window is not defined

### ISSUE THREAD

**Issue by tareqdayya** [pmmmwh/react-refresh-webpack-plugin#368]
Hi there,

Thanks for this plugin, i've used it multiple times and it's wonderful 🙂

I have a bit of an unusual problem right now. The nature of the project i'm working with is a bit complex and i'm getting the error mentioned in the title.

The code uses typescript, transpiled through ts-loader. It's also using react2angular to convert react code to angular code and a babel-loader to handle js files. The error occurs in a worker file.

I've tried using the "Robust" approach used with babel [here](https://github.com/pmmmwh/react-refresh-webpack-plugin/blob/main/docs/TROUBLESHOOTING.md#usage-with-indirection-like-workers-and-js-templates) to not run the worker file through the react-refresh-typescript. I've duplicated that behavior for the babel-loader too but the error still occurs.

I'm using:
"@pmmmwh/react-refresh-webpack-plugin": "^0.4.3",
"react-refresh": "^0.10.0",
"react-refresh-typescript": "^2.0.0",
 "type-fest": "^1.0.2",
"fork-ts-checker-webpack-plugin": "^6.1.0",
"webpack": "^4.4.1",
"webpack-dev-server": "^3.1.3",

**Comment by pmmmwh** [comment]
Can you provide the full error stack trace?

This can also happen if you have a worker in a separate loader for example, and the error overlay is injected to that entry.

You can work-around that by using the include/exclude options of this plugin if necessary.

**Comment by tareqdayya** [comment]
Thx for answering so promptly 🙂

I hope this error trace is of use:

`uncaught ReferenceError: window is not defined
(anonymous) @ bootstrap:1
(anonymous) @ bootstrap:780`

This is the block where line 780 is:
`// The require function
 	function __webpack_require__(moduleId) {

 		// Check if module is in cache
 		if(installedModules[moduleId]) {
 			return installedModules[moduleId].exports;
 		}
 		// Create a new module (and put it into the cache)
 		var module = installedModules[moduleId] = {
 			i: moduleId,
 			l: false,
 			exports: {},
 			hot: hotCreateModule(moduleId),
 			parents: (hotCurrentParentsTemp = hotCurrentParents, hotCurrentParents = [], hotCurrentParentsTemp),
 			children: []
 		};

 		// Execute the module function

 		__webpack_require__.$Refresh$.init();
 		try {
 			modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
 		} finally {
 			__webpack_require__.$Refresh$.cleanup(moduleId);
 		}  // this is line 780 😁


 		// Flag the module as loaded
 		module.l = true;

 		// Return the exports of the module
 		return module.exports;
 	}`


I've actually tried the exclude option to exclude workers but it led to a different error:
`
Uncaught TypeError: __react_refresh_utils__.getModuleExports is not a function
    at Object.<anonymous> (theme.js:39)
    at Object../node_modules/@pmmmwh/react-refresh-webpack-plugin/overlay/theme.js (theme.js:39)
    at __webpack_require__ (bootstrap:777)
    at fn (bootstrap:147)
    at Object.<anonymous> (RuntimeErrorFooter.js:1)
    at Object../node_modules/@pmmmwh/react-refresh-webpack-plugin/overlay/components/RuntimeErrorFooter.js (RuntimeErrorFooter.js:91)
    at __webpack_require__ (bootstrap:777)
    at fn (bootstrap:147)
    at Object.<anonymous> (index.js:1)
    at Object../node_modules/@pmmmwh/react-refresh-webpack-plugin/overlay/index.js (index.js:334)
(anonymous) @ theme.js:39
./node_modules/@pmmmwh/react-refresh-webpack-plugin/overlay/theme.js @ theme.js:39
__webpack_require__ @ bootstrap:777
fn @ bootstrap:147
(anonymous) @ RuntimeErrorFooter.js:1
./node_modules/@pmmmwh/react-refresh-webpack-plugin/overlay/components/RuntimeErrorFooter.js @ RuntimeErrorFooter.js:91
__webpack_require__ @ bootstrap:777
fn @ bootstrap:147
(anonymous) @ index.js:1
./node_modules/@pmmmwh/react-refresh-webpack-plugin/overlay/index.js @ index.js:334
__webpack_require__ @ bootstrap:777
fn @ bootstrap:147
./node_modules/react-refresh/runtime.js @ runtime.js:7
__webpack_require__ @ bootstrap:777
fn @ bootstrap:147
./node_modules/@pmmmwh/react-refresh-webpack-plugin/lib/runtime/RefreshUtils.js @ RefreshUtils.js:2
__webpack_require__ @ bootstrap:777
fn @ bootstrap:147
./node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ReactRefreshEntry.js @ ReactRefreshEntry.js:13
__webpack_require__ @ bootstrap:777
fn @ bootstrap:147
0 @ main.5d91fe86d21b21a5043c.js:184003
__webpack_require__ @ bootstrap:777
checkDeferredModules @ bootstrap:45
(anonymous) @ bootstrap:886
(anonymous) @ bootstrap:886
`

**Comment by pmmmwh** [comment]
Do you have the full trace of the `window` error?
You can hide away your code if needed.

I'll take a look at this tomorrow.

**Comment by tareqdayya** [comment]
I hope I got it right. You're going to need to take a look at the trace above and read from there.

![Screen Shot 2021-04-23 at 8 58 24 PM](https://user-images.githubusercontent.com/41693150/115911358-a66a1b80-a476-11eb-8e53-d54eec8ba08f.png)
![Screen Shot 2021-04-23 at 8 58 45 PM](https://user-images.githubusercontent.com/41693150/115911391-b3870a80-a476-11eb-8128-a215cb2246c3.png)
![Screen Shot 2021-04-23 at 8 59 00 PM](https://user-images.githubusercontent.com/41693150/115911415-bb46af00-a476-11eb-9834-b208972a4f23.png)
![Screen Shot 2021-04-23 at 8 59 25 PM](https://user-images.githubusercontent.com/41693150/115911462-cac5f800-a476-11eb-9f0b-0223dc971014.png)
![Screen Shot 2021-04-23 at 8 59 37 PM](https://user-images.githubusercontent.com/41693150/115911490-d1ed0600-a476-11eb-88ff-c3b30340ea7c.png)
![Screen Shot 2021-04-23 at 9 00 00 PM](https://user-images.githubusercontent.com/41693150/115911533-df09f500-a476-11eb-9013-6aa132491ead.png)
![Screen Shot 2021-04-23 at 9 00 14 PM](https://user-images.githubusercontent.com/41693150/115911565-e8935d00-a476-11eb-9c0e-0b6904babf57.png)
![Screen Shot 2021-04-23 at 9 00 26 PM](https://user-images.githubusercontent.com/41693150/115911585-ef21d480-a476-11eb-9bcf-b323f1b6c8f1.png)
![Screen Shot 2021-04-23 at 9 00 35 PM](https://user-images.githubusercontent.com/41693150/115911592-f47f1f00-a476-11eb-9990-9ad2ed382346.png)
![Screen Shot 2021-04-23 at 9 00 45 PM](https://user-images.githubusercontent.com/41693150/115911614-fa750000-a476-11eb-9f40-45bf8081a7f6.png)
Bootstrap L:147 [refer to picture above]
Bootstrap L:777 [refer to picture above] 
![Screen Shot 2021-04-23 at 9 01 20 PM](https://user-images.githubusercontent.com/41693150/115911686-0eb8fd00-a477-11eb-8a89-d964ccbf8548.png)
Bootstrap L:147 [refer to picture above]
Bootstrap L:777 [refer to picture above]
![Screen Shot 2021-04-23 at 9 01 52 PM](https://user-images.githubusercontent.com/41693150/115911748-21cbcd00-a477-11eb-901b-4e05d29b3696.png)
![Screen Shot 2021-04-23 at 9 02 04 PM](https://user-images.githubusercontent.com/41693150/115911770-298b7180-a477-11eb-8712-1d7c0f0b316c.png)
Bootstrap L:147 [refer to picture above]
Bootstrap L:777 [refer to picture above]
![Screen Shot 2021-04-23 at 9 02 54 PM](https://user-images.githubusercontent.com/41693150/115911846-46c04000-a477-11eb-8f70-8388fc460be0.png)
![Screen Shot 2021-04-23 at 9 03 00 PM](https://user-images.githubusercontent.com/41693150/115911856-4aec5d80-a477-11eb-8b6f-c10a8aa97a09.png)
Bootstrap L:147 [refer to picture above]
Bootstrap L:777 [refer to picture above]
![Screen Shot 2021-04-23 at 9 03 15 PM](https://user-images.githubusercontent.com/41693150/115911880-53dd2f00-a477-11eb-81dd-352322707b24.png)

**Comment by pmmmwh** [comment]
Does HMR compiles without using this plugin? It seems like it has something to do with your Webpack HMR runtime instead of this plugin? Can you try bumping Webpack/Webpack-dev-server?

**Comment by pmmmwh** [comment]
Minimum versions: https://github.com/pmmmwh/react-refresh-webpack-plugin#prerequisites

**Comment by tareqdayya** [comment]
And you were absolutely right 🙂 it's fixed.

Here's the final versions I ended up using:
` "webpack": "^4.46.0",
 "webpack-cli": "^4.6.0",
 "webpack-dev-server": "^3.11.2",
 "html-webpack-plugin": "^4.5.2",`

and the code I used:
`{
        oneOf: [
          {
            test: [/worklets\/.+\.[j]s$/, /workers\/.+\.[j]s$/],
            exclude: /node_modules/,
            use: {
              loader: 'babel-loader',
              options: {
                cacheDirectory: true,
                presets: ['@babel/preset-env'],
                plugins: ['@babel/plugin-proposal-class-properties', '@babel/plugin-transform-runtime']
              }
            },
          },
          {
            test: /\.jsx?$/,
            exclude: [/worklets\/.+\.[j]s$/, /workers\/.+\.[j]s$/, /node_modules/],
            use: {
              loader: 'babel-loader',
              options: {
                cacheDirectory: true,
                presets: ['@babel/preset-env', '@babel/preset-react'],
                plugins: ['@babel/plugin-proposal-class-properties', '@babel/plugin-transform-runtime', isDevelopment && 'react-refresh/babel'].filter(Boolean)
              }
            }
          }
        ]
      },
{
        oneOf: [
          {
            test: [/worklets\/.+\.[t]s$/, /workers\/.+\.[t]s$/],
            exclude: /node_modules/,
            use: {
              loader: 'ts-loader',
              options: {
                transpileOnly: true,
              }
            },
          },
          {
            test: /\.tsx?$/,
            exclude: [/worklets\/.+\.[t]s$/, /workers\/.+\.[t]s$/, /node_modules/, /\.spec\.tsx?$/],
            use: {
              loader: 'ts-loader',
              options: {
                transpileOnly: true,
                getCustomTransformers: () => ({
                  before: isDevelopment ? [ReactRefreshTypeScript()] : [],
                }),
              }
            },
          },
        ],
      },`


Didn't need to add any `exclude` to the ReactRefreshWebpackPlugin config object.

The newer version of webpack-dev-server is served with `node_modules/.bin/webpack serve` with no `--watch` option.

Thanks man, and sorry for the trouble. This plugin just keeps delivering ❤️
