### ISSUE TITLE
Support for Webpack 5

### ISSUE THREAD

**Issue by danhart** [pmmmwh/react-refresh-webpack-plugin#379]
I just took your `examples/webpack-dev-server` and updated it to the latest released webpack version(5.36.2) and this plugin does not work.

I also tried with webpack version 5.0.0 and I tried with the latest beta from your main branch (v0.5.0-beta.6). But still no luck in getting this working.

I don't get any errors, it just does nothing at all when I change a React component (nothing updates until I refresh the page manually myself in the browser).

It works perfectly with webpack version 4.

**Comment by pmmmwh** [comment]
Hi this is probably not a bug from us but rather from the other Webpack dependencies.

For example, `html-webpack-plugin` needs to be bumped to v5, and `webpack-cli` would be better off on v4.

I have tested the example out of the box with the following dependencies and it works fine.

```json
{
  "dependencies": {
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
  },
  "devDependencies": {
    "@babel/core": "^7.14.0",
    "@babel/preset-env": "^7.14.1",
    "@babel/preset-react": "^7.13.13",
    "@pmmmwh/react-refresh-webpack-plugin": "^0.5.0-beta.6",
    "babel-loader": "^8.2.2",
    "cross-env": "^7.0.3",
    "html-webpack-plugin": "^5.3.1",
    "react-refresh": "^0.10.0",
    "webpack": "^5.36.2",
    "webpack-cli": "^4.6.0",
    "webpack-dev-server": "^3.11.2"
  }
}
```
