### ISSUE TITLE
Incompatibility with browerslist or potentially native es6 modules?

### ISSUE THREAD

**Issue by danhart** [pmmmwh/react-refresh-webpack-plugin#381]
After feeling somewhat like I'd been smashing my face into a brick wall for about 5 hours, I found the issue with why my configuration wasn't working. As @pmmmwh rightly pointed out, the examples work perfectly with Webpack 5 (as mentioned here https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/379).

So basically everything works fine with the default https://github.com/browserslist/browserslist configuration. However, if you specify a modern browser in your `package.json`, nothing works:

```json
  "browserslist": [
    "Chrome 89"
  ]
```

I'm not sure if this is a problem with this plugin, `react-refresh` or webpack. What I can see is that the bundle gets compiled completely differently with this `package.json` configuration (i.e. the terminal output from Webpack is very different). Exclude any `browserslist` configuration and everything works just perfectly (as per the examples in this repo).

**Comment by pmmmwh** [comment]
This is a bug with `webpack-dev-server` v3 - they do not support the `browserlist` target of Webpack.

To workaround this, you can specify `target: 'web'` in your Webpack config during development, or use the v4 betas of WDS.

Do note that in the latest beta they have a breaking change that would require you to specify the `sockProtocol` parameter to `ws` or `wss`: the default have been changed to use native sockets.
