### ISSUE TITLE
Multiple entrypoints on the same page causes error

### ISSUE THREAD

**Issue by KevinGhadyani-minted** [pmmmwh/react-refresh-webpack-plugin#383]
When I run multiple entrypoints on the same page, this seems to try hot-loading updates for entrypoint 1 in entrypoint 2.

Then it errors that it couldn't update entrypoint 2 even though entrypoint 1 got the update.

**Comment by pmmmwh** [comment]
I believe this is no-longer an issue on the latest RC and Webpack 5, feel free to re-open if you still hit this.
