### ISSUE TITLE
Plugin requires naming of the component being exported

### ISSUE THREAD

**Issue by jeswin** [pmmmwh/react-refresh-webpack-plugin#39]
This can be treated as a non-bug, but it might make sense to mention it somewhere in the documentation.

Fast refresh or reload does not work if a component is written without naming it (as in the example below).

```jsx
export default function() {
  return <h1>Default Export Function</h1>;
}
```

But giving the component a name fixes the problem.

```jsx
export default function MyFunc() {
  return <h1>Default Export Function</h1>;
}
```

With the former, the entire page reloads saying Error: Aborted because filename.js is not accepted.

**Comment by jayenashar** [comment]
hi @jeswin.  i discovered the same issue recently and tracked it down to code in react not this plugin.  i left a comment here: https://github.com/facebook/react/issues/17281#issuecomment-581753769

**Comment by jeswin** [comment]
@jayenashar Good find. @pmmmwh I'll close this for now, but feel free to reopen if you feel this needs to be tracked here.
