### ISSUE TITLE
Websocket error

### ISSUE THREAD

**Issue by undeadfrost** [pmmmwh/react-refresh-webpack-plugin#396]
I created a multi-entry application. Using ReactreFreshPlugin, there are two websockets and link errors

![image](https://user-images.githubusercontent.com/24819204/118349189-c8d8eb80-b581-11eb-984b-3c533f092beb.png)

![image](https://user-images.githubusercontent.com/24819204/118349203-e017d900-b581-11eb-9456-e08fb774c9d5.png)

I started webpack-dev-server with Node
`webpackDevServer.addDevServerEntrypoints(webpackConfig, webpackConfig.devServer);
      const compiler = webpack(webpackConfig);
      const server = new webpackDevServer(compiler, webpackConfig.devServer)
      server.listen(7002, '127.0.0.1')`

devServer config:
`  devServer: {
    hot: true,
    hotOnly: true,
    disableHostCheck: true,
    publicPath: '/dev-static/',
    historyApiFallback: { disableDotRule: true },
    port: 7002,
    headers: {
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, PATCH, OPTIONS',
      'Access-Control-Allow-Headers': 'X-Requested-With, content-type, Authorization',
    },
    stats: 'errors-warnings',
    noInfo: `true,`
  },`

**Comment by pmmmwh** [comment]
What versions of deps are you using? Webpack, WDS, etc.

**Comment by undeadfrost** [comment]
"webpack-dev-server": "^3.11.2"
"webpack": "^5.36.2"
This problem was solved by configuring new ReactRefreshPlugin({ overlay: false })

**Comment by pmmmwh** [comment]
What version of this plugin are you using?

**Comment by pmmmwh** [comment]
To be specific - the double socket is correct. WDS does not provide and functionality for us to re-use their already established socket connection, so we need to establish it once more. The part I don't totally understand is how you would get version mismatching - we should use whatever WDS have installed for `sockjs-client`.

**Comment by undeadfrost** [comment]
MHR works for multiple websockets, except for the console error  

"devDependencies": {
    "@babel/core": "^7.14.0",
    "@babel/preset-env": "^7.14.1",
    "@babel/preset-react": "^7.13.13",
    "@loadable/babel-plugin": "^5.13.2",
    "@loadable/webpack-plugin": "^5.15.0",
    "@pmmmwh/react-refresh-webpack-plugin": "^0.4.3",
    "autod": "^3.0.1",
    "autod-egg": "^1.1.0",
    "autoprefixer": "^10.2.5",
    "clean-webpack-plugin": "^4.0.0-alpha.0",
    "core-js": "^3.12.1",
    "cross-env": "^7.0.3",
    "css-loader": "^5.2.4",
    "egg-bin": "^4.11.0",
    "egg-ci": "^1.11.0",
    "egg-mock": "^3.21.0",
    "eslint": "^5.13.0",
    "eslint-config-egg": "^7.1.0",
    "file-loader": "^6.2.0",
    "mini-css-extract-plugin": "^1.6.0",
    "postcss-loader": "^5.2.0",
    "progress-bar-webpack-plugin": "^2.1.0",
    "react-refresh": "^0.10.0",
    "regenerator-runtime": "^0.13.7",
    "sass": "^1.32.13",
    "sass-loader": "^11.1.1",
    "style-loader": "^2.0.0",
    "webpack-bundle-analyzer": "^4.4.1",
    "webpack-cli": "^4.7.0",
    "webpack-dev-server": "^3.11.2"
    "webpack": "^5.36.2"
  },

**Comment by pmmmwh** [comment]
Are you using `npm` or `yarn`? Can you try removing the lockfile and re-installing everything? I suspect there are multiple copies of `sockjs-client`?

**Comment by undeadfrost** [comment]
I still have this problem after reinstalling, Could it be a conflict with other packages?

**Comment by undeadfrost** [comment]
I use npm, delete package-lock.json `npm i` 
`VM1301 sockjs.bundle.js:1 Uncaught Error: Incompatible SockJS! Main site uses: "1.5.1", the iframe: "1.5.0".
    at VM1301 sockjs.bundle.js:1`
Must be added `new ReactRefreshPlugin({ overlay: false })` The error will disappear and the websocket will become a link

**Comment by pmmmwh** [comment]
Can you check what version of `sockjs` you are using? Can you try using `0.5.0` betas?

```sh
npm ls sockjs
npm ls sockjs-client
```

**Comment by undeadfrost** [comment]
![image](https://user-images.githubusercontent.com/24819204/119434654-3556a600-bd4b-11eb-943f-3df38c8d407f.png)
Need to install version 0.5.0 separately？

**Comment by pmmmwh** [comment]
This is very weird - I'm quite sure that you have two versions of `sockjs-client` installed on your machine. Are you using `npm@7`?

**Comment by pmmmwh** [comment]
Basically the issue is that we have an optional peer dependency on `sockjs-client`, and `webpack-dev-server` have a dependency on `sockjs-client`. If there are two versions of it installed it will conflict.

**Comment by undeadfrost** [comment]
Yes, Webpack-dev-server uses sockjs-client v1.5.0 as you said, but there are other applications that use sockjs-client v1.5.1, thank you for helping me out.
