### ISSUE TITLE
React refresh - hooks issue

### ISSUE THREAD

**Issue by amb445** [pmmmwh/react-refresh-webpack-plugin#399]
I am using react-refresh-webpack-plugin and hot reload is not working when I change the component by adding/removing a useEffect.  

react-refresh (0. 9. 0)
react-refresh-webpack-plugin (0.4.3)
react (16.13.0)

I am attaching the error message. I have also tried with react-refresh(0.10.0) and react-refresh-webpack-plugin beta version(0.5.0-beta.8) and I get the same error.

![react-refresh](https://user-images.githubusercontent.com/58574662/119373892-ca836d00-bc6d-11eb-9d2f-e1a6f24a59c2.jpg)

**Comment by pmmmwh** [comment]
Hi, can you provide a reproduction? It's very hard for me to debug without anything to test.

**Comment by njzydark** [comment]
> Hi, can you provide a reproduction? It's very hard for me to debug without anything to test.

I meet the same problem, you can try this example: https://github.com/njzydark/chrome-extension-boilerplate

```
npm i
npm run dev
```

Then loading extension from chrome or directly open `http://localhost:8080/options.html`, add a hook in options page https://github.com/njzydark/chrome-extension-boilerplate/blob/main/src/options/app.tsx, you can get the same error
