### ISSUE TITLE
Error when installing in a Webpack v5 project

### ISSUE THREAD

**Issue by JDansercoer** [pmmmwh/react-refresh-webpack-plugin#411]
Why is there a hard peer dependency requirement on `@types/webpack` `v4`? Could you update it so that it also accepts `@types/webpack` `v5`?

**Comment by pmmmwh** [comment]
It is an **OPTIONAL** peer dependency, and it is intentional to keep using v4 only - Webpack 5 mostly ships its own types and we do not require anything from DT for it to work.
