### ISSUE TITLE
Cannot use component in declaring module if exporting inline in declaration

### ISSUE THREAD

**Issue by jdimmerman** [pmmmwh/react-refresh-webpack-plugin#425]
Hi - Thanks for the plugin!

The following fails:

```
export const MyComponent1 = () => {
  return <MyComponent2 />;
}

export const MyComponent2 = () => {
  return <div>foo</div>;
}
```

Compilation succeeds, but at runtime, I get the following exception:
`Uncaught ReferenceError: MyComponent2 is not defined`

The following works properly:
```
export const MyComponent1 = () => {
  return <MyComponent2 />;
}

const MyComponent2 = () => {
  return <div>foo</div>;
}

export { MyComponent2 };
```

**Comment by pmmmwh** [comment]
First up - does this run without using the plugin + the Babel plugin?

**Comment by jdimmerman** [comment]
Thanks for responding @pmmmwh.

I'm sorry, I realize I did not note in my original report that I am using typescript and have not attempted this in JS.

This runs properly without the following three packages, via both the webpack dev server and webpack compilation to disk.
- @pmmmwh/react-refresh-webpack-plugin
- react-refresh
- react-refresh-typescript

**Comment by pmmmwh** [comment]
Have you tried using Babel with `react-refresh/babel` instead of `react-refresh-typescript`?

Can you try this plugin in isolation and with transforms and see if that works too?

**Comment by jdimmerman** [comment]
Yep! I'll try those out and respond here.

**Comment by pmmmwh** [comment]
Testing with `0.5.0-rc.6` it seems like it is no-longer an issue, but please re-open if this still persists.
