### ISSUE TITLE
peer deps `@types/webpack` only support 4.x, not 5.x?

### ISSUE THREAD

**Issue by miusuncle** [pmmmwh/react-refresh-webpack-plugin#427]

**Comment by pmmmwh** [comment]
First - `0.5.0` allows usage of `5.x` of `@types/webpack`.
Second, Webpack 5 ships type for most stuff out of the box, and hence in theory we do not need extra types.

**Comment by miusuncle** [comment]
`0.5.0` didn't published yet?

**Comment by pmmmwh** [comment]
`0.5.0-rc.0`

**Comment by miusuncle** [comment]
thx, I can't wait to have a try.
