### ISSUE TITLE
when css-loader options.url is true,  react-refresh-webpack-plugin no work

### ISSUE THREAD

**Issue by mizi-lin** [pmmmwh/react-refresh-webpack-plugin#430]
##  webpack css loader setting  
 options.modules is true (css modules) 
 options.url is true, support require url
```
{
            loader: require.resolve('css-loader'),
            options: {
                importLoaders: 1,
                url: true,
                modules: {
                    compileType: 'module',
                    mode: 'local',
                    // localIdentName: '[local]__[path][name]_[hash:base64:5]',
                    localIdentName: '[local]__[hash:base64:5]',
                    exportLocalsConvention: 'camelCase'
                }
            }
        }
```

### index.tsx 
```tsx
import __styles from 'index.less';
export default () => {
   return <div className={__styles.aaa}></div>
}
```

### index.less 

```less
.aaa {
     background: url(xxx.png)
}
```

### step

open page or refresh page is work, can show png;

but remove className is empty, page is empty;
then recovery className ,  at this time,  HMR reminder index.less change, but page no change,  no see png

react-refresh-webpack-plugin,  css-loader  version is latest

**Comment by mizi-lin** [comment]
https://user-images.githubusercontent.com/2802841/122566912-ae12fe80-d07a-11eb-9788-2e0f57b51cf8.mov

**Comment by pmmmwh** [comment]
This is unrelated to us since we don't process any CSS files, please file an issue at `css-loader`.
