### ISSUE TITLE
edge case when using with hooks

### ISSUE THREAD

**Issue by H2rmone** [pmmmwh/react-refresh-webpack-plugin#433]
Reproduce demo: https://codesandbox.io/s/goofy-framework-v0tjf?file=/src/App.js

When config is a initialValue reference as useState, modify config doesn't update content. should we implement this feature?

```jsx
// after changing config to 2, the content is not update.
// const config = 1
const config = 2

function App() {
  const [state] = useState(config)

  return <div>{state}</div>
}
```

anther possible usage:

```jsx
function App() {
  // after changing config to 2, the content is update.
  // const [state] = useState(1)
  const [state] = useState(2)

  return <div>{state}</div>
}
```

**Comment by BARMPlus** [comment]
+1

**Comment by BARMPlus** [comment]
I also encountered this problem，Is there any solution。

**Comment by pmmmwh** [comment]
This is an issue of CRA instead of us. See facebook/create-react-app#11105

**Comment by H2rmone** [comment]
Thanks!

**Comment by aladdin-add** [comment]
encountered the same issue, but we are not using CRA. @pmmmwh, do you think something can be done in the plugin?

**Comment by aladdin-add** [comment]
I can make a repro later (if needed).

**Comment by pmmmwh** [comment]
@aladdin-add Please create a reproduction.
