### ISSUE TITLE
ReactRefreshPluginOptions missing library property in Typescript

### ISSUE THREAD

**Issue by jayjetley** [pmmmwh/react-refresh-webpack-plugin#436]
When trying to use this package in a micro-frontend architecture we are required to set the library name to allow micro-frontend to update.

However, when trying to use the property via typescript we get the following error

ValidationError: Invalid options object. React Refresh Plugin has been initialised using an options object that does not match the API schema.
 - options has an unknown property 'library'. These properties are valid:
   object { exclude?, forceEnable?, include?, overlay? }
    at validate (/<projectpath>/node_modules/@pmmmwh/react-refresh-webpack-plugin/node_modules/schema-utils/dist/validate.js:98:11)
    at new ReactRefreshPlugin (/<projectpath>/node_modules/@pmmmwh/react-refresh-webpack-plugin/lib/index.js:50:5)
.....

**Comment by pmmmwh** [comment]
Hi, what version are you using?

**Comment by jayjetley** [comment]
Hi, we are using ^0.4.3 all the other properties are in there but it just seems to be missing the library one.

**Comment by pmmmwh** [comment]
It is only available in `0.5.0`. Feel free to use the RC version.
