### ISSUE TITLE
React Fast Refresh can't keep the component state?

### ISSUE THREAD

**Issue by toFrankie** [pmmmwh/react-refresh-webpack-plugin#442]
I follow the guidelines of [Usage](https://github.com/pmmmwh/react-refresh-webpack-plugin#usage) and [Troubleshooting Guide](https://github.com/pmmmwh/react-refresh-webpack-plugin/blob/main/docs/TROUBLESHOOTING.md) to configure the project.

When I finished all the configuration, I added some react component to test. When I edit the source code of a component, although it is HMR through the console, the whole component is reloaded at the same time, instead of keeping the original component state like `react-hot-loader`.

Below are some of my configurations (Based on development mode):

```js
// webpack.config.js
const path = require('path')
const webpack = require('webpack')
const HtmlWebpackPlugin = require('html-webpack-plugin')
const { CleanWebpackPlugin } = require('clean-webpack-plugin')
const ReactRefreshWebpackPlugin = require('@pmmmwh/react-refresh-webpack-plugin')

module.exports = {
  target: 'web',
  mode: 'none',
  devtool: 'eval-source-map',
  entry: './src/index.jsx',

  output: {
    path: path.resolve(__dirname, 'build'),
    publicPath: '/',
    filename: '[name].bundle.js',
    chunkFilename: '[chunkhash].bundle.js' // non-entry
  },

  optimization: {
    moduleIds: 'named'
  },

  devServer: {
    contentBase: false,
    publicPath: '/',
    open: true,
    hot: true,
    // useLocalIp: true,
    compress: true
  },

  resolve: {
    modules: ['node_modules'],
    extensions: ['.js', '.jsx', '.json'],
  },

  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new ReactRefreshWebpackPlugin(),

    new CleanWebpackPlugin(),

    new HtmlWebpackPlugin({
      template: './src/index.html',
      title: 'react-ts demo',
      inject: true,
      hash: true
    }),

    new webpack.DefinePlugin({
      'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV)
    })
  ],

  module: {
    rules: [
      {
        test: /\.js|jsx$/,
        exclude: /node_modules/,
        use: [
          {
            loader: 'babel-loader',
            options: {
              // cacheDirectory: true,
              plugins: [require.resolve('react-refresh/babel')]
            }
          }
        ]
      }
    ]
  }
}

```

```jsx
// entry
// index.jsx
import React from 'react'
import { render } from 'react-dom'
import Root from './root'

const rootEl = document.getElementById('root')
render(<Root />, rootEl)

if (module.hot) {
  module.hot.accept('./root', () => {
    import('./root.jsx').then(module => {
      const NextRoot = module.default
      render(<NextRoot/>, rootEl)
    })
  })
}
```

```
// root.jsx
import React, { useState, Component } from 'react'
import Sub1 from './js/components/Sub1'
import Sub2 from './js/components/Sub2'

export default class Root extends Component {
  state = {
    name: 'Root'
  }

  render() {
    return (
      <div>
        <Sub1 name="Frankie" />
        <Sub2 name="Mandy" />
      </div>
    )
  }
}
```

The `Sub1` is a class component and has its own state. When I modify the components of `Sub1`, the original state will be lost and restored to the default state.

The following are my questions:

* React Fast Refresh can't keep the component state?
* Did I understand React Fast Refresh wrong, or was it a configuration problem?

**Comment by pmmmwh** [comment]
> React Fast Refresh can't keep the component state?

Only state for function components (using hooks) will be kept. This is chosen to not rely on ugly hacks that patches component classes to track changes. Classes are super difficult to track in general especially when there are polyfills in between which also sometimes mess with semantics.

> Did I understand React Fast Refresh wrong, or was it a configuration problem?

It was an intentional choice and this is working as intended.
