### ISSUE TITLE
useURLPolyfill doesn't seem to work in 0.5.0.rc-1

### ISSUE THREAD

**Issue by tmeindle** [pmmmwh/react-refresh-webpack-plugin#444]
Hello,

I am unfortunately stuck supporting IE11 and have been having trouble with the overlay option.

If I set overlay: false I have no issues in IE11 apart from not having an error overlay.  The page loads correctly and when I update a component the refresh happens. 

However setting the overlay option to overlay: { useURLPolyfill: true} or overlay: { useURLPolyfill: false } results in an error in IE11 with the app crashing immediately with no render. Note everything works fine with Chrome and FF with any of the three settings.

This is the error in the dev tools
![image](https://user-images.githubusercontent.com/6541477/124804653-28b79700-df20-11eb-9d96-5c8ddceebc68.png)

Best regards,
Tim

**Comment by tmeindle** [comment]
Actually I mistyped.. thought I was using the latest version and was wrong.  The behavior I described bofor is in IE11 for 0.5.0-beta.9.

After updating to 0.5.0-rc.1 I can not get refresh to work in IE11 no matter what option I pass to the plugin.

    "@pmmmwh/react-refresh-webpack-plugin": "0.5.0-rc.1",
    "react-refresh": "0.11.0-alpha-ed6c091fe-20210701",  same behavior for 0.10.0
    "webpack": "5.43.0",
    "webpack-cli": "4.7.2",
    "webpack-dev-server": "4.0.0-beta.3",

I get the following error:
![image](https://user-images.githubusercontent.com/6541477/124824718-5c9eb680-df38-11eb-8f75-fde03528cbfe.png)

**Comment by pmmmwh** [comment]
I'll check this. Unfortunately I do not have access to a machine with IE11 currently but I guess I can spawn a VM 😬

**Comment by pmmmwh** [comment]
Are you by any chance already using a polyfill in your app, like `react-app-polyfill`, and have the `URL` constructor polyfilled?

**Comment by tmeindle** [comment]
Just core-js and regenerator runtime at the very top of my root index.is.
I do include the two polyfills in the entry field in my webpack.dev.config
to support web pack dev server 4 beta 3 for ie11.  One is whatwg-fetch and
something from corejs.  However I can't remember the exact corejs function
off the top of my head.  I can look tomorrow
