### ISSUE TITLE
in react@18 react-refresh-webpack-plugin && babel-loader && webpackDevServer , cannot apply update. Need to do a full reload

### ISSUE THREAD

**Issue by arleyGuoLei** [pmmmwh/react-refresh-webpack-plugin#448]
![image](https://user-images.githubusercontent.com/40717741/125416062-e3bb600f-1081-4a47-bfb7-890e720946f8.png)

```text
[HMR] Cannot apply update. Need to do a full reload!
[HMR] Error: Aborted because ./client/pages/login/index.tsx is not accepted
```

full reload will cause SSR error, state is lost

demo: [https://github.com/arleyGuoLei/react18-koa2-ssr-groupChat](https://github.com/arleyGuoLei/react18-koa2-ssr-groupChat)

- `yarn`
- `yarn dev`

start server && develop

Tried various schemes

maybe config is error, I need help
---

**main config:**

```js
// webpack config
// ...
module: {
      rules: [
        {
          test: /\.[jt]sx?$/,
          loader: 'babel-loader',
          options: {
            cacheDirectory: true,
            plugins: [
              isClient && isDev && require.resolve('react-refresh/babel')
            ].filter(Boolean)
          },
          exclude: /node_modules/
        }
      ]
    },
```

**Comment by arleyGuoLei** [comment]
- update devServer config:  hot: false / hotOnly: true
- client entry add the code

```js
if(module.hot){
   module.hot.accept()
}
```

----
do not a full reload, but... state  is lost

**Comment by pmmmwh** [comment]
I'll take a look this week.

**Comment by pmmmwh** [comment]
You need to give names to your components. Otherwise, React Refresh would not work.

**Comment by taoliujun** [comment]
Don't appear react component in your entry file.
