### ISSUE TITLE
Webpack 5 throws error The 'compilation' argument must be an instance of Compilation

### ISSUE THREAD

**Issue by karangarg45** [pmmmwh/react-refresh-webpack-plugin#449]
Hi,
I have a monorepo managed by lerna. The plugin was working fine for me in webpack 4 but i just upgraded to webpack 5 and i can not build my source code because of this error

```
TypeError: The 'compilation' argument must be an instance of Compilation
    at Function.getCompilationHooks (/home/kgarg/workspace/app/packages/configs/node_modules/webpack/lib/NormalModule.js:193:10)
    at /home/kgarg/workspace/app/packages/configs/node_modules/@pmmmwh/react-refresh-webpack-plugin/lib/index.js:253:26

```
 I tried searching for the error and landed on this link
 https://github.com/jantimon/html-webpack-plugin/issues/1451

I looked in my codebase and i don't seem to have mutliple copies of webpack. Is there anything i am missing or any way i can debug the problem more?

"webpack": "^5.44.0",
"@pmmmwh/react-refresh-webpack-plugin": "0.4.3",

**Comment by pmmmwh** [comment]
Hi, can you try `0.5.0-rc.2` and report back if that works?

**Comment by karangarg45** [comment]
Tried with the rc version and it seems to work now. Thanks a lot.
