### ISSUE TITLE
"Cannot read property 'replace' of undefined" in the overlay.

### ISSUE THREAD

**Issue by scriptex** [pmmmwh/react-refresh-webpack-plugin#452]
I am experiencing a weird issue with this webpack plugin.
I am not sure what causes this because it occurs randomly but I noticed that it happens when:

1. A path to an external asset (png, svg, or scss file) is changed
2. A variable or property in the redux store is changed

The console output is not so helpful but I will paste it here:
```
Uncaught TypeError: Cannot read property 'replace' of undefined
    at CompileErrorTrace (CompileErrorTrace.js?88cb:25)
    at CompileErrorContainer (CompileErrorContainer.js?ee76:21)
    at eval (index.js?5a19:184)
    at ensureRootExists (index.js?5a19:139)
    at render (index.js?5a19:172)
    at showRuntimeErrors (index.js?5a19:294)
    at eval (utils.js?6b9c:23)
```
The same error is being thrown over and over until I reload my browser. Then the build crashes and I see white screen.

Here is a screenshot from the browser console:
![Screenshot 2021-07-21 at 11 29 13](https://user-images.githubusercontent.com/4603539/126457986-87cccf92-39b5-42b3-8930-679278871318.png)

I have updated to version `0.5.0-rc.2` but the same issue occurred with the previous version I was using (`0.4.3`).

Any help will be highly appreciated.

Edit: Maybe it's worth mentioning that I am using React and Redux with TypeScript in a custom Webpack configuration.
If needed I can provide parts of the Webpack config file which might be relevant for you to debug.

**Comment by pmmmwh** [comment]
Hi, please provide a reproduction - it is impossible for me to debug.

Alternatively, can you print out what errors are captured by the error overlay? There must be some other error triggering it right?
