### ISSUE TITLE
Documentation for non-babel compilers (SWC)

### ISSUE THREAD

**Issue by fforres** [pmmmwh/react-refresh-webpack-plugin#454]
@pmmmwh, I see this pull request here https://github.com/pmmmwh/react-refresh-webpack-plugin/pull/450 

Is there anything missing for us to merge it? I know myself and a bunch of other folks would like to see it added :) 

(cc @Austaras)

**Comment by pmmmwh** [comment]
Hi, I had an accident last Wednesday and I didn't have time for any open source work since then. I'll take a look as soon as I have time.

**Comment by Zaid-Ajaj** [comment]
@pmmmwh That's horrible! I hope you get well and better soon 🙏
