### ISSUE TITLE
hot reloading not working for the first import of react

### ISSUE THREAD

**Issue by KutnerUri** [pmmmwh/react-refresh-webpack-plugin#455]
after a lot of debugging, I noticed that the first file that imports react fails hot reloading.
(that is `import React from 'react'` or `require('react')`)

If I understand correctly, react-refresh runs `.setup(moduleId)`, and then `.register(item, "someExportName")` to allow hot reloading.
Calling another require / import sometimes mess this up by triggering `.init()`, which resets `register`  to be `() => (undefined)`, and preventing the component from setting up correctly.

It seems to be happening especially when requiring `react`, and specifically on the first import.
Our code is a little complicated, so of course it happens in unexpected files, and not in the regular app index.
When I added a preemptive `import React from 'react'`, it seems to be fixed, but not in all cases.

My question is
- Why is this happening? can I use some configuration to mitigate it?
- Do you have any guidelines on this?
- Could this be a bug with react-refresh? I didn't find an issue about it.

I will continue to investigate..

**Comment by KutnerUri** [comment]
In hindsight, This makes some sense. Usually, when I put components in the index file, I get issues with hot reloading.
```tsx
ReactDOM.render(<App />, document.getElementById('root'));

function App() {
  return <div>
  </div>
}

// hot reloading works when components are in a different file.
// do not declare react components here.
```

**Comment by pmmmwh** [comment]
Hi, can you provide a reproducible example?

With the example you have shown with `App` in `index`, it wouldn't work as `index` is the root and any updates to this would try to bubble upwards (due to how we statically analyse `exports`), and since it's root there's no where for us to bubble and hence we need to fallback to force refresh.

**Comment by pmmmwh** [comment]
What versions are you running on? Webpack/React/This Plugin.

**Comment by KutnerUri** [comment]
ah, I thought it was a known issue.

versions:
```
"@pmmmwh/react-refresh-webpack-plugin": "0.4.3",
"webpack": "5.36.2",
"webpack-dev-server": "4.0.0-beta.2",
"react": "17.0.2",
"react-dom": "17.0.2"
```

I will try to get a standalone reproduction of it, I haven't quite figured it out.
```tsx
import React from "react";
import { SecondComponent } from "./second-react";

export { app };

export function SomeReactComponent() {
    return (
        <div>
            <div>before change22221</div>
            <SecondComponent />
        </div>
    );
}


```

**Comment by KutnerUri** [comment]
ah, I thought it was a known issue.
I will to get a standalone reproduction of it, I can't quite figure it out.

versions:
```
"@pmmmwh/react-refresh-webpack-plugin": "0.4.3",
"webpack": "5.36.2",
"webpack-dev-server": "4.0.0-beta.2",
"react": "17.0.2",
"react-dom": "17.0.2"
```

I got this, but it doesn't seem to be the problem

```tsx
// -- second-react.tsx --
import React from "react";

//   hot reloading here works great
export function SecondComponent() {
    return <div>second component3221</div>;
}

// -- first-react.tsx --
import React from "react";
import { SecondComponent } from "./second-react";

export { app };

export function SomeReactComponent() {
    return (
        <div>
            <div>some text</div>
            <SecondComponent />
        </div>
    );
}

//   this breaks hot reloading
export const app = <div>SomeReactComponent</div>;

//   this also breaks hot reloading
//   export { React };


// -- index.tsx --
import React from "react";
import ReactDOM from "react-dom";
import { app } from "./first-react";

ReactDOM.render(app, document.getElementById("root"));
```

**Comment by pmmmwh** [comment]
Hi, are you using `react-refresh/babel` or `react-refresh-typescript`?

**Comment by KutnerUri** [comment]
yes, I'm using `react-refresh/babel`. (though I was very puzzled to find it works without it. 😵‍💫)

I've just upgraded all the packages (WDS 4.1.0, RRWP 0.5.0-rc.6, etc), and so far hot reloading is working for all of the files.
I will update if I find any more problems.
