### ISSUE TITLE
react-refresh 0.10 is out

### ISSUE THREAD

**Issue by kud** [pmmmwh/react-refresh-webpack-plugin#459]
https://www.npmjs.com/package/react-refresh

**Comment by pmmmwh** [comment]
Hi, I know about that and as you can see `0.5.0-rc` does support `0.10.0`.

It will be released soon as stable.

**Comment by kud** [comment]
@pmmmwh cool!

However, I don't see any tag/branch about this 0.5.0 on github…?

![image](https://user-images.githubusercontent.com/655838/128572767-8512351f-3076-421d-8550-e7db4bb3f135.png)

![image](https://user-images.githubusercontent.com/655838/128572784-827f4e4b-776f-4815-bab4-c8c67d73c41a.png)

**Comment by pmmmwh** [comment]
It's on npm.

**Comment by kud** [comment]
Oh okay. I never go to npm website or list the version on npm, I always trust the official repo.

Thank you very much 😊
