### ISSUE TITLE
Styled-components refresh entire page

### ISSUE THREAD

**Issue by mnemanja** [pmmmwh/react-refresh-webpack-plugin#47]
Hi there,
Note:
I've created this issue in the **customize-cra-react-refresh** repo first and got referenced here.

There's a problem with fast-refresh and styled-components. It's making a full page reload. It works, however, when I make changes in a plain React component.

Reference issue:
https://github.com/esetnik/customize-cra-react-refresh/issues/7#issuecomment-597825755

**Comment by Lukavyi** [comment]
Have the same problem

**Comment by gaearon** [comment]
Complete reproducing project pls.

**Comment by mnemanja** [comment]
I stand corrected, the misbehaving is gone.
Everything runs smoothly now.

@Lukavyi, if you are still experiencing the problem please provide Dan with a reproducible project.

**Comment by Lukavyi** [comment]
Same for me, it just randomly started working fine again

**Comment by mnemanja** [comment]
If anyone else experiences the same behavior and finds this issue, provide here a reproduction and I'll reopen it.
