### ISSUE TITLE
hot reload doesn't work using webpack-hot-middleware

### ISSUE THREAD

**Issue by tjx666** [pmmmwh/react-refresh-webpack-plugin#475]
Reproduce repository: https://github.com/tjx666/awesome-chrome-extension-boilerplate/commit/7165090add98bbef64d4f5eb680853bdd878b4db

![image](https://user-images.githubusercontent.com/41773861/129486795-9526e50a-da3b-46fc-b3be-a19cf497a8ea.png)

Thought console show had updated, but the page content not updated. In fact, code had been change to:

![image](https://user-images.githubusercontent.com/41773861/129486853-937e06c4-fd5d-4d33-a55e-18e34d580f46.png)

**Comment by pmmmwh** [comment]
Hi, can you try using `@pmmmwh/react-refresh-webpack-plugin@next` and see if it works?

**Comment by tjx666** [comment]
I finally find:  after I remove `__REACT_DEVTOOLS_GLOBAL_HOOK__` environment I set, everything goes ok. Modify details:

https://github.com/tjx666/awesome-chrome-extension-boilerplate/commit/1f14c5723e7afaa44f22acbcc9bc97af12f6dd26

**Comment by pmmmwh** [comment]
Closing as remedy is found - React Refresh does rely on the dev tools hook, so don't override it :)
