### ISSUE TITLE
Doesn't reload the page after succesfull compile in new react app

### ISSUE THREAD

**Issue by spenat28** [pmmmwh/react-refresh-webpack-plugin#476]
OS: MacOS
Browser: Chroma (latest)

Expected:
on index.js change page should full reload

Actual result:
on index.js change there is no reload, and changes are not visible in browser without manual refresh

Simulate it:
1. create new app
  ```
  $ npx create-react-app my-app
  $ cd my-app
  $ npm start
  ```
2. edit `index.js` - make any change: add some console log or DIV ...
3. in terminal, you can see that app did compile
4. changes should be visible in browser - in this case - full page reload should occur  -- but nothing happens

When editing App.js - changes are fast reloaded. (At least most of the time ...)

Note:
example of this is in new app, but it doesn't work in larger projects either in most files.

Known workaround in our up now is just one solution we know: disabling fast reload.

**Comment by pmmmwh** [comment]
This is a known issue in CRA.

See https://github.com/facebook/create-react-app/pull/11105

**Comment by spenat28** [comment]
@pmmmwh oh thanks, it does work with your patch
