### ISSUE TITLE
Warning "Failed set up the socket connection" with webpack-dev-server 4.0.0-rc.1

### ISSUE THREAD

**Issue by erikt9** [pmmmwh/react-refresh-webpack-plugin#477]
Using `0.5.0-rc.3` of this plugin, when updating to the recently released `webpack-dev-server 4.0.0-rc.1` I start getting the warning `[Warning] [React Refresh] Failed set up the socket connection.` which does not appear under `4.0.0-rc.0`.  This appears to be coming from line 5 of `client/utils/retry.js.`

In the network tab of my browser I am only seeing only one web socket connection being made to the dev server where previously (under `4.0.0-rc.0`) two web socket connections would be established (one from the webpack-dev-server client and one from the react-refresh-webpack-plugin client).

![Screen Shot 2021-08-17 at 5 05 02 PM](https://user-images.githubusercontent.com/49534735/129816358-f8ec19dd-5f37-4cbe-8f58-4ef4279117aa.png)

**Comment by pmmmwh** [comment]
You can set the following:

```js
new ReactRefreshWebpackPlugin({
  overlay: {
    sockPath: '/ws',
  },
});
```

We might support default detection of this in the future, but for now this should fix it.

**Comment by erikt9** [comment]
@pmmmwh 

I don't think that is the problem (I've already made that change). 
```
new ReactRefreshWebpackPlugin({
          overlay: {
            sockProtocol: 'ws',
            sockPath: '/ws',
            sockPort: 1887
          }
        })
```

Placing a `console.warn` to log the exception in the catch block of `retry.js` shows:

[Warning] TypeError: Object is not a constructor (evaluating 'new SocketClient(getUrlFromParts(urlParts, enforceWs))')
initWDSSocket
initSocket
executeWithRetryAndTimeout
(anonymous function)

**Comment by pmmmwh** [comment]
Hmm, that's rough. I'm unfortunately quite occupied this week but hopefully I will be able to take a look this weekend and also setup tests to run on WDS `4.0.0`

**Comment by erikt9** [comment]
@pmmmwh Yes, the PR does resolve my issue.
