### ISSUE TITLE
Seeing console warning when using React-Refresh-Webpack-Plugin

### ISSUE THREAD

**Issue by KevinGhadyani-minted** [pmmmwh/react-refresh-webpack-plugin#478]
I'm seeing this error in my console:

![image](https://user-images.githubusercontent.com/45860344/129854344-83dc0078-4d77-4696-8311-4906aa480065.png)

I tracked it down to `React-Refresh-Webpack-Plugin` as it's the only library using `native-url` in my simple test project that only has a test component. The same error exists in other apps using this build system.

## `package.json`
```
    "@pmmmwh/react-refresh-webpack-plugin": "^0.4.3",
```

## `yarn.lock`
```
"@pmmmwh/react-refresh-webpack-plugin@^0.4.3":
  version "0.4.3"
  resolved "https://registry.yarnpkg.com/@pmmmwh/react-refresh-webpack-plugin/-/react-refresh-webpack-plugin-0.4.3.tgz#1eec460596d200c0236bf195b078a5d1df89b766"
  integrity sha512-br5Qwvh8D2OQqSXpd1g/xqXKnK0r+Jz6qVKBbWmpUcrbGOxUrf39V5oZ1876084CGn18uMdR5uvPqBv9UqtBjQ==
  dependencies:
    ansi-html "^0.0.7"
    error-stack-parser "^2.0.6"
    html-entities "^1.2.1"
    native-url "^0.2.6"
    schema-utils "^2.6.5"
    source-map "^0.7.3"
```

**Comment by pmmmwh** [comment]
`native-url` is removed in `0.5.0`, so this will disappear soon. It's not something we can fix as it is an issue from upstream build setups, so I'll close this.
