### ISSUE TITLE
Migrate plugin for Webpack dev server v4

### ISSUE THREAD

**Issue by jkthinksmart** [pmmmwh/react-refresh-webpack-plugin#481]
Migrate plugin for Webpack dev server v4

**Comment by pmmmwh** [comment]
`0.5.0-rc.4` should work with WDS v4 by default, the socket path however would need a bit of re-work - ideally we would want to support both v3 and v4

**Comment by sibelius** [comment]
it is throwing this error for me

```jsx
Uncaught TypeError: SocketClient is not a constructor
    at initWDSSocket (WDSSocket.js:17)
    at ../../node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ErrorOverlayEntry.js
```

**Comment by pmmmwh** [comment]
> it is throwing this error for me
> 
> ```js
> Uncaught TypeError: SocketClient is not a constructor
>     at initWDSSocket (WDSSocket.js:17)
>     at ../../node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ErrorOverlayEntry.js
> ```

What version?

**Comment by sibelius** [comment]
I think 0.4.x

I will try with 0.5.x

**Comment by tell-y** [comment]
Hi, I'm also facing the same issue. 
Temporarily, I set it like below to avoid the error. 
```
new ReactRefreshWebpackPlugin({
  overlay: false,
})
```

Packages are,
```
"@pmmmwh/react-refresh-webpack-plugin": "^0.4.3",
"webpack": "^5.50.0",
"webpack-dev-server": "^4.0.0",
```

**Comment by pmmmwh** [comment]
My advice: Use `0.5.0`.

It is mostly stable apart from edge cases related to strict-ESM and experimental features.

**Comment by tell-y** [comment]
Thanks. 
I have tried 0.5.0-rc.4, it works well 👍

**Comment by nikhilnayyar002** [comment]
Hi I am using ^0.5.0-rc.4. 
This is the repo link:  ​https://github.com/nikhilnayyar002/react-min

commands to reproduce:
```
git clone https://github.com/nikhilnayyar002/react-min.git
npm ci
npm start
```

I getting console error in browser:
```
WebSocketClient.js?626b:13 WebSocket connection to 'ws://0.0.0.0:3000/sockjs-node' failed:
```

Weird thing is that the error does not appear in browser console when I ran in Apple Macbook Pro M1 but this is happening in my Windows Laptop.

Also here is the hot module configeration in webpack in development mode:
```
            devServer: {
                host: '0.0.0.0',
                hot: true,
...
// plugin
    plugins: [
     ...,
    new webpack.HotModuleReplacementPlugin(),
    new ReactRefreshWebpackPlugin({
       exclude: /node_modules/,
       include: path.resolve(__dirname, "src")
    })
...
// babel loader
                use: [{
                    loader: 'babel-loader',
                    options: {
                        ...
                        plugins: [
                            require.resolve('react-refresh/babel')
                        ]
                    }
                }]
```

After I remove the `@pmmmwh/react-refresh-webpack-plugin` the browser console error disappears in Windows Machine.

Original issue link:
https://github.com/webpack/webpack-dev-server/issues/3712

**Comment by pmmmwh** [comment]
Please set sockPath for now, we don't version detect WDS v3/v4 defaults yet.

```js
new ReactRefreshWebpackPlugin({
  exclude: /node_modules/,
  include: path.resolve(__dirname, "src"),
  overlay: {
    sockPath: '/ws',
  },
});
```

**Comment by nikhilnayyar002** [comment]
Yeah what you mentioned should have worked but now I am seeing this error:
`WebSocketClient.js?626b:13 WebSocket connection to 'ws://0.0.0.0:3000/ws' failed: `

**Comment by mizaelmr** [comment]
> Hi, I'm also facing the same issue.
> Temporarily, I set it like below to avoid the error.
> 
> ```
> new ReactRefreshWebpackPlugin({
>   overlay: false,
> })
> ```
> 
> Packages are,
> 
> ```
> "@pmmmwh/react-refresh-webpack-plugin": "^0.4.3",
> "webpack": "^5.50.0",
> "webpack-dev-server": "^4.0.0",
> ```

Thanks!

**Comment by pmmmwh** [comment]
> Yeah what you mentioned should have worked but now I am seeing this error after making the changes you asked:
> 
> `WebSocketClient.js?626b:13 WebSocket connection to 'ws://0.0.0.0:3000/ws' failed: `
> 
> 
> 
> Earlier this was the error:
> 
> `WebSocketClient.js?626b:13 WebSocket connection to 'ws://0.0.0.0:3000/sockjs-node' failed:`

This is probably a bug in our handling of `0.0.0.0` - what does WDS actually connect to in this case?

**Comment by 92Eli** [comment]
I was getting insecure connection errors with version `0.5.0-rc.4` so I had to run it with:
```
new ReactRefreshWebpackPlugin({ overlay: { sockProtocol: "wss" } }),
```
(connection was `https`, it tried to connect with just `ws://`)

**Comment by pmmmwh** [comment]
> I was getting insecure connection errors with version `0.5.0-rc.4` so I had to run it with:
> 
> ```
> 
> new ReactRefreshWebpackPlugin({ overlay: { sockProtocol: "wss" } }),
> 
> ```
> 
> (connection was `https`, it tried to connect with just `ws://`)

Mind posting how the script URL looks like?

**Comment by pmmmwh** [comment]
`0.5.0-rc.5` should address all issues raised here.

**Comment by alexander-akait** [comment]
@pmmmwh in theory we can improve this and implement `__webpack_dev_server_socket_url__` so you can reuse it and don't worry about future changes

**Comment by pmmmwh** [comment]
@alexander-akait

I think the cleanest solution for us is to have a way to get an initialized socket client from WDS that we can reuse directly - we then don't even need to create a socket connection or care about any internals of WDS.

For example, `webpack-hot-middleware` attach the clients on the `window` global, and we just reuse the client there. Technically this is already "possible" for WDS if the `client` variable [here](https://github.com/webpack/webpack-dev-server/blob/master/client-src/socket.js) is exported, but I also understand that it's better to keep "private" APIs private.

**Comment by alexander-akait** [comment]
@pmmmwh you can use `__webpack_dev_server_client__`, it is public api and safe, or you need something more?

**Comment by nikhilnayyar002** [comment]
Yeah this new update `0.5.0-rc.5` fixes the error. Thanks.
Also @alexander-akait I wanted to ask something. I have asked before but wanted to ask again. In the new WDS 4, does this code below automatically add HotModuleReplacementPlugin ?

```
devServer: {
 hot: true
}
```

Or HotModuleReplacementPlugin  is only automatically added when we pass command line as follows:
```
npx webpack serve --hot only
```

Refer to https://webpack.js.org/configuration/dev-server/#devserverhot

> Note that webpack.HotModuleReplacementPlugin is required to fully enable HMR. If webpack or webpack-dev-server are launched with the --hot option, this plugin will be added automatically, so you may not need to add this to your webpack.config.js. See the HMR concepts page for more information.

In the doc it seems like it is mentioned that it is added automatically only in command line mode.

**Comment by alexander-akait** [comment]
> Also @alexander-akait I wanted to ask something. I have asked before but wanted to ask again. In the new WDS 4, does this code below automatically add HotModuleReplacementPlugin ?

`hot` is `true` by default (i.e. by default only `--no-hot` make sense, but we have `--hot` if you want rewrite `hot: false` on `hot: true` using CLI options), and yes, `hot: true` will add `HotModuleReplacementPlugin`, so you don't need to add `HotModuleReplacementPlugin` if you have `hot: true`

> In the doc it seems like it is mentioned that it is added automatically only in command line mode.

Let's open an issue and rewrite it

**Comment by nikhilnayyar002** [comment]
Thanks @alexander-akait . I have opened an issue but who gonna rewrite that we have to see 😄. Also things like HMR is enabled by default has to be added in docs

**Comment by pmmmwh** [comment]
> @pmmmwh you can use `__webpack_dev_server_client__`, it is public api and safe, or you need something more?

The point is, `__webpack_dev_server_client__` is not an initialized connection, so inevitably we need to emulate the behaviour of WDS (be it URL parsing or socket management with SockJS/WS). We then also need to create a duplicate socket connection.

In the perfect world we would just reuse the connection and attach a handler to it, that way we can drop all emulation of WDS internals in user land.

**Comment by alexander-akait** [comment]
@pmmmwh Let's open an issue in webpack-dev-server and describe what need to be add in API (maybe with small examples), it is not hard and improve compatibility and improve maintenance, big thanks for feedback

**Comment by alexander-akait** [comment]
@pmmmwh friendly ping :star:

**Comment by alexander-akait** [comment]
@pmmmwh 

> Sorry, had been really busy this week ... hopefully I will be able to come up with something during the weekends see_no_evil

Will wait you feedback :star:

**Comment by Kyubinhan** [comment]
The error went away with these set up

```
"@pmmmwh/react-refresh-webpack-plugin": "0.5.0-rc.5",
"webpack": "5.52.0",
"webpack-dev-server": "4.1.0",
```

**Comment by luan-k** [comment]
> Hi, I'm also facing the same issue.
> Temporarily, I set it like below to avoid the error.
> 
> ```
> new ReactRefreshWebpackPlugin({
>   overlay: false,
> })
> ```
> 
> Packages are,
> 
> ```
> "@pmmmwh/react-refresh-webpack-plugin": "^0.4.3",
> "webpack": "^5.50.0",
> "webpack-dev-server": "^4.0.0",
> ```

This is working for me as well!

**Comment by marcosVitorCoelho** [comment]
> Hi, I'm also facing the same issue.
> Temporarily, I set it like below to avoid the error.
> 
> ```
> new ReactRefreshWebpackPlugin({
>   overlay: false,
> })
> ```
> 
> Packages are,
> 
> ```
> "@pmmmwh/react-refresh-webpack-plugin": "^0.4.3",
> "webpack": "^5.50.0",
> "webpack-dev-server": "^4.0.0",
> ```

thank you

**Comment by egorovsa** [comment]
Both variants work
1) 0.5.0-rc.5
or 
```
new ReactRefreshWebpackPlugin({
  overlay: false,
})
```

I prefer the second one
