### ISSUE TITLE
First component loses state on first hot reload

### ISSUE THREAD

**Issue by kwohlfahrt** [pmmmwh/react-refresh-webpack-plugin#489]
If I modify a functional component, on the first hot reload, the first component loses its internal state. Subsequent reloads are OK. It seems to depend on the order the components are imported in, so may be related to #455. Changing the order of imports of `FunctionDefault` and `FunctionNamed` changes which one is affected, but one of them always is.

# Steps to reproduce:
1. Apply the diff below to the current git repository (319e650147c74127c7a4d92328a692f5233efc15). This adds some state to the two functional components, and deletes the class components.
2. Start the dev server with `yarn start`
3. Load the page in the browser, and click the button a few times to modify the state.
4. Modify the functional components, for example: `sed -E 's/more/less/g' -i ./*.tsx`

## Patch
```
diff --git a/examples/typescript-with-tsc/src/App.tsx b/examples/typescript-with-tsc/src/App.tsx
index c7def2a..dbd820a 100644
--- a/examples/typescript-with-tsc/src/App.tsx
+++ b/examples/typescript-with-tsc/src/App.tsx
@@ -9,8 +9,6 @@ const LazyComponent = lazy(() => import('./LazyComponent'));
 function App() {
   return (
     <div>
-      <ClassDefault />
-      <ClassNamed />
       <FunctionDefault />
       <FunctionNamed />
       <Suspense fallback={<h1>Loading</h1>}>
diff --git a/examples/typescript-with-tsc/src/FunctionDefault.tsx b/examples/typescript-with-tsc/src/FunctionDefault.tsx
index f886ae3..8022beb 100644
--- a/examples/typescript-with-tsc/src/FunctionDefault.tsx
+++ b/examples/typescript-with-tsc/src/FunctionDefault.tsx
@@ -1,5 +1,12 @@
+import { useState } from "react";
+
 function FunctionDefault() {
-  return <h1>Default Export Function</h1>;
+  let [state, setState] = useState(1);
+
+  return (<>
+    <h1>Default Export Function{"!".repeat(state)}</h1>
+    <button onClick={() => setState(state => state + 1)}>more</button>
+  </>);
 }
 
 export default FunctionDefault;
diff --git a/examples/typescript-with-tsc/src/FunctionNamed.tsx b/examples/typescript-with-tsc/src/FunctionNamed.tsx
index b807a43..35b1127 100644
--- a/examples/typescript-with-tsc/src/FunctionNamed.tsx
+++ b/examples/typescript-with-tsc/src/FunctionNamed.tsx
@@ -1,3 +1,10 @@
+import { useState } from "react";
+
 export function FunctionNamed() {
-  return <h1>Named Export Function</h1>;
+  let [state, setState] = useState(1);
+
+  return (<>
+    <h1>Named Export Function{"!".repeat(state)}</h1>
+    <button onClick={() => setState(state => state + 1)}>more</button>
+  </>);
 }
```

# Observed result
The page updates, but the state of the first component is lost (i.e. reset to the initial state). The second component maintains its state. This only occurs on the first hot reload, subsequent modifications to the components correctly preserve state.

# Expected result
Both functional components should maintain their state after the modification causes a hot reload.

**Comment by pmmmwh** [comment]
This seems like it's only an issue of `react-refresh-typescript` but not the official Babel plugin.

@Jack-Works Maybe you could help on this? I'm unfamiliar with how the TS custom transformer API works.

**Comment by Jack-Works** [comment]
Hi, I see this but I'm not available recently. I'll add this to my TODO list but I'm not able to fix it in a short time. 👀

**Comment by Jack-Works** [comment]
Yes I can reproduce this.

**Comment by Jack-Works** [comment]
It seems like in the first time rendering, the signature function I'm calling

![image](https://user-images.githubusercontent.com/5390719/132972372-a256db37-77b8-42ff-a91d-ae0b564666a6.png)


Is a mock one. (maybe react-refresh-webpack-plugin didn't setup complete at this stage?)

![image](https://user-images.githubusercontent.com/5390719/132972376-fcdb8520-fc42-4ca9-a50b-3b493f1335d2.png)

**Comment by Jack-Works** [comment]
Therefore the function signature is not reported to the react-refresh runtime at the first load

**Comment by Jack-Works** [comment]
As you can see the code I generated for the working version and non-working version is exactly the same. So I guess there isn't much thing I can do to fix this problem

![image](https://user-images.githubusercontent.com/5390719/132972430-4a9f828f-c6cf-48f5-8607-d2306c4f799b.png)

**Comment by Jack-Works** [comment]
@pmmmwh So the problem is 

> __webpack_require__.$Refresh$.signature = __webpack_require__.$Refresh$.runtime.createSignatureFunctionForTransform;

This code is called too late. Therefore react-refresh missed the first component signature

**Comment by pmmmwh** [comment]
Hey, thanks for the debugging. I've identified a fix!
