### ISSUE TITLE
ErrorOverlayEntry not work

### ISSUE THREAD

**Issue by BlowinInWind** [pmmmwh/react-refresh-webpack-plugin#490]
"webpack-dev-server": "^4.0.0",
![image](https://user-images.githubusercontent.com/7484227/131199111-2924bd2d-1cbd-4639-a349-37297731b19a.png)

**Comment by renan-f** [comment]
Good night, I'm also having the same problem.

**Comment by jiangtong** [comment]
hmr not work

**Comment by pmmmwh** [comment]
Are you using `0.5.0`? If not, it is expected to not work. As per the `package.json` of `0.4.3`, only `3.x` release of WDS is supported.

**Comment by renan-f** [comment]
I installed the latest version through yarn and I had this problem.

**Comment by pmmmwh** [comment]
> I installed the latest version through yarn and I had this problem.

What is the latest version?

**Comment by renan-f** [comment]
I just noticed that Yarn Add is adding version 0.4.3.

I installed passing the version together and it solved the problem.

yarn add -D @pmmmwh/react-refresh-webpack-plugin@0.5.0-rc.5

**Comment by pmmmwh** [comment]
Please use `0.5.0` if you're going to use `4.0.0` of WDS.

**Comment by junyorff12** [comment]
tks man!
