### ISSUE TITLE
webpack5  webpack-dev-server not work

### ISSUE THREAD

**Issue by BlowinInWind** [pmmmwh/react-refresh-webpack-plugin#491]
"webpack": "^5.32.0",
   "webpack-dev-server": "^4.0.0",

![image](https://user-images.githubusercontent.com/7484227/131204537-14c8833f-3e4c-46a4-9105-d9363743f343.png)

` const [state, setstate] = useState(0);

    return (
        <div>
            {state}

            <div>
                <button
                    onClick={() => {
                        setstate(state + 1);
                    }}
                >
                    button
                </button>
            </div>
        </div>
    );`
click the button  state = 1
after coding
state = 0

**Comment by vdesdoigts** [comment]
@BlowinInWind Hello, did you find a solution?
