### ISSUE TITLE
SWC hot reload doesn't work when arrow function is used

### ISSUE THREAD

**Issue by norman-ags** [pmmmwh/react-refresh-webpack-plugin#496]
Whenever I use `arrow function` instead of `function`, hot reload doesn't work. See screenshot and how to repro below: 

![image](https://user-images.githubusercontent.com/63862061/132089929-ee320071-3b7a-407e-92bc-484dab942e39.png)

Repro:
1. clone react-refresh-webpack-plugin
2. navigate to examples/typescript-with-swc
3. Change 
```
function App() {
  return (
    <div>
      <ClassDefault />
      <ClassNamed />
      <FunctionDefault />
      <FunctionNamed />
      <Suspense fallback={<h1>Loading</h1>}>
        <LazyComponent />
      </Suspense>
    </div>
  );
}
```
to
```
const App= () => {
  return (
    <div>
      {/* added */}
     <div> test </div> 
      <ClassDefault />
      <ClassNamed />
      <FunctionDefault />
      <FunctionNamed />
      <Suspense fallback={<h1>Loading</h1>}>
        <LazyComponent />
      </Suspense>
    </div>
  );
}
```
4. Change `test` text to different text

**Comment by norman-ags** [comment]
All good now, I can just do `function` for the root component, and do arrow functions for the children.

**Comment by pmmmwh** [comment]
Hi, Please report to SWC. This is likely a bug in their transform implementation.

CC @Austaras - I think you implemented the original transform?

**Comment by Austaras** [comment]
Yeah it's me.
I have spent some time for this issue and there're multiple layers of problems in this issue:
1. Arrow function get transpiled to `(function () {}).bind(this)`, which is a long standing minor defect in `swc` and there haven't been a good reason to fix it(until this issue)
2. And somehow this will cause react refresh to stop working, I have no idea why though
3. I forget to enable `preset-env` for `swc`, so this issue should be reopened
4. However when I add it and add `browserslist` field to `package.json`, webpack hot reload will silently fail, I have tested with other examples and they behave the same. I have absolutely idea why this is happening

**Comment by pmmmwh** [comment]
>     1. Arrow function get transpiled to `(function () {}).bind(this)`, which is a long standing minor defect in `swc` and there haven't been a good reason to fix it(until this issue)
> 
>     2. And somehow this will cause react refresh to stop working, I have no idea why though

I think it might have something to do with a "stable" identity of the function since we do a shallow compare of exports to check if anything changed?

>     3. I forget to enable `preset-env` for `swc`, so this issue should be reopened @pmmmwh

Yep feel free to PR, I think it's just an option on the loader?

>     4. However when I add it and add `browserslist` field to `package.json`, webpack hot reload will silently fail, I have tested with other examples and they behave the same. I have absolutely idea why this is happening

This is an issue with WDS v3, it doesn't recognise the `browserslist` target. For our example I think it's fine to keep it as `web` in development.

I planned to update to WDS v4 in examples 😄

**Comment by Austaras** [comment]
Cool, great to get my questions answered. I'll send fix when I have time.
