### ISSUE TITLE
Could not find plugin "proposal-numeric-separator"

### ISSUE THREAD

**Issue by Lukavyi** [pmmmwh/react-refresh-webpack-plugin#50]
Error: [BABEL] /Users/taraslukavyi/Projects/traverz/traverz-admin/node_modules/@pmmmwh/react-refresh-webpack-plugin/src/runtime/BabelDetectComponent.js: Could not find plugin "proposal-numeric-separator". Ensure there is an entry in ./available-plugins.js for it. (While processing: "/Users/taraslukavyi/Projects/traverz/traverz-admin/node_modules/babel-preset-react-app/dependencies.js$0")

Can be reproduced if completely removed node_modules and package-lock and `npm i`

**Comment by eugene1g** [comment]
This is triggered by bigger issue in the babel/react ecosystem -> https://github.com/facebook/create-react-app/issues/8680

**Comment by eugene1g** [comment]
Seems like this issue is now resolved - at least our build works again using today's versions of @babel dependencies.
