### ISSUE TITLE
Add custom EventSource and web socket url

### ISSUE THREAD

**Issue by PlayMa256** [pmmmwh/react-refresh-webpack-plugin#51]
I'm currently one of the maintainers on `webpack-plugin-serve` and we also want to support it (specially for one my use cases).

But due to how tangled to wds and wdm this plugin is, we would need support for custom message handlers (similar to https://github.com/pmmmwh/react-refresh-webpack-plugin/blob/master/src/runtime/WHMEventSource.js) and a custom websocket properties!

Would these things be supported? Technically i don't want to embbed a custom message handler to this as well, i would like to leave it as generic as it would be so we can add more extensiability!

something like: 

```
new ReactRefreshWebpackPlugin({
   ws: {
     url: localhost,
     port: 12345
   },
   messageHandler: () => {
     ....
   }
})
```

what do you guys think?

Edit: so we already have one PR on going, which would help 1/2 of this issue: https://github.com/pmmmwh/react-refresh-webpack-plugin/pull/44

**Comment by pmmmwh** [comment]
Hi! I am working on an API to make this less painful. It will probably take me a few more days, but once that's ready I'll release a beta to gather feedback.

**Comment by PlayMa256** [comment]
Oh ok! Let me know please and thank you!
