### ISSUE TITLE
Serving a built website fails: "Can't find variable: $RefreshReg$"

### ISSUE THREAD

**Issue by mmykhaylov** [pmmmwh/react-refresh-webpack-plugin#511]
I created a [repo](https://github.com/mmykhaylov/webpack-react-boilerplate) that illustrates the issue.

Steps to reproduce:

```
git clone https://github.com/mmykhaylov/webpack-react-boilerplate
cd webpack-react-bolierplate
yarn install
yarn build
yarn start
```

I found a similar issue in React Native, but it looks like it's unrelated facebook/react-native#25622

**Comment by pmmmwh** [comment]
You probably didn't set `NODE_ENV` properly for the production build, so `react-refresh/babel` actually transformed your code (but this Webpack plugin is skipped due to `isDevelopment`).
