### ISSUE TITLE
<w> [ReactRefreshPlugin] Hot Module Replacement (HMR) is not enabled! React Refresh requires HMR to function properly.

### ISSUE THREAD

**Issue by cuilongsheng** [pmmmwh/react-refresh-webpack-plugin#515]
Hello, when I configured webpack, I used pmmmwh/react-refresh-webpack-plugin. When I executed npm run build on the command line, the following prompt appeared：<w> [ReactRefreshPlugin] Hot Module Replacement (HMR) is not enabled! React Refresh requires HMR to function properly.
How to avoid this warning?

`> webpack@1.0.0 build
> webpack

**<w> [ReactRefreshPlugin] Hot Module Replacement (HMR) is not enabled! React Refresh requires HMR to function properly.**
asset main.bundle.js 1.32 MiB [emitted] (name: main) 1 related asset
asset index.html 351 bytes [emitted]
runtime modules 2.81 KiB 5 modules
modules by path ./node_modules/core-js-pure/ 106 KiB 99 modules
modules by path ./node_modules/@pmmmwh/react-refresh-webpack-plugin/ 50.7 KiB 23 modules
modules by path ./src/ 15.1 KiB 4 modules
modules by path ./node_modules/scheduler/ 26.3 KiB 4 modules
modules by path ./node_modules/html-entities/lib/*.js 81.3 KiB 4 modules
modules by path ./node_modules/react-refresh/ 21.9 KiB 2 modules
modules by path ./node_modules/react/ 70.6 KiB
  ./node_modules/react/index.js 190 bytes [built] [code generated]
  ./node_modules/react/cjs/react.development.js 70.5 KiB [built] [code generated]
modules by path ./node_modules/react-dom/ 875 KiB
  ./node_modules/react-dom/index.js 1.33 KiB [built] [code generated]
  ./node_modules/react-dom/cjs/react-dom.development.js 874 KiB [built] [code generated]
4 modules
webpack 5.53.0 compiled successfully in 2012 ms`

**Development dependencies I use：**

`"devDependencies": {
    "@babel/core": "^7.15.5",
    "@babel/plugin-proposal-class-properties": "^7.14.5",
    "@babel/preset-env": "^7.15.6",
    "@babel/preset-react": "^7.14.5",
    "@pmmmwh/react-refresh-webpack-plugin": "^0.5.1",
    "babel-loader": "^8.2.2",
    "clean-webpack-plugin": "^4.0.0",
    "core-js": "^3.18.0",
    "css-loader": "^6.3.0",
    "file-loader": "^6.2.0",
    "html-loader": "^2.1.2",
    "html-webpack-plugin": "^5.3.2",
    "raw-loader": "^4.0.2",
    "react-refresh": "^0.10.0",
    "style-loader": "^3.2.1",
    "webpack": "^5.53.0",
    "webpack-cli": "^4.8.0",
    "webpack-dev-server": "^4.2.1"
  },`

webpack.config.js

`
const ReactRefreshWebpackPlugin = require('@pmmmwh/react-refresh-webpack-plugin');
const isDevelopment = process.env.NODE_ENV !== 'production';

hot: true,

{
        test: /\.m?js$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: [
              ['@babel/preset-env']
            ],
            plugins: [isDevelopment && require.resolve('react-refresh/babel')].filter(Boolean),
          }
        }
      }

plugins: [
    isDevelopment && new ReactRefreshWebpackPlugin()
]
`

**Comment by pmmmwh** [comment]
Are you sure you've enabled hot module replacement?

**Comment by palfrey** [comment]
Docs for webpack-dev-server (https://webpack.js.org/configuration/dev-server/#devserverhot) say that if you've got `hot` enabled, it'll automatically load `webpack.HotModuleReplacementPlugin` so this shouldn't be needed to be configured I think?
