### ISSUE TITLE
`sockPort` does not match `window.location.port`

### ISSUE THREAD

**Issue by blissdev** [pmmmwh/react-refresh-webpack-plugin#519]
https://github.com/pmmmwh/react-refresh-webpack-plugin/blob/main/docs/API.md#sockport

In the docs `sockPort` is supposed to default to `window.location.port` but in my case this is not true. I am serving my webpage at `localhost:8888` but it seems to initially attempt to connect to `localhost:3000` which is where I'm serving Webpack before it is proxied through NGINX.

Errors:
![image](https://user-images.githubusercontent.com/3456/136593339-aa1f0c83-ca67-4600-b4e3-3e1d35bd9a08.png)

The following diff fixes the issue for me, but I can't assume port `8888` for all users of this webpack configuration.

```diff
diff --git a/webpack.config.js b/webpack.config.js
--- a/webpack.config.js
+++ b/webpack.config.js
@@ -127,7 +127,14 @@ const settings = {
         output: {
             publicPath: "/static-dev/",
         },
-        plugins: [...plugins, new ReactRefreshWebpackPlugin()],
+        plugins: [
+            ...plugins,
+            new ReactRefreshWebpackPlugin({
+                overlay: {
+                    sockPort: 8888,
+                },
+            })
+        ],
     },
     production: {
         output: {

```

Is there a way I can use the actual `window.location.port` instead of the Webpack origin port? Or is this a bug? Thanks.

**Comment by pmmmwh** [comment]
Are you setting the WDS port in your Webpack config? Can you show the full config?

**Comment by pmmmwh** [comment]
So this is probably a limitation of the current implementation, but we could probably expand the coverage of the `client.webSocketURL` config on `devServer` to support your use case. I'll take a look at it.
