### ISSUE TITLE
could you make a demo for typescript-react with bable.config.js?

### ISSUE THREAD

**Issue by wulibaibao** [pmmmwh/react-refresh-webpack-plugin#520]
At present, 
the react typescript demo uses the options of TS loader to set react refresh typescript, 
but the problem is, how to set it in bable.config.js?
 I have no answer after Google search. 
I hope I can write a case of using devserver and bable.config.js with TS, or directly tell me how to configure it. 
Thank you

**Comment by pmmmwh** [comment]
You can use the same configuration as the `webpack-dev-server` example but add `@babel/preset-typescript` to the presets.
