### ISSUE TITLE
Is react-refresh-webpack-plugin stable with Redux?

### ISSUE THREAD

**Issue by novelette17** [pmmmwh/react-refresh-webpack-plugin#530]
We use React and Redux (will soon be replaced by Mobx) in the project, and use react-hot-loader as HMR. Will there be problems if we switch to react-refresh-webpack-plugin?

**Comment by pmmmwh** [comment]
Yes, as far as I can tell we haven't have any error reports for using with Redux, and for MobX the bugs should have been fixed so it should be stable.
