### ISSUE TITLE
Add `react-refresh@0.11.0` to be a valid peer dependency

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [pmmmwh/react-refresh-webpack-plugin#533]
Warning (current behavior)
```
 WARN  @pmmmwh/react-refresh-webpack-plugin@0.5.1 requires a peer of react-refresh@^0.10.0 but version 0.11.0 was installed.
```
The plugin is working fine for me with version `react-refresh@0.11.0`.

**Comment by tjx666** [comment]
same here:

![image](https://user-images.githubusercontent.com/41773861/142372888-1c31f336-69d5-4076-bbdc-4f5e64ac9f4f.png)
