### ISSUE TITLE
slowness with loader + sourcemaps

### ISSUE THREAD

**Issue by serkanyersen** [pmmmwh/react-refresh-webpack-plugin#536]
Hi,

I've been investigating the slow build times of our project and wanted to share my findings here.

For context, we have a decently large project with thousands of files. When HMR is enabled, it takes around 7 to 8 minutes without babel cache and 4+ minutes with babel cache.

If I disable HMR, the project builds around 4 minutes without cache and 1.8minutes with the cache. 

I did some CPU profiling and found that most of the time is spent on garbage collection; this is also apparent without the profiling because the build starts fast but gradually slows down as the build progresses. 

I went a little bit deeper to understand what part of the build was causing this much memory usage to frequently trigger GC and found this part of the code to be the main culprit.

https://github.com/pmmmwh/react-refresh-webpack-plugin/blob/d35f64631053fcc8e9a112d4895d4f09b2fd46a2/loader/index.js#L73-L87

I understand this is necessary for accurate source maps, but loading the source maps for each file and modifying them in the loader is a heavy operation and sends GC into a frenzy, probably due to the size of some of the maps.

If I comment out this block of code, HMR still works and the build time go back to normal.

Is there a way to optimize this code in any way?

**Comment by serkanyersen** [comment]
```javascript
const consumer = await new SourceMapConsumer(originalSourceMap);
const node = SourceNode.fromStringWithSourceMap(
  source,
  consumer
);
consumer.destroy(); // <-- 
``` 

Changing the code like this seems to resolve the problem. I get more than 50% speed increase (only if you are hitting heavy GC)

SourceMaps seems to map to correct locations and things work fine on my end. 

Can someone verify that this is a safe change?

**Comment by pmmmwh** [comment]
Hey, thanks for the investigation. Source map generation is definitely something that we should further optimise. I've actually been experimenting with the same change you've illustrated here, from my understanding it is actually quite safe to do so.

Another random thought of mine is to actually share some of the source map processing instances across loader runs, but I haven't got any results there yet.

**Comment by serkanyersen** [comment]
Thanks, I'll put up a PR for this 👍

**Comment by pmmmwh** [comment]
I've put up a PR https://github.com/pmmmwh/react-refresh-webpack-plugin/pull/537 using the `with` method which handles both initialization and destruction of the consumer. I've mark you as a co-author :)

If you wouldn't mind - can you test out the PR? You can install the package through the git branch.
