### ISSUE TITLE
Changes in node_modules not being picked up

### ISSUE THREAD

**Issue by alamothe** [pmmmwh/react-refresh-webpack-plugin#538]
Hello,
I am using CRA and TypeScript. 

I am trying to have "fast refresh" pick up a change in `node_modules`. My project is TS but I am changing a plain JavaScript file. When I make the change, the development server **does refresh** however the change is not picked up by the browser — I have to refresh the page to see it. If I refresh the page, it is fine. 

For `src`, everything works flawlessly. 

Do you have any idea what could be the cause?

**Comment by pmmmwh** [comment]
CRA does not apply fast refresh to `node_modules`.

**Comment by alamothe** [comment]
Do you know where that setting is? Is it ultimately a setting in `@pmmmwh/react-refresh-webpack-plugin`?

Because I patched CRA and changed `watchOptions.ignored`, and while the development server does pick up the change (it didn't before my patch), the browser still doesn't pick it up.

**Comment by pmmmwh** [comment]
To my knowledge, CRA v4 does have some "bugs" where necessary bail outs (force refreshes) should happen but does not. This is likely one of those cases.

If you truly want HMR for `node_modules`, you will have to ensure that the `react-refresh/babel` Babel plugin is transforming the files (so you likely need to patch the Webpack loader configurations), and also would have to change the `exclude` option on this plugin, which by default is `/node_modules`.
