### ISSUE TITLE
Does not support the ClassComponent？

### ISSUE THREAD

**Issue by shengdan19** [pmmmwh/react-refresh-webpack-plugin#539]

**Comment by pmmmwh** [comment]
What is not supported?

Class components are support to refresh but not persist state.

**Comment by shengdan19** [comment]
> What is not supported?
> 
> Class components are support to refresh but not persist state.

Will class components (state) be supported in the future？

**Comment by pmmmwh** [comment]
> > What is not supported?
> > Class components are support to refresh but not persist state.
> 
> Will class components (state) be supported in the future？

No, this is an intentional choice to not hack React's internals.

**Comment by shengdan19** [comment]
> > > What is not supported?
> > > Class components are support to refresh but not persist state.
> > 
> > 
> > Will class components (state) be supported in the future？
> 
> No, this is an intentional choice to not hack React's internals.

ok thank you！
