### ISSUE TITLE
You may need an additional loader to handle the result of these loaders

### ISSUE THREAD

**Issue by SmartAngus** [pmmmwh/react-refresh-webpack-plugin#540]
Failed to compile.

../text.ts 10:28
Module parse failed: Unexpected token (10:28)
File was processed with these loaders:
 * ./node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js
You may need an additional loader to handle the result of these loaders.
| 
| // getWords: Get the word array from text. A single Chinese character is a word.
> export function getWords(txt: string) {
|   const words = [];
|   let word = '';

**Comment by jetonk** [comment]
I get the same error by using CRA React with TypeScript and Craco when trying to access files outside of `/src`
![Screenshot 2021-12-07 at 19 06 31](https://user-images.githubusercontent.com/10130015/145083136-462fe35d-eebb-408d-8aba-6a0713c7f7a5.png)

**Comment by pmmmwh** [comment]
> I get the same error by using CRA React with TypeScript and Craco when trying to access files outside of `/src` ![Screenshot 2021-12-07 at 19 06 31](https://user-images.githubusercontent.com/10130015/145083136-462fe35d-eebb-408d-8aba-6a0713c7f7a5.png)

This is expected behaviour with CRA - it doesn't support transpiling source code outside of `src` with the full Babel setup. You probably need more transforms to handle the TS code you're loading outside of `src`.

**Comment by pmmmwh** [comment]
> Failed to compile.
> 
> ../text.ts 10:28 Module parse failed: Unexpected token (10:28) File was processed with these loaders:
> 
>     * ./node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js
>       You may need an additional loader to handle the result of these loaders.
>       |
>       | // getWords: Get the word array from text. A single Chinese character is a word.
> 
> 
> > export function getWords(txt: string) {
> > |   const words = [];
> > |   let word = '';

Seemingly your TS files are not transpiled properly, it should be something to do with your TS setup?

**Comment by christopherGdynia** [comment]
I have got the same issue.
It only appears in local packages in my turborepos, which uses yarn workspaces.

In Reactcomponents I could resolve it, with exporting the type of my props

<details>
<summary>
tscsonfig
</summary>
base config
```json
{
  "$schema": "https://json.schemastore.org/tsconfig",
  "display": "Default",
  "compilerOptions": {
    "allowJs": true,
    "composite": false,
    "declaration": true,
    "declarationMap": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "incremental": true,
    "inlineSources": false,
    "isolatedModules": true,
    "lib": ["ES2021", "DOM", "DOM.Iterable"],
    "module": "esnext",
    "moduleResolution": "node",
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "preserveWatchOutput": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "strict": true,
    "typeRoots": ["../../node_modules/@types"]
  }
}

```
the config
```json
{
  "$schema": "https://json.schemastore.org/tsconfig",
  "display": "React Library",
  "extends": "./base.json",
  "compilerOptions": {
    "jsx": "react-jsx",
    "noEmit": false,
    "target": "ES5"
  }
}
```
</details>

<details>
<summary>
Module parse failed: Unexpected token (11:54)
File was processed with these loaders:
* ../../node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js
* You may need an additional loader to handle the result of these loaders.
</summary>
```ts
import { parseISO } from "date-fns";
import { isIsoDateString } from "./dateFormatHandler";
export * from "./constants";
export * from "./dateFormatHandler";
export * from "./searchParamBuilder";
export * from "./validation/errorMessages";

export const API_BASE_URL = process.env.API_BASE_URL ?? "https://localhost:44371/api/";
export const AUTH_BASE_URL = process.env.AUTH_BASE_URL ?? "https://localhost:7126/";
export const JWT_TIME = +(process.env.JWT_TIME ?? 18); //20
export const REFRESH_TIME = +(process.env.REFRESH_TIME ?? 20); //20
```
</details>

I appreciate every help

**Comment by pmmmwh** [comment]
> I have got the same issue. It only appears in local packages in my turborepos, which uses yarn workspaces.

This seems like you have un-transpiled TS code that was included by this loader, you probably need to add TS transpile to those files?

**Comment by designbyadrian** [comment]
I get this issue when trying to use optional chaining, i.e `const myVar = myObject?.theProperty`

Inside a CRA app running react-scripts 4.0.3 with default options. Do I need to add a .babelrc as well?

**Comment by christopherGdynia** [comment]
> > I have got the same issue. It only appears in local packages in my turborepos, which uses yarn workspaces.
> 
> This seems like you have un-transpiled TS code that was included by this loader, you probably need to add TS transpile to those files?

Ok, how do I implement a loader in cra with typescript?
This might be a nooby question, but I don't have any ideas

**Comment by pmmmwh** [comment]
> > > I have got the same issue. It only appears in local packages in my turborepos, which uses yarn workspaces.
> > 
> > 
> > This seems like you have un-transpiled TS code that was included by this loader, you probably need to add TS transpile to those files?
> 
> Ok, how do I implement a loader in cra with typescript? This might be a nooby question, but I don't have any ideas

The problem with CRA is that it does not support transpiling code outside of the project's `src` directory - so what you would need to do is to have the code transpiled somehow before feeding it into the CRA project, or use something like `react-app-rewired` or `craco` to inject another Babel loader rule so that the code imported from your other workspaces would be transpiled.

**Comment by pmmmwh** [comment]
> I get this issue when trying to use optional chaining, i.e `const myVar = myObject?.theProperty`
> 
> Inside a CRA app running react-scripts 4.0.3 with default options. Do I need to add a .babelrc as well?

I'm not sure about syntax support in CRA versions, maybe you should ask there? Adding a `.babelrc` would definitely help.

**Comment by christopherGdynia** [comment]
I have switched from `CRA` to `NextJS`, this works, in the `turborepo` example is a working solution.

**Comment by pmmmwh** [comment]
Closing as this is expected behaviour - CRA does not transpile outside of `src`, and it is the responsibility of the user to handle that.

**Comment by yatessss** [comment]
this my way can be resolve

```js
const appDirectory = fs.realpathSync(process.cwd());
const resolveApp = relativePath => path.resolve(appDirectory, relativePath);

....

configure: (webpackConfig, {env, paths}) => {
     ...
      // 为了可以解析src目录外的文件 添加一个loader
      const {matches} = getLoaders(webpackConfig, loaderByName('babel-loader'));
      addBeforeLoader(webpackConfig, loaderByName('babel-loader'), {
        ...matches[0].loader,
        include: [resolveApp('../shared')],
      });
     ...
      return webpackConfig;
    },
```

**Comment by JohnXG** [comment]
following @robertcoopercode's suggestion, I found a bit more info re CRA vs craco on youtube
https://youtu.be/zQUpNa1hZIA?t=595

and here is the code from the video
```code
const path = require("path");
const { getLoader, loaderByName } = require("@craco/craco");

const packages = [];
console.log(__dirname);
packages.push(path.join(__dirname, "./path-to-the-shared-package"));

module.exports = {
  webpack: {
    configure: (webpackConfig, arg) => {
      const { isFound, match } = getLoader(
        webpackConfig,
        loaderByName("babel-loader")
      );
      if (isFound) {
        const include = Array.isArray(match.loader.include)
          ? match.loader.include
          : [match.loader.include];

        match.loader.include = include.concat(packages);
      }
      return webpackConfig;
    },
  },
};
```

**Comment by ViieeS** [comment]
In my case I have a published package with transpiled code, so dist contains .js along with d.ts. However, this garbage loader trying to import .d.ts from .js file and return this error.

**package.json**
```
"main": "./dist/index.js",
"types": "./dist/index.d.ts",
```

**tsconfig.json**
```
{
  "compilerOptions": {
    "declaration": true,
    "target": "es6",
    "module": "esnext",
    "moduleResolution": "node",
    "lib": [
      "es6",
      "dom"
    ],
    "noImplicitAny": true,
    "outDir": "dist",
    "rootDir": ".",
    "typeRoots": [
      "node_modules/@types"
    ]
  },
  "exclude": [
    "dist",
    "node_modules"
  ]
}
```

**Comment by Makinde1034** [comment]
> "types": "./dist/index.d.ts",
> "scripts": {
>    "build": "tsc --outDir dist/",
>    "prepare": "npm run build"
> },

Were you able to resolve this issue?

**Comment by keithfrazier98** [comment]
When I added the babel-loader after reading it is recommended, I mistakenly removed `ts-loader`. After adding it back in everything worked great. 

```js 
module.exports = {
  mode: isDevelopment ? "development" : "production",
  entry: {
    index: "./src/index.tsx",
  },
  output: {
    path: path.resolve(__dirname, "dist"),
    filename: "bundle.js",
  },
  resolve: {
    extensions: [".ts", ".tsx", ".js", ".jsx"],
  },
  module: {
    rules: [
      {
        test: /\.tsx$/,
        exclude: /node_modules/,
        use: {
          loader: "ts-loader",
        },
      },
      {
        test: /\.(?:js|mjs|cjs)$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: [
              ['@babel/preset-env', { targets: "defaults" }]
            ]
          }
        }
      }
    ]
  },
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    isDevelopment && new ReactRefreshPlugin(),
    new HtmlWebpackPlugin({
      filename: "index.html",
      template: "./public/index.html",
    }),
  ].filter(Boolean),
  devServer: {
    static: path.join(__dirname, "dist"),
    port: 3000,
  },
};
```

Some of this may not event be necessary, but it's working, so I'll leave it alone. The whole setup now is working with webpack, babel, TS, and HMR.
