### ISSUE TITLE
You may need an additional loader to handle the result of these loaders.

### ISSUE THREAD

**Issue by jetonk** [pmmmwh/react-refresh-webpack-plugin#541]
I get this error when I try to access files outside of `/src` when using CRA React with Craco and TypeScript.

![Screenshot 2021-12-07 at 19 06 31](https://user-images.githubusercontent.com/10130015/145083454-cc7a37ef-303b-47a7-9670-8e98a9308cef.png)

```
"@craco/craco": "^6.4.2",
"react": "^17.0.2",
"@types/node": "^12.0.0",
"@types/react": "^17.0.0",
"@types/react-dom": "^17.0.0",
```

**Comment by pmmmwh** [comment]
https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/540#issuecomment-991783717
