### ISSUE TITLE
How to use refresh with webpack dll

### ISSUE THREAD

**Issue by zejunking** [pmmmwh/react-refresh-webpack-plugin#549]
problem：react-refresh does work，when used with webpack dll.  If I do not use dll, the react-refresh will work normally. 

webpack：5.61.0
react-refresh-webpack-plugin：0.5.4
react: 16.14.0

dll list：
    react、react-dom、react-refresh/runtime

**Comment by pmmmwh** [comment]
Did you set mode to development in the DLL bundle?

**Comment by zejunking** [comment]
> 
Thanks, that's the reason
