### ISSUE TITLE
Type Definition

### ISSUE THREAD

**Issue by fwh1990** [pmmmwh/react-refresh-webpack-plugin#55]
Hi, author. Could you please provide type definition file `index.d.ts` for people who are writing configuration with typescript

**Comment by pmmmwh** [comment]
Since the project contains a lot of JSDoc, I think probably we can generate `.d.ts` files from them. I'll take a look at this in a few days.

**Comment by fwh1990** [comment]
Unfortunately, you miss reference configuration in package.json
```json
{
    "name": "xxx",
    "version": "0.3.0-beta.4"
    "typings": "types/index.d.ts"
}
```

**Comment by pmmmwh** [comment]
> Unfortunately, you lost reference configuration in package.json

This has been fixed in beta 5.
