### ISSUE TITLE
Works with webpack 'virtual modules'

### ISSUE THREAD

**Issue by ntucker** [pmmmwh/react-refresh-webpack-plugin#555]
Motivation: https://github.com/callstack/linaria/pull/879

According to https://webpack.js.org/api/loaders/#inline-matchresource this is the 'official way' to support css in js.

Looking at https://github.com/pmmmwh/react-refresh-webpack-plugin/blob/main/lib/utils/injectRefreshLoader.js however, `match(moduleData.resource)` is matching the virtual css files because `resource` shows up as .js, .tsx, or whatever the js file was that had the css embedded.

**Comment by ntucker** [comment]
`match(moduleData.matchResource || moduleData.resource)` might just do the trick here

**Comment by pmmmwh** [comment]
Will fix this shortly - local tests seem promising
