### ISSUE TITLE
`options.overlay` set to false creates fatal error

### ISSUE THREAD

**Issue by charrondev** [pmmmwh/react-refresh-webpack-plugin#56]
Having the option overlay set to false creates a fatal error in the runtime. This is due to the usage of WebpackProvidePlugin for the overlay.

https://github.com/pmmmwh/react-refresh-webpack-plugin/blob/c42efed652c45e7f991cb19789ad07a863a50537/src/index.js#L39

Webpack will try to load a module called `false` creating a fatal error on the import.

In order to resolve it might be easiest to create a stub implementation like the on I have over here https://github.com/facebook/create-react-app/pull/8582/files#diff-b32bd53ea5f21f7fa8711bb475a72d78

It seems if you want to use the provide plugin you **_have to_** have an actual module there.

I attempted conditionally including/adding the module to provide plugin at all, and that creates errors where it attempts to be used, so I guess the usage sites could be updated instead.

![image](https://user-images.githubusercontent.com/1770056/77985742-404aad80-72e3-11ea-97c3-19bbb2ae58cc.png)

**Comment by avetisk** [comment]
Are you sure you're not giving `'false'` (string) instead of `false` (boolean)?

**Comment by charrondev** [comment]
I'm giving `false`. Any falsy value causes the issue because of the code snippet I linked.

https://github.com/pmmmwh/react-refresh-webpack-plugin/blob/c42efed652c45e7f991cb19789ad07a863a50537/src/index.js#L39

Webpack will attempt to import whatever you give there into the scope of every module.

I doesn't matter if you give `null`, `false`, `undefined`, etc. If it's not a string path to an actual existing module for webpack to load you will get an error.

**Comment by avetisk** [comment]
Well, actually, I have another issue: if I give any falsy value, it just doesn't take it into account, so I can never switch off the overlay :/

I guess there really is some issue with the overlay option.

**Comment by pmmmwh** [comment]
A patch is on its way. Thanks for the report.
