### ISSUE TITLE
Setting connection to websocket are invoked twice

### ISSUE THREAD

**Issue by rkovalyov** [pmmmwh/react-refresh-webpack-plugin#570]
Repo for Reproduce: [https://github.com/rkovalyov/webpack-react-refresh](https://github.com/rkovalyov/webpack-react-refresh)

**Expected:**
- created one channel for websocket 

**Actual**
- settings connection are invoked twice
![image](https://user-images.githubusercontent.com/4090779/151188405-7bdbef0c-47b8-42b0-a245-ca297ad7d39d.png)

Investigation come from:
https://github.com/webpack/webpack-dev-server/issues/4224#issuecomment-1022102337

**Comment by pmmmwh** [comment]
This is expected behaviour - there is no other way for us to tap into the build logs unless we create another socket client as the initialised socket client from WDS is not exposed.
