### ISSUE TITLE
Uncaught TypeError: __webpack_require__.$Refresh$.init is not a function

### ISSUE THREAD

**Issue by ghislainDeffo** [pmmmwh/react-refresh-webpack-plugin#572]
![image](https://user-images.githubusercontent.com/92927993/151801777-219e30a4-82c4-4f62-a24e-bf65a0ae675e.png)

![image](https://user-images.githubusercontent.com/92927993/151801955-8ff3e60b-fe19-44ce-bb33-81af380cde61.png)

We're using cra v4 - with craco originally, but I'm experimenting with react-app-rewired
I've been trying to setup fast-refresh for our project at work. I thought it should already have it. But I've run out of ways to google this thing.

What could be the cause(s) of this error?

Any help appreciated.

**Comment by pmmmwh** [comment]
Hi, if you are using CRA v4, you do not need to inject the plugin yourself. CRA integration is built-in and you should not tinker with it.
