### ISSUE TITLE
Backport ansi-html -> ansi-html-community fix to 0.4.x

### ISSUE THREAD

**Issue by Blasz** [pmmmwh/react-refresh-webpack-plugin#586]
Hi,

I was wondering if you would consider backporting the `ansi-html` to `ansi-html-community` security fix made in https://github.com/pmmmwh/react-refresh-webpack-plugin/pull/501 to v0.4.x. This would allow dependent libraries such as https://github.com/gatsbyjs/gatsby (and their consumers) to adopt the fix without performing a major upgrade from v0.4 to v0.5.

Thank you

**Comment by pmmmwh** [comment]
Hi, the short answer is no - `0.5.x` should be a non-breaking upgrade for most consumers unless they are on really old versions of Webpack/Webpack-dev-server. I would suggest moving to `0.5.x` instead.
