### ISSUE TITLE
No error overlay when using webpack-hot-middleware

### ISSUE THREAD

**Issue by LeComptoirDesPharmacies** [pmmmwh/react-refresh-webpack-plugin#589]
Hi,

I am currently trying your [examples](https://github.com/pmmmwh/react-refresh-webpack-plugin/tree/main/examples) and detected a strange behavior between `webpack-dev-server` and `webpack-hot-middleware`.

On `webpack-dev-server`, if I do a syntax error in my component, there is a compilation failure which is displayed in overlay.
On `webpack-hot-middleware`, if I do the same syntax error, the compilation failure occurs but no overlay displayed.

Is there something I am missing ? Thanks in advance for your enlightenment.

Environment :
Npm version : 6.13.7
Node version : 13.9.0

Yours faithfully,
LCDP

**Comment by pmmmwh** [comment]
WHM does not work well with Webpack 5 - there's a [PR](https://github.com/webpack-contrib/webpack-hot-middleware/pull/397) open, but doesn't seem to be getting much traction. If you need that now, you might want to look at some of the communities forks: https://github.com/gatsbyjs/webpack-hot-middleware.
