### ISSUE TITLE
Hot reloading not working with output.clean set to true

### ISSUE THREAD

**Issue by lamai6** [pmmmwh/react-refresh-webpack-plugin#595]
Hello,

## Explanation

The `output.clean` option cleans the output directory before emitting new assets. It is a useful feature when building manually the files but webpack-dev-server, when a change in a file is detected, will, I guess, also clean the assets stored in memory before compiling again files, which leads to a forced page reload, which prevents the plugin from working properly.

- This works:
  ```js
  output: {
        filename: 'app.bundle.js',
        path: path.resolve(__dirname, 'dist')
  },
  ```

- This won't work:
  ```js
  output: {
        filename: 'app.bundle.js',
        path: path.resolve(__dirname, 'dist'),
        clean: true
  },
  ```

> Environment
>  ```json
>{
>    "npm": "8.3.1",
>    "node": "16.14.0",
>    "react": "^17.0.2",
>    "react-dom": "^17.0.2",
>    "react-refresh": "^0.11.0",
>    "@pmmmwh/react-refresh-webpack-plugin": "^0.5.4"
>}
>  ```

## Suggested solution

I don't know if it could be considered as an issue (and sorry if not), but I think it would be great if this case could be added in [_**Edits always lead to full reload**_](https://github.com/pmmmwh/react-refresh-webpack-plugin/tree/main/docs/TROUBLESHOOTING.md#edits-always-lead-to-full-reload) section of the Troubleshooting guide.

**Comment by TrickyPi** [comment]
which webpack version are you using, see here https://github.com/webpack/webpack/issues/15206

**Comment by lamai6** [comment]
Sorry for the delay @TrickyPi.

I'm using `"webpack": "^5.69.1"`

I read the issue you've linked, it seems like it's a webpack issue still unsolved [with output.clean set to true](https://github.com/webpack/webpack/issues/15206#issuecomment-1028076950).

So I think it's worth adding in the Troubleshooting guide or README file that this option will prevent this plugin from working properly.

**Comment by TrickyPi** [comment]
this webpack issue has been closed by https://github.com/webpack/webpack/pull/15405, you need to upgrade your webpack version to v5.70.0.

**Comment by lamai6** [comment]
Thank you very much @TrickyPi !

**Comment by rmstsd** [comment]
I'm using "webpack": "^5.93.0", There is still this problem.
