### ISSUE TITLE
Full compile instead of HMR with webpack-plugin-serve for webpack versions 5.56.0 onwards

### ISSUE THREAD

**Issue by latema** [pmmmwh/react-refresh-webpack-plugin#599]
We were having a problem in our project with HMR not working, or it seems that a full compile is performed additionally to the HMR. We are using react-refresh-plugin with `webpack-plugin-serve`. Was able to narrow it down to the webpack version where it stops working and managed to replicate it on the `webpack-plugin-serve` example. It should be easy to replicate:

On the examples folder `webpack-plugin-serve` with webpack version fixed to 5.55.1 the HMR works as it should (I am making a change to `./src/ArrowFunction.jsx`):

```
assets by status 3.48 KiB [cached] 1 asset
assets by path *.js 1.53 MiB
  asset bundle.js 1.52 MiB [emitted] (name: main)
  asset 74e84c2-main-wps-hmr.js 3.59 KiB [emitted] [hmr] (name: main)
asset ./index.html 283 bytes [emitted]
asset main-74e84c2-wps-hmr.json 28 bytes [emitted] [hmr]
Entrypoint main 1.53 MiB = bundle.js 1.52 MiB 74e84c2-main-wps-hmr.js 3.59 KiB
cached modules 1.31 MiB [cached] 165 modules
runtime modules 31 KiB 14 modules
./src/ArrowFunction.jsx 1.49 KiB [built] [code generated]
0 (webpack 5.55.1) compiled successfully in 60 ms
```

And with webpack version fixed to 5.56.0 (or any later version up to 5.70.0), there is a lot more going on:
```
assets by status 3.48 KiB [cached] 1 asset
assets by path *.js 1.53 MiB
  asset bundle.js 1.52 MiB [emitted] (name: main)
  asset 7fb7725-main-wps-hmr.js 3.6 KiB [emitted] [hmr] (name: main)
asset ./index.html 283 bytes [emitted]
asset main-7fb7725-wps-hmr.json 28 bytes [emitted] [hmr]
Entrypoint main 1.53 MiB = bundle.js 1.52 MiB 7fb7725-main-wps-hmr.js 3.6 KiB
runtime modules 31 KiB 14 modules
modules by path ./node_modules/core-js-pure/ 119 KiB 110 modules
modules by path ./node_modules/@pmmmwh/react-refresh-webpack-plugin/ 44.8 KiB 19 modules
modules by path ./node_modules/webpack-plugin-serve/ 25.2 KiB 9 modules
modules by path ./src/ 20.4 KiB 8 modules
modules by path ./node_modules/react/ 108 KiB 4 modules
modules by path ./node_modules/scheduler/ 26.3 KiB 4 modules
modules by path ./node_modules/html-entities/lib/*.js 81.3 KiB 4 modules
modules by path ./node_modules/react-refresh/ 21.8 KiB
  ./node_modules/react-refresh/runtime.js 222 bytes [built]
  ./node_modules/react-refresh/cjs/react-refresh-runtime.development.js 21.6 KiB [built]
modules by path ./node_modules/react-dom/ 875 KiB
  ./node_modules/react-dom/index.js 1.33 KiB [built]
  ./node_modules/react-dom/cjs/react-dom.development.js 874 KiB [built]
4 modules
0 (webpack 5.56.0) compiled successfully in 485 ms
```

I also tested with `webpack-dev-server`, and there HMR seems to work fine also with the latest webpack version.

**Comment by pmmmwh** [comment]
Hi, can you try using the latest version of `webpack` and `webpack-plugin-serve`? With `webpack@5.71.0` and `webpack-plugin-serve@1.6.0` I cannot reproduce the issue - and if it persists it is likely unrelated to this plugin.

**Comment by latema** [comment]
Hello, tried with the latest version and cannot reproduce the issue anymore. Can't reproduce it with an earlier version of `webpack` either. Maybe it was some bad combination of library versions, or just plain old user error. Thanks for checking this out!
