### ISSUE TITLE
how to capture the files updated to HMR?

### ISSUE THREAD

**Issue by shudson-versasuite** [pmmmwh/react-refresh-webpack-plugin#600]
![image](https://user-images.githubusercontent.com/57822914/158481422-68ab78cb-758b-4078-8817-958983de2726.png)

Wondering how to capture the list of files that are updated by HMR?  Reasons not important 😬😬😬

It only breaks on the addStatusHandler callback.  Curiously, it doesn't even break on the hot.accept() callback.  In the previous version of my project, which originally came from react-boilerplate, it breaks in the hot.accept() callback after "dispose" and before "apply".  But none of the callbacks have any information regarding the HMR updated files.

![image](https://user-images.githubusercontent.com/57822914/158481145-066feaee-de96-483d-99f2-5bc46ef4b453.png)

**Comment by pmmmwh** [comment]
The `module.hot.accept` and `module.hot.dispose` callbacks are used by this plugin internally, any attempt to override them in user code is bound to not work properly.

As for your use case, unless you wire up a completely custom HMR client, you wouldn't be able to capture the list of updated files (ref [here](https://github.com/webpack/webpack/blob/main/hot/dev-server.js)).
