### ISSUE TITLE
Expo cli error when installing this package. [Error caused in enhanced-resolve]

### ISSUE THREAD

**Issue by smoove** [pmmmwh/react-refresh-webpack-plugin#601]
This error shows up after I `yarn add` this package and run `expo web`.
This happens even without using/importing the plugin at all, simply adding it to the project causes this.

```bash

/home/smoove/.nvm/versions/node/v16.13.2/lib/node_modules/expo-cli/node_modules/enhanced-resolve/lib/Resolver.js:302
                const idxQuery = identifier.indexOf("?");
                              ^
TypeError: identifier.indexOf is not a function
```

```javascript
// I added console.log('identifier',identifier); before the affected line in Resolver.js
// The last few lines of output are:

identifier ./_toKey
identifier ./_isKey
identifier ./_basePropertyDeep
identifier ./_matchesStrictComparable
identifier ./_getMatchData
identifier react-is
identifier ./react-is
identifier ./react-is
identifier ./react-is
identifier ./index.js
identifier ./isArray
identifier ./toString
identifier [Function: toString]
```

The error disappears as soon as I remove the package again.

I found this related issue in the enhanced-resolve repo: https://github.com/webpack/enhanced-resolve/issues/193

**Comment by pmmmwh** [comment]
This is a problem of `enhanced-resolve`: https://github.com/webpack/enhanced-resolve/issues/118

It is related to use of `lodash` in one of our dependencies (`whatwg-url`), and I believe they should fix it there.
