### ISSUE TITLE
[Express] [Webpack 4 externals] fast-refresh doesnt work with webpack externals

### ISSUE THREAD

**Issue by Holalko** [pmmmwh/react-refresh-webpack-plugin#602]
Hi, 

im having problem that react-refresh doesn't work with webpack externals.. tried every solution i found and made a little reproducible [example](https://github.com/Holalko/fast-refresh-webpack-externals) (fork of [this](https://github.com/adbutterfield/fast-refresh-express))

https://github.com/Holalko/fast-refresh-webpack-externals

`npm install`
`npm run dev`

**Comment by hungtcs** [comment]
I have a similar problem. fast-refresh doesn't work when I use the following configuration:

```js
externals: {
  'react': 'React',
  'react-dom': 'ReactDOM',
},
```
---

My webpack version is `5.70.0`

**Comment by pmmmwh** [comment]
https://github.com/pmmmwh/react-refresh-webpack-plugin/blob/main/docs/TROUBLESHOOTING.md#externalising-react
