### ISSUE TITLE
Components don't get re-rendered in React 18 (webpack-hot-middleware)

### ISSUE THREAD

**Issue by drinking-code** [pmmmwh/react-refresh-webpack-plugin#617]
Repro-repo: https://github.com/drinking-code/react-fast-refresh-renderToPipeableStream

So, I'm rendering my application with React 18's new `renderToPipeableStream`, which I think shouldn't interfere with react-refresh. However, I can't get it to work. Whenever I change a component with my dev server running, the client logs, that the code has been updated, but apparently, the updated component does not get re-rendered:
```
[HMR] bundle rebuilding (app.js, line 43834)
[HMR] bundle rebuilt in 118ms (app.js, line 43843)
[HMR] Checking for updates on the server... (app.js, line 43958)
[HMR] Updated modules: (app.js, line 44032)
[HMR]  - ./src/pages/Home.js (app.js, line 44034)
[HMR] App is up to date. (app.js, line 44039)
```

I have set up the project according to the `webpack-hot-middleware` example, and the outputted `app.js` seems to be as it should be. I have also tried externalising react, and it also does't work if I only use one webpack entry. Am I missing something? Or is this a bug with the plugin?

**Comment by pmmmwh** [comment]
I haven't looked at React 18 yet, but I suspect the integration would have to be slightly different (with WHM and Webpack) due to how components are now streamed instead of simply statically compiled?

**Comment by drinking-code** [comment]
I tested it with `renderToString` and it doesn't make react-refresh work. The same setup with react 17 works fine, but just upgrading to React 18 (and obligatorily switching `ReactDOM.hydrate()` to the new `ReactDOMClient.hydrateRoot()`) makes react-refresh stop re-rendering.

Here is a branch with `renderToString` in React 18
https://github.com/drinking-code/react-fast-refresh-renderToPipeableStream/tree/renderToString
and here is another branch with `renderToString` in React 17
https://github.com/drinking-code/react-fast-refresh-renderToPipeableStream/tree/react-17

**Comment by drinking-code** [comment]
Good news: after updating react-refresh from `0.11.0` to `0.12.0` and react-refresh-webpack-plugin from `0.5.4` to `0.5.5` everything works in React 18 now. Both `renderToString` and `renderToPipeableStream`.

Probably was just an incompatibility of react-refresh with react or something similar.

**Comment by ahmaddie1378** [comment]
pls can share code i have had this problem for 3 days

**Comment by drinking-code** [comment]
https://github.com/drinking-code/react-fast-refresh-renderToPipeableStream has all the code discussed.

**Comment by ahmaddie1378** [comment]
example dont use renderToPipeableStream it use renderToString

**Comment by drinking-code** [comment]
Make sure you are on the `master` branch.
Right here is the call to `renderToPipeableStream`: https://github.com/drinking-code/react-fast-refresh-renderToPipeableStream/blob/master/src/server-entry.js#L17

**Comment by ahmaddie1378** [comment]
yes yes now working
ty for the amazing help 
i try it has a problem on reloading the page 
when i reload the page it gives the error of miss matching elements and cant hydrate 
any fix for that ?
