### ISSUE TITLE
Incompatible with React 18

### ISSUE THREAD

**Issue by bradenmitchell** [pmmmwh/react-refresh-webpack-plugin#621]
The react and react-dom libraries have been updated to version 18. Using version 18 with the react-refresh and this webpack plugin throws the following error when running webpack dev server:

```node
ERROR in ./src/index.tsx
Module build failed (from ./node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js):
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './runtime.js' is not defined by "exports" in /Users/Braden/Projects/test-app/node_modules/react-refresh/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:453:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:729:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at Object.<anonymous> (/Users/Braden/Projects/test-app/node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js:20:4)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)

ERROR in ./node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ReactRefreshEntry.js 4:23-58
Module not found: Error: Package path ./runtime.js is not exported from package /Users/Braden/Projects/test-app/node_modules/react-refresh (see exports field in /Users/Braden/Projects/test-app/node_modules/react-refresh/package.json)
```

__Versions__
node: 16.14.0
react: 18.0.0
react-dom: 18.0.0
webpack: 5.70.0
webpack-dev-server: 4.7.4
react-refresh: 0.12.0
react-refresh-webpack-plugin: 0.5.4

Current work around is to disable react-refresh & react-refresh-webpack-plugin or downgrade to react/react-dom 17

**Comment by 1111mp** [comment]
+1

**Comment by kimbaudi** [comment]
i agree that these errors are related to react-refresh 0.12.0 and not react 18. you should be able to use react 18 as long as you don't upgrade from react-refresh 0.11.0 to 0.12.0. we just need to wait for a newer release of react-refresh w/ the fix.

**Comment by luckymore** [comment]
are you ok?

**Comment by luckymore** [comment]
@jussikinnula  I know the reason...

![image](https://user-images.githubusercontent.com/5390013/161368851-770801a0-3572-4a89-8530-a1ca04864382.png)

**Comment by jussikinnula** [comment]
Thanks for noting this. Slava Ukraini.

I can take action and publish an npm package Tomorrow which could be used until we hear back from @pmmmwh.

**Comment by pmmmwh** [comment]
> @jussikinnula I know the reason...

Hi, I really do not appreciate the attempt to misinterpret what I write on my **PERSONAL** Twitter account. The fixes just have not been released simply because I did not have the time and effort to go through more planned work.

> Thanks for noting this. Slava Ukraini.
> 
> I can take action and publish an npm package Tomorrow which could be used until we hear back from @pmmmwh.

If you haven't done it, I would strongly advise against doing so to reduce fragmentation.

Fix is published in `0.5.5`.

**Comment by jussikinnula** [comment]
@pmmmwh, I agree that reducing fragmentation is very important.

I haven't published anything and of course I will not publish anything.

And I'm very sorry for the misinterpretation from my behalf.

**Comment by justin808** [comment]
If React 18 is supported, does the home page need updating?

BTW, thanks @pmmmwh for your great work! I'm maintaining https://github.com/shakacode/react_on_rails and https://github.com/shakacode/shakapacker and this is a key part of the puzzle. 

CC: @tomdracz.
