### ISSUE TITLE
Working with ReScript

### ISSUE THREAD

**Issue by justin808** [pmmmwh/react-refresh-webpack-plugin#625]
**Is there a way to configure this plugin to ignore files with a given extension?**

## Background

In a ReScript React project:

1. I edit file `foobar.res`
2. A watch process creates `foobar.bs.js` 
3. Webpack HMR should run and trigger a page update.

## What happens?

A full-page update per the troubleshooting docs [here](https://github.com/pmmmwh/react-refresh-webpack-plugin/blob/main/docs/TROUBLESHOOTING.md#edits-always-lead-to-full-reload).

## What should happen?

Can this plugin and the webpack-dev-server completely ignore file changes if the files have a given extension of `.res`?

**Comment by pmmmwh** [comment]
You should change the `include` list?

**Comment by justin808** [comment]
@pmmmwh Thanks for the clue! Can you give me a doc link or other details?
