### ISSUE TITLE
You may need an additional loader to handle the result of these loaders.

### ISSUE THREAD

**Issue by config95** [pmmmwh/react-refresh-webpack-plugin#642]
Hello everyone, I'm trying to connect fast refresh to my webpack build. With the example https://github.com/pmmmwh/react-refresh-webpack-plugin/tree/main/examples/typescript-with-tsc
I have 2 configs. 1 for client, 2 for server.
I start the server on port 3000, hmr on port 3001. I get an error:
```
Module parse failed: Unexpected token (7:64)
File was processed with these loaders:
 * ./node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js
You may need an additional loader to handle the result of these loaders.
| import {Header} from "../shared/Header";
|
> const root = hydrateRoot(document.getElementById('react_root'), <Header/>);
|
| const $ReactRefreshModuleId$ = __webpack_require__.$Refresh$.moduleId;

```

Server config:
```
const path = require('path');
const webpackNodeExternals = require('webpack-node-externals');

module.exports = {
    entry: {
        server: path.resolve(__dirname, '/src/server/server.js')
    },
    output: {
        filename: '[name].bundle.js',
        path: path.resolve(__dirname, '../dist/server'),
    },
    module: {
        rules: [
            {
                test: /\.[tj]sx?$/,
                use: ['ts-loader']
            }
        ]
    },
    mode: 'development',
    target: 'node',
    externals: [new webpackNodeExternals()],
    resolve: {
        extensions: ['.js', '.jsx', '.ts', '.tsx', '.json']
    }
}
```
Client config:
```
const path = require('path');
const ReactRefreshWebpackPlugin = require('@pmmmwh/react-refresh-webpack-plugin');
const ReactRefreshTypeScript = require('react-refresh-typescript');
const webpack = require('webpack');
const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin');
module.exports = {
    entry: {
        client: [path.resolve(__dirname, '../src/client/client.jsx'),
            'webpack-hot-middleware/client?path=http://localhost:3001/static/__webpack_hmr']
    },
    output: {
        filename: '[name].bundle.js',
        path: path.resolve(__dirname, '../dist/client/'),
        publicPath: "/static/"
    },
    module: {
        rules: [
            {
                test: /\.[tj]sx?$/,
                include: path.join(__dirname, 'src/shared'),
                loader: "ts-loader",
                options: {
                    getCustomTransformers: () => ({
                        before: [ReactRefreshTypeScript()],
                    }),
                    transpileOnly: true,
                },
            }
        ]
    },
    plugins: [new ReactRefreshWebpackPlugin(), new webpack.HotModuleReplacementPlugin(), new ForkTsCheckerWebpackPlugin()],
    mode: 'development',
    resolve: {
        extensions: ['.js', '.jsx', '.ts', '.tsx', '.json']
    }
}
```
I'm running through node js:
```
const [client, server] = require('./webpack.config.js');
const webpack = require('webpack');
const compilerClient = webpack(client);
const express = require('express');
const wdm = require('webpack-dev-middleware');
const whm = require('webpack-hot-middleware');
const compilerServer = webpack(server);
const nodemon = require('nodemon');
const path = require('path')
const hmr = express();

hmr.use(wdm(compilerClient, {
    publicPath: compilerClient.options.output.publicPath,
    serverSideRender: true,
    writeToDisk: true,
    stats: 'errors-only'
}))

hmr.use(whm(compilerClient, {
    path: '/static/__webpack_hmr',
    heartbeat: 10 * 1000,
    log: false
}));


compilerServer.watch({}, () => {
    console.log('Watch run');
})

compilerClient.run(() => {
    console.log('Bundle client');
})

hmr.listen(3001, () => {
    console.log('Hmr started')
})

nodemon({
    script: path.resolve(__dirname, './dist/server/server.bundle.js'),
    watch: [path.resolve(__dirname, "./dist/server/")]
})
```
server file:
```
const express = require('express');
const {indexTemplate} = require("./indexTemplate");
const {Header} = require("../shared/Header");
const app = express();
import {renderToString} from 'react-dom/server';
import React from 'react';

app.use('/static/', express.static('./dist/client/'))

app.get('/', (req, res) => {
    res.send(indexTemplate(renderToString(<Header/>)));
})

app.listen(3000, () => {
    console.log('Start')
})
```
package.json:
`  "devDependencies": {
    "@pmmmwh/react-refresh-webpack-plugin": "^0.5.7",
    "@types/react": "^18.0.10",
    "@types/react-dom": "^18.0.5",
    "express": "^4.18.1",
    "fork-ts-checker-webpack-plugin": "^7.2.11",
    "nodemon": "^2.0.16",
    "react-refresh": "^0.13.0",
    "react-refresh-typescript": "^2.0.5",
    "ts-loader": "^9.3.0",
    "typescript": "^4.7.2",
    "webpack": "^5.72.1",
    "webpack-cli": "^4.9.2",
    "webpack-dev-middleware": "^5.3.3",
    "webpack-hot-middleware": "^2.25.1",
    "webpack-node-externals": "^3.0.0"
  },
  "dependencies": {
    "react": "^18.1.0",
    "react-dom": "^18.1.0"
  }

`
Here is the structure of my application:
![image](https://user-images.githubusercontent.com/76443106/171294830-5651ae1a-93fc-4ed4-b2ee-150b2f46dac2.png)

help me please. I'm still a beginner.

**Comment by pmmmwh** [comment]
> @config95 I'm encountering roughly the same issue:
> 
> ```
> File was processed with these loaders:
>  * ./node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js
> You may need an additional loader to handle the result of these loaders.
> ```
> 
> How did you solve it?

Are you using TS or something similar - if you do not handle their transform this plugin won't do them for you (but it will show this error, because the file will get processed by this plugin) - they need to be transformed so that Webpack can understand them.

**Comment by chioio** [comment]
> > @config95 I'm encountering roughly the same issue:
> > ```
> > File was processed with these loaders:
> >  * ./node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js
> > You may need an additional loader to handle the result of these loaders.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > How did you solve it?
> 
> Are you using TS or something similar - if you do not handle their transform this plugin won't do them for you (but it will show this error, because the file will get processed by this plugin) - they need to be transformed so that Webpack can understand them.

If I want do not transform my lib in monorepo, what should I do? Because in my lib, I need transform ts, unocss at the same time.

**Comment by pmmmwh** [comment]
> > > @config95 I'm encountering roughly the same issue:
> 
> > > ```
> 
> > > File was processed with these loaders:
> 
> > >  * ./node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js
> 
> > > You may need an additional loader to handle the result of these loaders.
> 
> > > ```
> 
> > > 
> 
> > > 
> 
> > >     
> 
> > >       
> 
> > >     
> 
> > > 
> 
> > >       
> 
> > >     
> 
> > > 
> 
> > >     
> 
> > >   
> 
> > > How did you solve it?
> 
> > 
> 
> > Are you using TS or something similar - if you do not handle their transform this plugin won't do them for you (but it will show this error, because the file will get processed by this plugin) - they need to be transformed so that Webpack can understand them.
> 
> 
> 
> If I want do not transform my lib in monorepo, what should I do? Because in my lib, I need transform ts, unocss at the same time.

Take a look at ts-loader
