### ISSUE TITLE
Cannot set properties of undefined (setting 'runtime')

### ISSUE THREAD

**Issue by tmns** [pmmmwh/react-refresh-webpack-plugin#646]
Hello all!

First, thanks for all the effort on this project! It's been working like a charm for a while now.

The other day however, seemingly randomly, we started noticing a peculiar bug:

We can build our project fine, and when we make changes to related files, the "fast refresh" seems to work as expected. However, if we then perform a full page reload (e.g. by pressing `cmd + R`), the app breaks with the error listed in the title:

```
Cannot set properties of undefined (setting 'runtime')
```

which is in reference to the following code in the bundle:
```
__webpack_require__.$Refresh$.runtime = __webpack_require__("../../node_modules/react-refresh/runtime.js");
```

Looking into this a bit further, it seems that, upon a fresh build, the definition for `__webpack_require__.$Refresh$` does exist in the bundle; however, after a change is made and the refresh completes, the definition at some point is stripped. 

Things then work fine until a full page refresh is triggered, as this causes the bundle to get re-requested & executed, in turn triggering the undefined `$Refresh$` error. I've confirmed this by searching for the definition for `$Refresh$` before and after the above flow, and it is indeed missing afterward (which makes sense given the `undefined` error).

We've searched quite a bit and haven't been able to find a related issue. Has anyone come across this / have any insights?

Our package versions are:
```json
"webpack": "^4.46.0",
"webpack-cli": "^3.3.9",
"webpack-dev-server": "^3.8.1",
"@pmmmwh/react-refresh-webpack-plugin": "^0.5.7",
"react-refresh": "^0.9.0",
"html-webpack-plugin": "^3.2.0",
```

Our Webpack config:
```js
module.exports = smp.wrap({
  entry: { app: ['./src/a.js', './src/index.js'] },
// ...
  plugins: isDevEnv ? [
    new HtmlWebPackPlugin({
      template: './index.html',
      filename: './index.html',
      inject: true,
    }),
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: JSON.stringify(process.env.NODE_ENV),
    }),
    new ReactRefreshWebpackPlugin(),
  ]
// ...
  module: {
// ...
    {
      test: /\.(ts|tsx)$/,
      exclude: /node_modules/,
      use: ['babel-loader', 'ts-loader'],
    },
    {
      test: /\.(js|jsx)$/,
      exclude: /node_modules/,
      use: 'babel-loader',
    },
```

Also in our babel config we removed `'react-refresh/babel'` from the plugins because it was causing this error to show up even more often. We've tried adding it to the webpack config in the `babel-loader` `use` field but it didn't make a difference.

**Comment by tmns** [comment]
Closing this as  it turns out it's [SpeedMeasurePlugin](https://github.com/stephencookdev/speed-measure-webpack-plugin) that's causing this behavior. Disabling / removing that plugin allows Fast Refresh to work properly again. Would be nice for it to be fixed but unfortunately it seems the plugin isn't actively maintained anymore.

**Comment by pmmmwh** [comment]
Yes - unfortunately the implementation of speed measure webpack plugin does not work nicely with incremental rebuilds (it also mess up fork-ts-webpack-plugin, for example).

**Comment by salmagomaa** [comment]
I am stuck in it for days, thank you 🙏

**Comment by sergeydushechkin** [comment]
In my case, the reason was [string-replace-loader](https://github.com/Va1/string-replace-loader). Disabling the loader helped.
