### ISSUE TITLE
An error was reported during local startup

### ISSUE THREAD

**Issue by xiaoguo525** [pmmmwh/react-refresh-webpack-plugin#650]
An error is as follows：
**Error: [BABEL] F:\project\hexin\hexin_html\app\index.jsx: React Refresh Babel transform should only be enabled in development environment. Instead, the environment is: "production". If you want to override this check, pass {skipEnvCheck: true} as plugin options. (While processing: "F:\\project\\hexin\\hexin_html\\node_modules\\react-refresh\\babel.js")**

Where is skipEnvCheck configured ？

**Comment by pmmmwh** [comment]
Hi, this is an option for the `react-refresh/Babel` Babel plugin. You should set the option there if you absolutely want to use the setup in production mode.
