### ISSUE TITLE
Hello, I configured the hot update according to the document method, but when I changed the JS file, the whole page was refreshed instead of partial refresh. Why?

### ISSUE THREAD

**Issue by Yangbg2018** [pmmmwh/react-refresh-webpack-plugin#651]
Hello, I configured the hot update according to the document method, but when I changed the JS file, the whole page was refreshed instead of partial refresh. Why?

**Comment by YoungSeungSeo** [comment]
@Yangbg2018  I have same issue above. In my case, I set ```liveReload: false``` in devServer then whole page reload issue have gone.

**Comment by pmmmwh** [comment]
Hi, did you read this?

https://github.com/pmmmwh/react-refresh-webpack-plugin/blob/main/docs/TROUBLESHOOTING.md

Is it just refreshing for some changes, or all the changes? Do you have a lot of non-React-related named imports near application root?
