### ISSUE TITLE
webpack-hot-middleware is not optional

### ISSUE THREAD

**Issue by avetisk** [pmmmwh/react-refresh-webpack-plugin#66]
Using `0.3.0-beta.1`

`Module not found: Error: Can't resolve 'webpack-hot-middleware/client'`

https://github.com/pmmmwh/react-refresh-webpack-plugin/blob/master/package.json#L62-L64

**Comment by pmmmwh** [comment]
This is fixed in #64

**Comment by Letrab** [comment]
It is still required apparently, fresh installed this lib (beta3). But still I get the error message: 

Failed to compile.
Module not found: Can't resolve 'webpack-hot-middleware/client' in '/Users/.../node_modules/@pmmmwh/react-refresh-webpack-plugin/src/runtime'
node_modules/@pmmmwh/react-refresh-webpack-plugin/src/runtime/WHMEventSource.js
