### ISSUE TITLE
Getting this error: Module not found: Error: Can't resolve 'core-js-pure/features/global-this'

### ISSUE THREAD

**Issue by gobinda-fe** [pmmmwh/react-refresh-webpack-plugin#661]
When trying to run dev server getting this error
ERROR in ./packages/lib-build-tools/node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ReactRefreshEntry.js 2:17-61
Module not found: Error: Can't resolve 'core-js-pure/features/global-this' in '/Users/PATH_TO_CODEBASE/frontend/packages/lib-build-tools/node_modules/@pmmmwh/react-refresh-webpack-plugin/client'

**Comment by donyFeng6** [comment]
`
react-scripts@^5.0.1:
  version "5.0.1"
  dependencies:
    "@pmmmwh/react-refresh-webpack-plugin" "0.4.3"
`

**Comment by gobinda-fe** [comment]
I am using CRA eject. Is there any way to fix without react scripts?

**Comment by vasilews** [comment]
I had a similar error when I missed '.js' in 'resolve.extensions'. [https://webpack.js.org/configuration/resolve/#resolveextensions](https://webpack.js.org/configuration/resolve/#resolveextensions)
