### ISSUE TITLE
Errors do not show up in browser console.

### ISSUE THREAD

**Issue by INCHMAN1901** [pmmmwh/react-refresh-webpack-plugin#666]
### Description

When I manually create a SyntaxError, the errors show up normally in terminal, but not in browser console.

**terminal**

<img width="1411" alt="terminal-error" src="https://user-images.githubusercontent.com/90598758/185049480-5c8d32a9-1581-4c47-9cd8-5fe0cd6ba3b0.png">

**browser console**

<img width="1438" alt="console-hot-update" src="https://user-images.githubusercontent.com/90598758/185049502-09a2476e-85c0-4fd3-8de0-0511e969436e.png">

Since there is a SyntaxError in the updated module, no hot updates are applied to reflect build errors on the page. I'm wondering this is an intended behavior or a bug.

### Configuration

I use express with `webpack-dev-middleware` and `webpack-hot-middleware`as backend, and `react-refresh` and `react-refresh-webpack-plugin` are used to implement `hmr` in react. Below is a MRE.

[react-demo-with-hmr-enabled.zip](https://github.com/pmmmwh/react-refresh-webpack-plugin/files/9356868/react-demo.zip)

### other

`react-hot-loader` will show errors in browser console, which I think is correct.

**Comment by yykyy123123** [comment]
I have this problem too. I don't know how to deal with it

**Comment by INCHMAN1901** [comment]
> I have this problem too. I don't know how to deal with it

@yykyy123123 I think this is intended. You can try to fork this plugin and add a log in [this](https://github.com/pmmmwh/react-refresh-webpack-plugin/blob/40f16570d903680eb5841a45c25d28c1675cb2df/lib/runtime/RefreshUtils.js#L221) function.

**Comment by pmmmwh** [comment]
Hi, sorry for the late reply. Officially, Webpack Hot Middleware does not support Webpack 5 - which is why it doesn't work for you. If you want a quick fix, you can use the [fork by gatsby](https://github.com/gatsbyjs/webpack-hot-middleware) here. Note that you should also set overlay to use `whm` instead of the default `wds` integration:

```js
new ReactRefreshPlugin({
  overlay: {
    sockIntegration: 'whm',
  },
})
```
