### ISSUE TITLE
Client is trying to connect to wrong port

### ISSUE THREAD

**Issue by Tarik02** [pmmmwh/react-refresh-webpack-plugin#667]
I have project running on https://mediadl.test and webpack dev server running on port 8080 (I don't specify port, it's automatically selected). The project is serving HTML template which contains script links to dev server `<script src="https://mediadl.test:8080/js/app.js"></script>`.

I start webpack with this command line:
``` bash
$ webpack --host mediadl.test --client-web-socket-url-hostname=mediadl.test --server-type https --server-options-key=/path/to/mediadl.test.key --server-options-cert=/path/to/mediadl.test.crt --server-options-ca=/path/to/default.pem
```

The problem is that this plugin tries to connect to `wss://mediadl.test/ws` which is wrong. Dev server client itself connects to right endpoint: `wss://mediadl.test:8080/ws`.

Previously port was detected from `document.currentScript` which gives right host and port pair, now it uses data passed from resourceQuery (why?).

**Comment by pmmmwh** [comment]
Hi, if you can provide a reproducible example it would be great. In particular, what Webpack/WDS versions are you using?

We try to parse whatever WDS is using from the configuration (if it exists), and then only override missing fields from `document.currentScript` (where possible) - if we don't do it this way there is no possibility to respect config by default. The behaviour you are seeing is likely a bug, but in the next version we will ship with tighter integration with WDS, which should allow us to deprecate the old approach of sniffing config, and eliminate this bug completely.
