### ISSUE TITLE
Pre-refresh event

### ISSUE THREAD

**Issue by stylesuxx** [pmmmwh/react-refresh-webpack-plugin#675]
Is there any way I can do something before a refresh is triggered? I ran into a couple of cases where this would be useful, but could not find any documentation about how to do this.

In my specific case I would like to close a webserial connection before the current page is refreshed.

**Comment by pmmmwh** [comment]
It is possible to just run something inside the callback of `React.useEffect`; and no, there's no lifecycle to be tapped into right now and I don't plan to add such a functionality (which will encourage implicit weird behaviours).
