### ISSUE TITLE
Security vulnerability - Security Vulnerability - loader-utils 2.0.3

### ISSUE THREAD

**Issue by pbochnak** [pmmmwh/react-refresh-webpack-plugin#693]
<img width="891" alt="image" src="https://user-images.githubusercontent.com/98875319/201683016-744bccd4-a3a7-4dbc-aa6d-fea19b0f273e.png">

**Comment by naseertkxel** [comment]
Hi @pbochnak were you able to make it work? Facing the same issue even with v0.5.9.

**Comment by pmmmwh** [comment]
I will release a new version today. 0.5.9 bumped the version to 2.0.3 but now we need to bump it further.

**Comment by pbochnak** [comment]
@pmmmwh any updates? when can we expect the release?
