### ISSUE TITLE
forcing wrapped imperative components to re-render

### ISSUE THREAD

**Issue by AprilArcus** [pmmmwh/react-refresh-webpack-plugin#694]
I have a library which wraps components written in an imperative framework (like AngularJS, jQuery, d3) in a React shell. These components are unusual by React standards and do not use any of the normal hooks or lifecycle methods. They are memoized such that after initially mounting, they allocate a DOM node for the procedural code using a ref, and then never re-render until they are unmounted.

This presents obvious challenges for the React Refresh. The ideal behavior when an update for one of these components is detected would be to unmount and re-mount the component in question. An acceptable fallback would be to perform a full page reload. Is there any way I can annotate the components returned by my library such that they are opted out of the usual React Refresh behavior?

**Comment by pmmmwh** [comment]
Can you create an example on how it will look? It doesn't sound like it won't work out of the box if the logic to render is within some sort of effect.

**Comment by pmmmwh** [comment]
Hi, you can use [directive feature](https://github.com/pmmmwh/react-refresh-webpack-plugin/blob/main/docs/API.md#directives)
