### ISSUE TITLE
Syntax errors with typescript 4.9 "satisfies" operator

### ISSUE THREAD

**Issue by nickhall** [pmmmwh/react-refresh-webpack-plugin#709]
I'm running version 0.5.10 of the plugin with babel core version 7.20.5. I am trying to use the new `satisfies` operator from TypeCript 4.9, but I am getting errors caused by this plugin:

```
ERROR in ./app/myfile.ts 19:2
Module parse failed: Unexpected token (19:2)
File was processed with these loaders:
 * ./node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|     color: white
|   }
> } satisfies PageStyles);
|
| var $ReactRefreshModuleId$ = __webpack_require__.$Refresh$.moduleId;
```

I have isolated it to react-refresh-webpack-plugin. If I disable it, everything works as intended. Let me know if you need other information.

**Comment by pmmmwh** [comment]
Please report to Babel - it is up to them (and @babel/preset-typescript) to transform the new syntax into parsable code.
