### ISSUE TITLE
Websocket shows "type": "invalid" each time I save a file

### ISSUE THREAD

**Issue by mxvsh** [pmmmwh/react-refresh-webpack-plugin#741]
I have tried using this plugin with `swc`. `esbuild`, `babel` but each time i get type invalid error in the websocket message. I am using latest version of all the packages.

<img width="337" alt="Screenshot 2023-03-26 at 11 33 39" src="https://user-images.githubusercontent.com/31907722/227758334-5c9b6f56-9cc6-4a44-9fcb-0b4f54288134.png">

**Comment by pmmmwh** [comment]
I believe `invalid` is a normal status?
