### ISSUE TITLE
Security vulnerability -  loader-utils 2.0.4

### ISSUE THREAD

**Issue by FujitaKyotaka** [pmmmwh/react-refresh-webpack-plugin#788]
`loader-utils: 2.0.4` has the dependency `JSON5: 2.1.2`
it causes Prototype Pollution in JSON5 via Parse Method

**Comment by DanielRuf** [comment]
Most probably not a real risk, see also https://overreacted.io/npm-audit-broken-by-design/

**Comment by pmmmwh** [comment]
Unfortunately since we still support WDS v3 it is likely impossible to fix. Probably something for `0.6.x`.

**Comment by pmmmwh** [comment]
Will be fixed in `v0.6.0`.

**Comment by mciastek** [comment]
@pmmmwh is the `v0.6.0` going to be released soon? In the latest version `react-refresh-webpack-plugin` the vulnerability is still present.
