### ISSUE TITLE
Server startup hangs forever (or a really long time?) if disableRefreshCheck=false

### ISSUE THREAD

**Issue by drather19** [pmmmwh/react-refresh-webpack-plugin#8]
I have to set `disableRefreshCheck: true` in order to successfully start up the webpack-dev-server, otherwise the startup seems to hang (I waited minutes, but not hours).

This is observable both on an ejected CRA app patched using instructions from the README as well as an existing CRA app that uses react-app-rewired/customize-cra.

**Comment by pmmmwh** [comment]
> I have to set `disableRefreshCheck: true` in order to successfully start up the webpack-dev-server, otherwise the startup seems to hang (I waited minutes, but not hours).
> 
> This is observable both on an ejected CRA app patched using instructions from the README as well as an existing CRA app that uses react-app-rewired/customize-cra.

OK - have been investigating this. It seems that the plugin thrown an Error during compilation and is supposed to warn you, but the error somehow got lost and never got propagated to the console. It might have something to do with the CRA's custom error handling using the Webpack Node API.

Will further investigate on that.
