### ISSUE TITLE
Error on app start while loading the page

### ISSUE THREAD

**Issue by bovas85** [pmmmwh/react-refresh-webpack-plugin#80]
When I compile the app and open the localhost webpage I am welcomed by this error:
![image](https://user-images.githubusercontent.com/16958684/80075329-6f4eea80-8542-11ea-9ce9-91f00f37be24.png)

There's no error in the console or in the terminal, and when I close this I can work on the app and reload works fine. This is just happening on page load looks like.

I'm using the plugin new ReactRefreshWebpackPlugin(), and adding this before HtmlWebpackPlugin

**Comment by pmmmwh** [comment]
Hi! Is it possible for you to create a minimal reproducable repo so that I can track down the issue? It seems to me that your application somehow have an unhandled promise rejection on load, so it triggered the error overlay integration.

**Comment by bovas85** [comment]
unlikely :( it's a corporate app and the codebase is relatively huge. Is there any other way to track this down? Otherwise how would I remove this overlay completely?

**Comment by pmmmwh** [comment]
> unlikely :( it's a corporate app and the codebase is relatively huge. Is there any other way to track this down? Otherwise how would I remove this overlay completely?

If you're on the latest beta, you can set `overlay: false` to disable the overlay.

Which webpack dev integration are you using? Is it possible for you to provide a full console snapshot? If you don't mind tracking it down yourself, you can checkout the last few lines in `runtune/ErrorOverlayEntry.js` and line 37 in `runtime/errorEventHandlers.js`. I suspect some unhandled promise rejection occured and it triggered the handlers.

**Comment by bovas85** [comment]
It's a custom webpack 4 dev server with happypack, with hardly any way to customise it as it's abstracted into a package. Where would those files be?
How do I know if I'm on the beta?

**Comment by pmmmwh** [comment]
> It's a custom webpack 4 dev server with happypack, with hardly any way to customise it as it's abstracted into a package.

I'll set up a `happypack` development environment and see if I can reproduce.

> Where would those files be?

Inside `node_modules/@pmmmwh/react-refresh-webpack-plugin/src`.

> How do I know if I'm on the beta?

Version `0.3.0-beta.5` is what you're looking for.

**Comment by bovas85** [comment]
I installed the beta and the overlay is gone, thanks :D
