### ISSUE TITLE
Issues with peer dependencies found

### ISSUE THREAD

**Issue by rkmsnc** [pmmmwh/react-refresh-webpack-plugin#824]
Hi,
There is a WARN  Issues with peer dependencies found for webpack-dev-server 5.x version 
└─┬ @pmmmwh/react-refresh-webpack-plugin 0.5.11
  └── ✕ unmet peer webpack-dev-server@"3.x || 4.x": found 5.0.4

![Screenshot_20240326-000029](https://github.com/pmmmwh/react-refresh-webpack-plugin/assets/46848877/df67978b-1118-47e5-b6ec-ec9a9cd24264)

Thanks

**Comment by nyngwang** [comment]
It had been reported, see #802.
