### ISSUE TITLE
[webpack-dev-server] Some internal modules are deprecated.

### ISSUE THREAD

**Issue by stein2nd** [pmmmwh/react-refresh-webpack-plugin#841]
npm warn deprecated rimraf@3.0.2:
Rimraf versions prior to v4 are no longer supported
![rimraf@3 0 2](https://github.com/pmmmwh/react-refresh-webpack-plugin/assets/531628/58ed0ab2-f12f-4443-9554-47698710b4e6)

npm warn deprecated glob@7.2.3:
Glob versions prior to v9 are no longer supported
![rimraf@3 0 2](https://github.com/pmmmwh/react-refresh-webpack-plugin/assets/531628/ee3de2cd-b359-486c-8a6e-1aebe2fc30b0)

**Comment by pmmmwh** [comment]
Hi, if you upgrade to webpack-dev-server v5 the error should go away?

**Comment by stein2nd** [comment]
After upgrading webpack-dev-server to v5, the error disappeared.

**Comment by pmmmwh** [comment]
Unfortunately we cannot do anything to fix deprecated dependencies from downstream dependencies. In `v0.6.x` we will drop support for WDSv4 which will remove this warning.
