### ISSUE TITLE
[del-cli] Some internal modules are deprecated.

### ISSUE THREAD

**Issue by stein2nd** [pmmmwh/react-refresh-webpack-plugin#843]
npm warn deprecated rimraf@3.0.2:
Rimraf versions prior to v4 are no longer supported
![＠pmmmwhreact-ref resh-webpack-plugin](https://github.com/pmmmwh/react-refresh-webpack-plugin/assets/531628/852523c3-2107-4b2d-ae93-add3bfd6c0e7)

**Comment by pmmmwh** [comment]
Unfortunately we cannot do anything to fix deprecated dependencies from downstream dependencies.
