### ISSUE TITLE
[webpack-plugin-serve] Some internal modules are deprecated.

### ISSUE THREAD

**Issue by stein2nd** [pmmmwh/react-refresh-webpack-plugin#845]
npm warn deprecated rimraf@3.0.2: 
Rimraf versions prior to v4 are no longer supported
![＠pmmmwhreact-ref resh-webpack-plugin](https://github.com/pmmmwh/react-refresh-webpack-plugin/assets/531628/ce4e501b-b8a1-4c73-9065-3cfc84b4ae00)

npm warn deprecated glob@7.2.3:
Glob versions prior to v9 are no longer supported
![@jestcore@29 7 0](https://github.com/pmmmwh/react-refresh-webpack-plugin/assets/531628/4666dc1e-e208-4da3-8f93-7f309176a614)

**Comment by pmmmwh** [comment]
Unfortunately we cannot do anything to fix deprecated dependencies from downstream dependencies. This is an integration we want to support but unfortunately the plugin doesn't seem to have much activity these days.
