### ISSUE TITLE
[vulnerabilities] npm displayed a warning "2 high severity vulnerabilities".

### ISSUE THREAD

**Issue by stein2nd** [pmmmwh/react-refresh-webpack-plugin#846]
In the 'react-refresh-webpack-plugin' installation directory, 'ncu', 'ncu -u' and 'npm install -force' were executed in sequence.
![prettser](https://github.com/pmmmwh/react-refresh-webpack-plugin/assets/531628/5eb091c0-e287-4247-b5fb-3b2cb1792461)

> 2 high severity vulnerabilities
> 
> Some issues need review, and may require choosing a different dependency.
> 
> Run `npm audit` for details.

The following is the result of running 'npm audit'.
![Pasted Graphic 3](https://github.com/pmmmwh/react-refresh-webpack-plugin/assets/531628/4bf3e7de-bc4b-410a-a90f-2ca901daa6eb)

**Comment by pmmmwh** [comment]
Hi, `sourcemap-validator` (the package consuming `lodash.template`) is only used in testing - unfortunately the `lodash` team doesn't want to publish a new version to fix this vulnerability, so it is impossible for us to act on.

As for `webpack-dev-middleware`, we currently still support WDSv3 but will drop that in `v0.6.x`.
