### ISSUE TITLE
this plugin is not compatible with webpack-dev-server --inline

### ISSUE THREAD

**Issue by bugzpodder** [pmmmwh/react-refresh-webpack-plugin#87]
I think if you do webpack-dev-server --inline it breaks this plugin.  Took me a long time to figure out, I think it should be mentioned in the README.

**Comment by bugzpodder** [comment]
Cannot repo in the examples directory from this package, closing.

**Comment by pmmmwh** [comment]
> I think if you do `webpack-dev-server --inline` it breaks this plugin.

How did it break for you to be exact?

**Comment by bugzpodder** [comment]
It reloads the page instead of fast-refresh the content.  Taking it out apparently make everything work.  not sure why.

**Comment by pmmmwh** [comment]
> It reloads the page instead of fast-refresh the content. Taking it out apparently make everything work. not sure why.

To be fair, I'm not sure why it broke for you - `inline` mode is by default on (see the [docs](https://webpack.js.org/configuration/dev-server/#devserverinline))
