### ISSUE TITLE
Whole page is reloaded when the root export is an HOC

### ISSUE THREAD

**Issue by renchap** [pmmmwh/react-refresh-webpack-plugin#99]
All my root components are looking like this:

```jsx
const Page = () => (
  <div>My page</div>
)

export default RootPage(Page)
```

When I make a change in the `Page` Component and save the file, the whole page is reloaded. It changing a component used in this page, hot reloading works fine.
If I am not using an HOC as the root export, it also works fine.

I am not sure if there is a way to correctly manage this case, but it would be handy!

**Comment by pmmmwh** [comment]
Is it possible for you to provide a reproducible example for me to look at?

Also - what version of `react-refresh` and the plugin are you on? How is the HOC implemented? (There are some quirks: facebook/react#17142)

**Comment by renchap** [comment]
Nice catch, this was exactly the problem! I created a `wrappedComponent` in my HOC, when switching it to `WrappedComponent` fast refresh works.
I am closing this issue, if you think this needs to be specified somewhere (or logged as a warning? not sure if possible?) please re-open it.

**Comment by pmmmwh** [comment]
> This needs to be specified somewhere?

Probably this should be added to the README alongside the rationale behind this, or maybe even in the React docs. I'll followup.
 
> Logged as a warning?

Not entirely possible, especially detection of JSX is not as straight forward as it seems. Documentation should be good for now.
